/*
 * Positions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.38.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.positions;

import java.time.LocalDate;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AccountBalanceSnapshot model
 */
@JsonPropertyOrder({
  AccountBalanceSnapshot.JSON_PROPERTY_ACCOUNT_NUMBER,
  AccountBalanceSnapshot.JSON_PROPERTY_CURRENCY,
  AccountBalanceSnapshot.JSON_PROPERTY_CASH_BALANCE,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_EQUITY_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_EQUITY_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_DERIVATIVE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_DERIVATIVE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_FUTURES_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_FUTURES_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_FUTURES_DERIVATIVE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_FUTURES_DERIVATIVE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_MARGINEABLE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_MARGINEABLE_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_MARGIN_EQUITY,
  AccountBalanceSnapshot.JSON_PROPERTY_EQUITY_BUYING_POWER,
  AccountBalanceSnapshot.JSON_PROPERTY_DERIVATIVE_BUYING_POWER,
  AccountBalanceSnapshot.JSON_PROPERTY_DAY_TRADING_BUYING_POWER,
  AccountBalanceSnapshot.JSON_PROPERTY_FUTURES_MARGIN_REQUIREMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_AVAILABLE_TRADING_FUNDS,
  AccountBalanceSnapshot.JSON_PROPERTY_MAINTENANCE_REQUIREMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_MAINTENANCE_CALL_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_REG_T_CALL_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_DAY_TRADING_CALL_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_DAY_EQUITY_CALL_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_NET_LIQUIDATING_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_CASH_AVAILABLE_TO_WITHDRAW,
  AccountBalanceSnapshot.JSON_PROPERTY_DAY_TRADE_EXCESS,
  AccountBalanceSnapshot.JSON_PROPERTY_PENDING_CASH,
  AccountBalanceSnapshot.JSON_PROPERTY_PENDING_CASH_EFFECT,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_CRYPTOCURRENCY_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SHORT_CRYPTOCURRENCY_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_CRYPTOCURRENCY_MARGIN_REQUIREMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_AMOUNT,
  AccountBalanceSnapshot.JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_EFFECT,
  AccountBalanceSnapshot.JSON_PROPERTY_CLOSED_LOOP_AVAILABLE_BALANCE,
  AccountBalanceSnapshot.JSON_PROPERTY_EQUITY_OFFERING_MARGIN_REQUIREMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_LONG_BOND_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_BOND_MARGIN_REQUIREMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_USED_DERIVATIVE_BUYING_POWER,
  AccountBalanceSnapshot.JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_VALUE,
  AccountBalanceSnapshot.JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_APEX_ADJUSTMENT,
  AccountBalanceSnapshot.JSON_PROPERTY_TOTAL_SETTLE_BALANCE,
  AccountBalanceSnapshot.JSON_PROPERTY_MARGIN_SETTLE_BALANCE,
  AccountBalanceSnapshot.JSON_PROPERTY_CASH_SETTLE_BALANCE,
  AccountBalanceSnapshot.JSON_PROPERTY_SMA_EQUITY_OPTION_BUYING_POWER,
  AccountBalanceSnapshot.JSON_PROPERTY_SNAPSHOT_DATE,
  AccountBalanceSnapshot.JSON_PROPERTY_TIME_OF_DAY,
  AccountBalanceSnapshot.JSON_PROPERTY_FIXED_INCOME_SECURITY_MARGIN_REQUIREMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-17T09:38:55.964775200+02:00[Europe/Berlin]")
@JsonIgnoreProperties(ignoreUnknown = true)
public class AccountBalanceSnapshot {
  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_CASH_BALANCE = "cash-balance";
  private Double cashBalance;

  public static final String JSON_PROPERTY_LONG_EQUITY_VALUE = "long-equity-value";
  private Double longEquityValue;

  public static final String JSON_PROPERTY_SHORT_EQUITY_VALUE = "short-equity-value";
  private Double shortEquityValue;

  public static final String JSON_PROPERTY_LONG_DERIVATIVE_VALUE = "long-derivative-value";
  private Double longDerivativeValue;

  public static final String JSON_PROPERTY_SHORT_DERIVATIVE_VALUE = "short-derivative-value";
  private Double shortDerivativeValue;

  public static final String JSON_PROPERTY_LONG_FUTURES_VALUE = "long-futures-value";
  private Double longFuturesValue;

  public static final String JSON_PROPERTY_SHORT_FUTURES_VALUE = "short-futures-value";
  private Double shortFuturesValue;

  public static final String JSON_PROPERTY_LONG_FUTURES_DERIVATIVE_VALUE = "long-futures-derivative-value";
  private Double longFuturesDerivativeValue;

  public static final String JSON_PROPERTY_SHORT_FUTURES_DERIVATIVE_VALUE = "short-futures-derivative-value";
  private Double shortFuturesDerivativeValue;

  public static final String JSON_PROPERTY_LONG_MARGINEABLE_VALUE = "long-margineable-value";
  private Double longMargineableValue;

  public static final String JSON_PROPERTY_SHORT_MARGINEABLE_VALUE = "short-margineable-value";
  private Double shortMargineableValue;

  public static final String JSON_PROPERTY_MARGIN_EQUITY = "margin-equity";
  private Double marginEquity;

  public static final String JSON_PROPERTY_EQUITY_BUYING_POWER = "equity-buying-power";
  private Double equityBuyingPower;

  public static final String JSON_PROPERTY_DERIVATIVE_BUYING_POWER = "derivative-buying-power";
  private Double derivativeBuyingPower;

  public static final String JSON_PROPERTY_DAY_TRADING_BUYING_POWER = "day-trading-buying-power";
  private Double dayTradingBuyingPower;

  public static final String JSON_PROPERTY_FUTURES_MARGIN_REQUIREMENT = "futures-margin-requirement";
  private Double futuresMarginRequirement;

  public static final String JSON_PROPERTY_AVAILABLE_TRADING_FUNDS = "available-trading-funds";
  private Double availableTradingFunds;

  public static final String JSON_PROPERTY_MAINTENANCE_REQUIREMENT = "maintenance-requirement";
  private Double maintenanceRequirement;

  public static final String JSON_PROPERTY_MAINTENANCE_CALL_VALUE = "maintenance-call-value";
  private Double maintenanceCallValue;

  public static final String JSON_PROPERTY_REG_T_CALL_VALUE = "reg-t-call-value";
  private Double regTCallValue;

  public static final String JSON_PROPERTY_DAY_TRADING_CALL_VALUE = "day-trading-call-value";
  private Double dayTradingCallValue;

  public static final String JSON_PROPERTY_DAY_EQUITY_CALL_VALUE = "day-equity-call-value";
  private Double dayEquityCallValue;

  public static final String JSON_PROPERTY_NET_LIQUIDATING_VALUE = "net-liquidating-value";
  private Double netLiquidatingValue;

  public static final String JSON_PROPERTY_CASH_AVAILABLE_TO_WITHDRAW = "cash-available-to-withdraw";
  private Double cashAvailableToWithdraw;

  public static final String JSON_PROPERTY_DAY_TRADE_EXCESS = "day-trade-excess";
  private Double dayTradeExcess;

  public static final String JSON_PROPERTY_PENDING_CASH = "pending-cash";
  private Double pendingCash;

  public static final String JSON_PROPERTY_PENDING_CASH_EFFECT = "pending-cash-effect";
  private String pendingCashEffect;

  public static final String JSON_PROPERTY_LONG_CRYPTOCURRENCY_VALUE = "long-cryptocurrency-value";
  private Double longCryptocurrencyValue;

  public static final String JSON_PROPERTY_SHORT_CRYPTOCURRENCY_VALUE = "short-cryptocurrency-value";
  private Double shortCryptocurrencyValue;

  public static final String JSON_PROPERTY_CRYPTOCURRENCY_MARGIN_REQUIREMENT = "cryptocurrency-margin-requirement";
  private Double cryptocurrencyMarginRequirement;

  public static final String JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_AMOUNT = "unsettled-cryptocurrency-fiat-amount";
  private Double unsettledCryptocurrencyFiatAmount;

  public static final String JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_EFFECT = "unsettled-cryptocurrency-fiat-effect";
  private String unsettledCryptocurrencyFiatEffect;

  public static final String JSON_PROPERTY_CLOSED_LOOP_AVAILABLE_BALANCE = "closed-loop-available-balance";
  private Double closedLoopAvailableBalance;

  public static final String JSON_PROPERTY_EQUITY_OFFERING_MARGIN_REQUIREMENT = "equity-offering-margin-requirement";
  private Double equityOfferingMarginRequirement;

  public static final String JSON_PROPERTY_LONG_BOND_VALUE = "long-bond-value";
  private Double longBondValue;

  public static final String JSON_PROPERTY_BOND_MARGIN_REQUIREMENT = "bond-margin-requirement";
  private Double bondMarginRequirement;

  public static final String JSON_PROPERTY_USED_DERIVATIVE_BUYING_POWER = "used-derivative-buying-power";
  private Double usedDerivativeBuyingPower;

  public static final String JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_VALUE = "special-memorandum-account-value";
  private Double specialMemorandumAccountValue;

  public static final String JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_APEX_ADJUSTMENT = "special-memorandum-account-apex-adjustment";
  private Double specialMemorandumAccountApexAdjustment;

  public static final String JSON_PROPERTY_TOTAL_SETTLE_BALANCE = "total-settle-balance";
  private Double totalSettleBalance;

  public static final String JSON_PROPERTY_MARGIN_SETTLE_BALANCE = "margin-settle-balance";
  private Double marginSettleBalance;

  public static final String JSON_PROPERTY_CASH_SETTLE_BALANCE = "cash-settle-balance";
  private Double cashSettleBalance;

  public static final String JSON_PROPERTY_SMA_EQUITY_OPTION_BUYING_POWER = "sma-equity-option-buying-power";
  private Double smaEquityOptionBuyingPower;

  public static final String JSON_PROPERTY_SNAPSHOT_DATE = "snapshot-date";
  private LocalDate snapshotDate;

  public static final String JSON_PROPERTY_TIME_OF_DAY = "time-of-day";
  private String timeOfDay;

  public static final String JSON_PROPERTY_FIXED_INCOME_SECURITY_MARGIN_REQUIREMENT = "fixed-income-security-margin-requirement";
  private Double fixedIncomeSecurityMarginRequirement;
  
  public AccountBalanceSnapshot() {
  }

  public AccountBalanceSnapshot accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public AccountBalanceSnapshot currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * 
   * @return currency
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public AccountBalanceSnapshot cashBalance(Double cashBalance) {
    
    this.cashBalance = cashBalance;
    return this;
  }

   /**
   * 
   * @return cashBalance
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCashBalance() {
    return cashBalance;
  }


  @JsonProperty(JSON_PROPERTY_CASH_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashBalance(Double cashBalance) {
    this.cashBalance = cashBalance;
  }


  public AccountBalanceSnapshot longEquityValue(Double longEquityValue) {
    
    this.longEquityValue = longEquityValue;
    return this;
  }

   /**
   * 
   * @return longEquityValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_EQUITY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongEquityValue() {
    return longEquityValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_EQUITY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongEquityValue(Double longEquityValue) {
    this.longEquityValue = longEquityValue;
  }


  public AccountBalanceSnapshot shortEquityValue(Double shortEquityValue) {
    
    this.shortEquityValue = shortEquityValue;
    return this;
  }

   /**
   * 
   * @return shortEquityValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_EQUITY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortEquityValue() {
    return shortEquityValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_EQUITY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortEquityValue(Double shortEquityValue) {
    this.shortEquityValue = shortEquityValue;
  }


  public AccountBalanceSnapshot longDerivativeValue(Double longDerivativeValue) {
    
    this.longDerivativeValue = longDerivativeValue;
    return this;
  }

   /**
   * 
   * @return longDerivativeValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongDerivativeValue() {
    return longDerivativeValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongDerivativeValue(Double longDerivativeValue) {
    this.longDerivativeValue = longDerivativeValue;
  }


  public AccountBalanceSnapshot shortDerivativeValue(Double shortDerivativeValue) {
    
    this.shortDerivativeValue = shortDerivativeValue;
    return this;
  }

   /**
   * 
   * @return shortDerivativeValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortDerivativeValue() {
    return shortDerivativeValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortDerivativeValue(Double shortDerivativeValue) {
    this.shortDerivativeValue = shortDerivativeValue;
  }


  public AccountBalanceSnapshot longFuturesValue(Double longFuturesValue) {
    
    this.longFuturesValue = longFuturesValue;
    return this;
  }

   /**
   * 
   * @return longFuturesValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_FUTURES_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongFuturesValue() {
    return longFuturesValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_FUTURES_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongFuturesValue(Double longFuturesValue) {
    this.longFuturesValue = longFuturesValue;
  }


  public AccountBalanceSnapshot shortFuturesValue(Double shortFuturesValue) {
    
    this.shortFuturesValue = shortFuturesValue;
    return this;
  }

   /**
   * 
   * @return shortFuturesValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_FUTURES_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortFuturesValue() {
    return shortFuturesValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_FUTURES_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortFuturesValue(Double shortFuturesValue) {
    this.shortFuturesValue = shortFuturesValue;
  }


  public AccountBalanceSnapshot longFuturesDerivativeValue(Double longFuturesDerivativeValue) {
    
    this.longFuturesDerivativeValue = longFuturesDerivativeValue;
    return this;
  }

   /**
   * 
   * @return longFuturesDerivativeValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_FUTURES_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongFuturesDerivativeValue() {
    return longFuturesDerivativeValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_FUTURES_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongFuturesDerivativeValue(Double longFuturesDerivativeValue) {
    this.longFuturesDerivativeValue = longFuturesDerivativeValue;
  }


  public AccountBalanceSnapshot shortFuturesDerivativeValue(Double shortFuturesDerivativeValue) {
    
    this.shortFuturesDerivativeValue = shortFuturesDerivativeValue;
    return this;
  }

   /**
   * 
   * @return shortFuturesDerivativeValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_FUTURES_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortFuturesDerivativeValue() {
    return shortFuturesDerivativeValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_FUTURES_DERIVATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortFuturesDerivativeValue(Double shortFuturesDerivativeValue) {
    this.shortFuturesDerivativeValue = shortFuturesDerivativeValue;
  }


  public AccountBalanceSnapshot longMargineableValue(Double longMargineableValue) {
    
    this.longMargineableValue = longMargineableValue;
    return this;
  }

   /**
   * 
   * @return longMargineableValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_MARGINEABLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongMargineableValue() {
    return longMargineableValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_MARGINEABLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongMargineableValue(Double longMargineableValue) {
    this.longMargineableValue = longMargineableValue;
  }


  public AccountBalanceSnapshot shortMargineableValue(Double shortMargineableValue) {
    
    this.shortMargineableValue = shortMargineableValue;
    return this;
  }

   /**
   * 
   * @return shortMargineableValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_MARGINEABLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortMargineableValue() {
    return shortMargineableValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_MARGINEABLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortMargineableValue(Double shortMargineableValue) {
    this.shortMargineableValue = shortMargineableValue;
  }


  public AccountBalanceSnapshot marginEquity(Double marginEquity) {
    
    this.marginEquity = marginEquity;
    return this;
  }

   /**
   * 
   * @return marginEquity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARGIN_EQUITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMarginEquity() {
    return marginEquity;
  }


  @JsonProperty(JSON_PROPERTY_MARGIN_EQUITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarginEquity(Double marginEquity) {
    this.marginEquity = marginEquity;
  }


  public AccountBalanceSnapshot equityBuyingPower(Double equityBuyingPower) {
    
    this.equityBuyingPower = equityBuyingPower;
    return this;
  }

   /**
   * 
   * @return equityBuyingPower
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUITY_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getEquityBuyingPower() {
    return equityBuyingPower;
  }


  @JsonProperty(JSON_PROPERTY_EQUITY_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquityBuyingPower(Double equityBuyingPower) {
    this.equityBuyingPower = equityBuyingPower;
  }


  public AccountBalanceSnapshot derivativeBuyingPower(Double derivativeBuyingPower) {
    
    this.derivativeBuyingPower = derivativeBuyingPower;
    return this;
  }

   /**
   * 
   * @return derivativeBuyingPower
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DERIVATIVE_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDerivativeBuyingPower() {
    return derivativeBuyingPower;
  }


  @JsonProperty(JSON_PROPERTY_DERIVATIVE_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDerivativeBuyingPower(Double derivativeBuyingPower) {
    this.derivativeBuyingPower = derivativeBuyingPower;
  }


  public AccountBalanceSnapshot dayTradingBuyingPower(Double dayTradingBuyingPower) {
    
    this.dayTradingBuyingPower = dayTradingBuyingPower;
    return this;
  }

   /**
   * 
   * @return dayTradingBuyingPower
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DAY_TRADING_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDayTradingBuyingPower() {
    return dayTradingBuyingPower;
  }


  @JsonProperty(JSON_PROPERTY_DAY_TRADING_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayTradingBuyingPower(Double dayTradingBuyingPower) {
    this.dayTradingBuyingPower = dayTradingBuyingPower;
  }


  public AccountBalanceSnapshot futuresMarginRequirement(Double futuresMarginRequirement) {
    
    this.futuresMarginRequirement = futuresMarginRequirement;
    return this;
  }

   /**
   * 
   * @return futuresMarginRequirement
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUTURES_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFuturesMarginRequirement() {
    return futuresMarginRequirement;
  }


  @JsonProperty(JSON_PROPERTY_FUTURES_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFuturesMarginRequirement(Double futuresMarginRequirement) {
    this.futuresMarginRequirement = futuresMarginRequirement;
  }


  public AccountBalanceSnapshot availableTradingFunds(Double availableTradingFunds) {
    
    this.availableTradingFunds = availableTradingFunds;
    return this;
  }

   /**
   * 
   * @return availableTradingFunds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVAILABLE_TRADING_FUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAvailableTradingFunds() {
    return availableTradingFunds;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE_TRADING_FUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableTradingFunds(Double availableTradingFunds) {
    this.availableTradingFunds = availableTradingFunds;
  }


  public AccountBalanceSnapshot maintenanceRequirement(Double maintenanceRequirement) {
    
    this.maintenanceRequirement = maintenanceRequirement;
    return this;
  }

   /**
   * 
   * @return maintenanceRequirement
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAINTENANCE_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaintenanceRequirement() {
    return maintenanceRequirement;
  }


  @JsonProperty(JSON_PROPERTY_MAINTENANCE_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaintenanceRequirement(Double maintenanceRequirement) {
    this.maintenanceRequirement = maintenanceRequirement;
  }


  public AccountBalanceSnapshot maintenanceCallValue(Double maintenanceCallValue) {
    
    this.maintenanceCallValue = maintenanceCallValue;
    return this;
  }

   /**
   * 
   * @return maintenanceCallValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAINTENANCE_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaintenanceCallValue() {
    return maintenanceCallValue;
  }


  @JsonProperty(JSON_PROPERTY_MAINTENANCE_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaintenanceCallValue(Double maintenanceCallValue) {
    this.maintenanceCallValue = maintenanceCallValue;
  }


  public AccountBalanceSnapshot regTCallValue(Double regTCallValue) {
    
    this.regTCallValue = regTCallValue;
    return this;
  }

   /**
   * 
   * @return regTCallValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REG_T_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRegTCallValue() {
    return regTCallValue;
  }


  @JsonProperty(JSON_PROPERTY_REG_T_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegTCallValue(Double regTCallValue) {
    this.regTCallValue = regTCallValue;
  }


  public AccountBalanceSnapshot dayTradingCallValue(Double dayTradingCallValue) {
    
    this.dayTradingCallValue = dayTradingCallValue;
    return this;
  }

   /**
   * 
   * @return dayTradingCallValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DAY_TRADING_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDayTradingCallValue() {
    return dayTradingCallValue;
  }


  @JsonProperty(JSON_PROPERTY_DAY_TRADING_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayTradingCallValue(Double dayTradingCallValue) {
    this.dayTradingCallValue = dayTradingCallValue;
  }


  public AccountBalanceSnapshot dayEquityCallValue(Double dayEquityCallValue) {
    
    this.dayEquityCallValue = dayEquityCallValue;
    return this;
  }

   /**
   * 
   * @return dayEquityCallValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DAY_EQUITY_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDayEquityCallValue() {
    return dayEquityCallValue;
  }


  @JsonProperty(JSON_PROPERTY_DAY_EQUITY_CALL_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayEquityCallValue(Double dayEquityCallValue) {
    this.dayEquityCallValue = dayEquityCallValue;
  }


  public AccountBalanceSnapshot netLiquidatingValue(Double netLiquidatingValue) {
    
    this.netLiquidatingValue = netLiquidatingValue;
    return this;
  }

   /**
   * 
   * @return netLiquidatingValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NET_LIQUIDATING_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getNetLiquidatingValue() {
    return netLiquidatingValue;
  }


  @JsonProperty(JSON_PROPERTY_NET_LIQUIDATING_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetLiquidatingValue(Double netLiquidatingValue) {
    this.netLiquidatingValue = netLiquidatingValue;
  }


  public AccountBalanceSnapshot cashAvailableToWithdraw(Double cashAvailableToWithdraw) {
    
    this.cashAvailableToWithdraw = cashAvailableToWithdraw;
    return this;
  }

   /**
   * 
   * @return cashAvailableToWithdraw
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH_AVAILABLE_TO_WITHDRAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCashAvailableToWithdraw() {
    return cashAvailableToWithdraw;
  }


  @JsonProperty(JSON_PROPERTY_CASH_AVAILABLE_TO_WITHDRAW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashAvailableToWithdraw(Double cashAvailableToWithdraw) {
    this.cashAvailableToWithdraw = cashAvailableToWithdraw;
  }


  public AccountBalanceSnapshot dayTradeExcess(Double dayTradeExcess) {
    
    this.dayTradeExcess = dayTradeExcess;
    return this;
  }

   /**
   * 
   * @return dayTradeExcess
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DAY_TRADE_EXCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDayTradeExcess() {
    return dayTradeExcess;
  }


  @JsonProperty(JSON_PROPERTY_DAY_TRADE_EXCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayTradeExcess(Double dayTradeExcess) {
    this.dayTradeExcess = dayTradeExcess;
  }


  public AccountBalanceSnapshot pendingCash(Double pendingCash) {
    
    this.pendingCash = pendingCash;
    return this;
  }

   /**
   * 
   * @return pendingCash
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPendingCash() {
    return pendingCash;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCash(Double pendingCash) {
    this.pendingCash = pendingCash;
  }


  public AccountBalanceSnapshot pendingCashEffect(String pendingCashEffect) {
    
    this.pendingCashEffect = pendingCashEffect;
    return this;
  }

   /**
   * 
   * @return pendingCashEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPendingCashEffect() {
    return pendingCashEffect;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCashEffect(String pendingCashEffect) {
    this.pendingCashEffect = pendingCashEffect;
  }


  public AccountBalanceSnapshot longCryptocurrencyValue(Double longCryptocurrencyValue) {
    
    this.longCryptocurrencyValue = longCryptocurrencyValue;
    return this;
  }

   /**
   * 
   * @return longCryptocurrencyValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_CRYPTOCURRENCY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongCryptocurrencyValue() {
    return longCryptocurrencyValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_CRYPTOCURRENCY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongCryptocurrencyValue(Double longCryptocurrencyValue) {
    this.longCryptocurrencyValue = longCryptocurrencyValue;
  }


  public AccountBalanceSnapshot shortCryptocurrencyValue(Double shortCryptocurrencyValue) {
    
    this.shortCryptocurrencyValue = shortCryptocurrencyValue;
    return this;
  }

   /**
   * 
   * @return shortCryptocurrencyValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHORT_CRYPTOCURRENCY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShortCryptocurrencyValue() {
    return shortCryptocurrencyValue;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_CRYPTOCURRENCY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortCryptocurrencyValue(Double shortCryptocurrencyValue) {
    this.shortCryptocurrencyValue = shortCryptocurrencyValue;
  }


  public AccountBalanceSnapshot cryptocurrencyMarginRequirement(Double cryptocurrencyMarginRequirement) {
    
    this.cryptocurrencyMarginRequirement = cryptocurrencyMarginRequirement;
    return this;
  }

   /**
   * 
   * @return cryptocurrencyMarginRequirement
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CRYPTOCURRENCY_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCryptocurrencyMarginRequirement() {
    return cryptocurrencyMarginRequirement;
  }


  @JsonProperty(JSON_PROPERTY_CRYPTOCURRENCY_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCryptocurrencyMarginRequirement(Double cryptocurrencyMarginRequirement) {
    this.cryptocurrencyMarginRequirement = cryptocurrencyMarginRequirement;
  }


  public AccountBalanceSnapshot unsettledCryptocurrencyFiatAmount(Double unsettledCryptocurrencyFiatAmount) {
    
    this.unsettledCryptocurrencyFiatAmount = unsettledCryptocurrencyFiatAmount;
    return this;
  }

   /**
   * 
   * @return unsettledCryptocurrencyFiatAmount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getUnsettledCryptocurrencyFiatAmount() {
    return unsettledCryptocurrencyFiatAmount;
  }


  @JsonProperty(JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsettledCryptocurrencyFiatAmount(Double unsettledCryptocurrencyFiatAmount) {
    this.unsettledCryptocurrencyFiatAmount = unsettledCryptocurrencyFiatAmount;
  }


  public AccountBalanceSnapshot unsettledCryptocurrencyFiatEffect(String unsettledCryptocurrencyFiatEffect) {
    
    this.unsettledCryptocurrencyFiatEffect = unsettledCryptocurrencyFiatEffect;
    return this;
  }

   /**
   * 
   * @return unsettledCryptocurrencyFiatEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnsettledCryptocurrencyFiatEffect() {
    return unsettledCryptocurrencyFiatEffect;
  }


  @JsonProperty(JSON_PROPERTY_UNSETTLED_CRYPTOCURRENCY_FIAT_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsettledCryptocurrencyFiatEffect(String unsettledCryptocurrencyFiatEffect) {
    this.unsettledCryptocurrencyFiatEffect = unsettledCryptocurrencyFiatEffect;
  }


  public AccountBalanceSnapshot closedLoopAvailableBalance(Double closedLoopAvailableBalance) {
    
    this.closedLoopAvailableBalance = closedLoopAvailableBalance;
    return this;
  }

   /**
   * 
   * @return closedLoopAvailableBalance
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOSED_LOOP_AVAILABLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getClosedLoopAvailableBalance() {
    return closedLoopAvailableBalance;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED_LOOP_AVAILABLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosedLoopAvailableBalance(Double closedLoopAvailableBalance) {
    this.closedLoopAvailableBalance = closedLoopAvailableBalance;
  }


  public AccountBalanceSnapshot equityOfferingMarginRequirement(Double equityOfferingMarginRequirement) {
    
    this.equityOfferingMarginRequirement = equityOfferingMarginRequirement;
    return this;
  }

   /**
   * 
   * @return equityOfferingMarginRequirement
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUITY_OFFERING_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getEquityOfferingMarginRequirement() {
    return equityOfferingMarginRequirement;
  }


  @JsonProperty(JSON_PROPERTY_EQUITY_OFFERING_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquityOfferingMarginRequirement(Double equityOfferingMarginRequirement) {
    this.equityOfferingMarginRequirement = equityOfferingMarginRequirement;
  }


  public AccountBalanceSnapshot longBondValue(Double longBondValue) {
    
    this.longBondValue = longBondValue;
    return this;
  }

   /**
   * 
   * @return longBondValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONG_BOND_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongBondValue() {
    return longBondValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_BOND_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongBondValue(Double longBondValue) {
    this.longBondValue = longBondValue;
  }


  public AccountBalanceSnapshot bondMarginRequirement(Double bondMarginRequirement) {
    
    this.bondMarginRequirement = bondMarginRequirement;
    return this;
  }

   /**
   * 
   * @return bondMarginRequirement
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOND_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBondMarginRequirement() {
    return bondMarginRequirement;
  }


  @JsonProperty(JSON_PROPERTY_BOND_MARGIN_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBondMarginRequirement(Double bondMarginRequirement) {
    this.bondMarginRequirement = bondMarginRequirement;
  }


  public AccountBalanceSnapshot usedDerivativeBuyingPower(Double usedDerivativeBuyingPower) {
    
    this.usedDerivativeBuyingPower = usedDerivativeBuyingPower;
    return this;
  }

   /**
   * 
   * @return usedDerivativeBuyingPower
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USED_DERIVATIVE_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getUsedDerivativeBuyingPower() {
    return usedDerivativeBuyingPower;
  }


  @JsonProperty(JSON_PROPERTY_USED_DERIVATIVE_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsedDerivativeBuyingPower(Double usedDerivativeBuyingPower) {
    this.usedDerivativeBuyingPower = usedDerivativeBuyingPower;
  }


  public AccountBalanceSnapshot specialMemorandumAccountValue(Double specialMemorandumAccountValue) {
    
    this.specialMemorandumAccountValue = specialMemorandumAccountValue;
    return this;
  }

   /**
   * 
   * @return specialMemorandumAccountValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSpecialMemorandumAccountValue() {
    return specialMemorandumAccountValue;
  }


  @JsonProperty(JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecialMemorandumAccountValue(Double specialMemorandumAccountValue) {
    this.specialMemorandumAccountValue = specialMemorandumAccountValue;
  }


  public AccountBalanceSnapshot specialMemorandumAccountApexAdjustment(Double specialMemorandumAccountApexAdjustment) {
    
    this.specialMemorandumAccountApexAdjustment = specialMemorandumAccountApexAdjustment;
    return this;
  }

   /**
   * 
   * @return specialMemorandumAccountApexAdjustment
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_APEX_ADJUSTMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSpecialMemorandumAccountApexAdjustment() {
    return specialMemorandumAccountApexAdjustment;
  }


  @JsonProperty(JSON_PROPERTY_SPECIAL_MEMORANDUM_ACCOUNT_APEX_ADJUSTMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecialMemorandumAccountApexAdjustment(Double specialMemorandumAccountApexAdjustment) {
    this.specialMemorandumAccountApexAdjustment = specialMemorandumAccountApexAdjustment;
  }


  public AccountBalanceSnapshot totalSettleBalance(Double totalSettleBalance) {
    
    this.totalSettleBalance = totalSettleBalance;
    return this;
  }

   /**
   * 
   * @return totalSettleBalance
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalSettleBalance() {
    return totalSettleBalance;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalSettleBalance(Double totalSettleBalance) {
    this.totalSettleBalance = totalSettleBalance;
  }


  public AccountBalanceSnapshot marginSettleBalance(Double marginSettleBalance) {
    
    this.marginSettleBalance = marginSettleBalance;
    return this;
  }

   /**
   * 
   * @return marginSettleBalance
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARGIN_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMarginSettleBalance() {
    return marginSettleBalance;
  }


  @JsonProperty(JSON_PROPERTY_MARGIN_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarginSettleBalance(Double marginSettleBalance) {
    this.marginSettleBalance = marginSettleBalance;
  }


  public AccountBalanceSnapshot cashSettleBalance(Double cashSettleBalance) {
    
    this.cashSettleBalance = cashSettleBalance;
    return this;
  }

   /**
   * 
   * @return cashSettleBalance
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCashSettleBalance() {
    return cashSettleBalance;
  }


  @JsonProperty(JSON_PROPERTY_CASH_SETTLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashSettleBalance(Double cashSettleBalance) {
    this.cashSettleBalance = cashSettleBalance;
  }


  public AccountBalanceSnapshot smaEquityOptionBuyingPower(Double smaEquityOptionBuyingPower) {
    
    this.smaEquityOptionBuyingPower = smaEquityOptionBuyingPower;
    return this;
  }

   /**
   * 
   * @return smaEquityOptionBuyingPower
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMA_EQUITY_OPTION_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSmaEquityOptionBuyingPower() {
    return smaEquityOptionBuyingPower;
  }


  @JsonProperty(JSON_PROPERTY_SMA_EQUITY_OPTION_BUYING_POWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmaEquityOptionBuyingPower(Double smaEquityOptionBuyingPower) {
    this.smaEquityOptionBuyingPower = smaEquityOptionBuyingPower;
  }


  public AccountBalanceSnapshot snapshotDate(LocalDate snapshotDate) {
    
    this.snapshotDate = snapshotDate;
    return this;
  }

   /**
   * 
   * @return snapshotDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SNAPSHOT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getSnapshotDate() {
    return snapshotDate;
  }


  @JsonProperty(JSON_PROPERTY_SNAPSHOT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshotDate(LocalDate snapshotDate) {
    this.snapshotDate = snapshotDate;
  }


  public AccountBalanceSnapshot timeOfDay(String timeOfDay) {
    
    this.timeOfDay = timeOfDay;
    return this;
  }

   /**
   * 
   * @return timeOfDay
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_OF_DAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeOfDay() {
    return timeOfDay;
  }


  @JsonProperty(JSON_PROPERTY_TIME_OF_DAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeOfDay(String timeOfDay) {
    this.timeOfDay = timeOfDay;
  }

  /**
  * 
  * @return fixedIncomeSecurityMarginRequirement
 **/
 @javax.annotation.Nullable
 @JsonProperty(JSON_PROPERTY_FIXED_INCOME_SECURITY_MARGIN_REQUIREMENT)
 @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getFixedIncomeSecurityMarginRequirement() {
	return fixedIncomeSecurityMarginRequirement;
}

 @JsonProperty(JSON_PROPERTY_FIXED_INCOME_SECURITY_MARGIN_REQUIREMENT)
 @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
public void setFixedIncomeSecurityMarginRequirement(Double fixedIncomeSecurityMarginRequirement) {
	this.fixedIncomeSecurityMarginRequirement = fixedIncomeSecurityMarginRequirement;
}

@Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountBalanceSnapshot accountBalanceSnapshot = (AccountBalanceSnapshot) o;
    return Objects.equals(this.accountNumber, accountBalanceSnapshot.accountNumber) &&
        Objects.equals(this.currency, accountBalanceSnapshot.currency) &&
        Objects.equals(this.cashBalance, accountBalanceSnapshot.cashBalance) &&
        Objects.equals(this.longEquityValue, accountBalanceSnapshot.longEquityValue) &&
        Objects.equals(this.shortEquityValue, accountBalanceSnapshot.shortEquityValue) &&
        Objects.equals(this.longDerivativeValue, accountBalanceSnapshot.longDerivativeValue) &&
        Objects.equals(this.shortDerivativeValue, accountBalanceSnapshot.shortDerivativeValue) &&
        Objects.equals(this.longFuturesValue, accountBalanceSnapshot.longFuturesValue) &&
        Objects.equals(this.shortFuturesValue, accountBalanceSnapshot.shortFuturesValue) &&
        Objects.equals(this.longFuturesDerivativeValue, accountBalanceSnapshot.longFuturesDerivativeValue) &&
        Objects.equals(this.shortFuturesDerivativeValue, accountBalanceSnapshot.shortFuturesDerivativeValue) &&
        Objects.equals(this.longMargineableValue, accountBalanceSnapshot.longMargineableValue) &&
        Objects.equals(this.shortMargineableValue, accountBalanceSnapshot.shortMargineableValue) &&
        Objects.equals(this.marginEquity, accountBalanceSnapshot.marginEquity) &&
        Objects.equals(this.equityBuyingPower, accountBalanceSnapshot.equityBuyingPower) &&
        Objects.equals(this.derivativeBuyingPower, accountBalanceSnapshot.derivativeBuyingPower) &&
        Objects.equals(this.dayTradingBuyingPower, accountBalanceSnapshot.dayTradingBuyingPower) &&
        Objects.equals(this.futuresMarginRequirement, accountBalanceSnapshot.futuresMarginRequirement) &&
        Objects.equals(this.availableTradingFunds, accountBalanceSnapshot.availableTradingFunds) &&
        Objects.equals(this.maintenanceRequirement, accountBalanceSnapshot.maintenanceRequirement) &&
        Objects.equals(this.maintenanceCallValue, accountBalanceSnapshot.maintenanceCallValue) &&
        Objects.equals(this.regTCallValue, accountBalanceSnapshot.regTCallValue) &&
        Objects.equals(this.dayTradingCallValue, accountBalanceSnapshot.dayTradingCallValue) &&
        Objects.equals(this.dayEquityCallValue, accountBalanceSnapshot.dayEquityCallValue) &&
        Objects.equals(this.netLiquidatingValue, accountBalanceSnapshot.netLiquidatingValue) &&
        Objects.equals(this.cashAvailableToWithdraw, accountBalanceSnapshot.cashAvailableToWithdraw) &&
        Objects.equals(this.dayTradeExcess, accountBalanceSnapshot.dayTradeExcess) &&
        Objects.equals(this.pendingCash, accountBalanceSnapshot.pendingCash) &&
        Objects.equals(this.pendingCashEffect, accountBalanceSnapshot.pendingCashEffect) &&
        Objects.equals(this.longCryptocurrencyValue, accountBalanceSnapshot.longCryptocurrencyValue) &&
        Objects.equals(this.shortCryptocurrencyValue, accountBalanceSnapshot.shortCryptocurrencyValue) &&
        Objects.equals(this.cryptocurrencyMarginRequirement, accountBalanceSnapshot.cryptocurrencyMarginRequirement) &&
        Objects.equals(this.unsettledCryptocurrencyFiatAmount, accountBalanceSnapshot.unsettledCryptocurrencyFiatAmount) &&
        Objects.equals(this.unsettledCryptocurrencyFiatEffect, accountBalanceSnapshot.unsettledCryptocurrencyFiatEffect) &&
        Objects.equals(this.closedLoopAvailableBalance, accountBalanceSnapshot.closedLoopAvailableBalance) &&
        Objects.equals(this.equityOfferingMarginRequirement, accountBalanceSnapshot.equityOfferingMarginRequirement) &&
        Objects.equals(this.longBondValue, accountBalanceSnapshot.longBondValue) &&
        Objects.equals(this.bondMarginRequirement, accountBalanceSnapshot.bondMarginRequirement) &&
        Objects.equals(this.usedDerivativeBuyingPower, accountBalanceSnapshot.usedDerivativeBuyingPower) &&
        Objects.equals(this.specialMemorandumAccountValue, accountBalanceSnapshot.specialMemorandumAccountValue) &&
        Objects.equals(this.specialMemorandumAccountApexAdjustment, accountBalanceSnapshot.specialMemorandumAccountApexAdjustment) &&
        Objects.equals(this.totalSettleBalance, accountBalanceSnapshot.totalSettleBalance) &&
        Objects.equals(this.marginSettleBalance, accountBalanceSnapshot.marginSettleBalance) &&
        Objects.equals(this.cashSettleBalance, accountBalanceSnapshot.cashSettleBalance) &&
        Objects.equals(this.smaEquityOptionBuyingPower, accountBalanceSnapshot.smaEquityOptionBuyingPower) &&
        Objects.equals(this.snapshotDate, accountBalanceSnapshot.snapshotDate) &&
        Objects.equals(this.timeOfDay, accountBalanceSnapshot.timeOfDay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, currency, cashBalance, longEquityValue, shortEquityValue, longDerivativeValue, shortDerivativeValue, longFuturesValue, shortFuturesValue, longFuturesDerivativeValue, shortFuturesDerivativeValue, longMargineableValue, shortMargineableValue, marginEquity, equityBuyingPower, derivativeBuyingPower, dayTradingBuyingPower, futuresMarginRequirement, availableTradingFunds, maintenanceRequirement, maintenanceCallValue, regTCallValue, dayTradingCallValue, dayEquityCallValue, netLiquidatingValue, cashAvailableToWithdraw, dayTradeExcess, pendingCash, pendingCashEffect, longCryptocurrencyValue, shortCryptocurrencyValue, cryptocurrencyMarginRequirement, unsettledCryptocurrencyFiatAmount, unsettledCryptocurrencyFiatEffect, closedLoopAvailableBalance, equityOfferingMarginRequirement, longBondValue, bondMarginRequirement, usedDerivativeBuyingPower, specialMemorandumAccountValue, specialMemorandumAccountApexAdjustment, totalSettleBalance, marginSettleBalance, cashSettleBalance, smaEquityOptionBuyingPower, snapshotDate, timeOfDay);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountBalanceSnapshot {\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    cashBalance: ").append(toIndentedString(cashBalance)).append("\n");
    sb.append("    longEquityValue: ").append(toIndentedString(longEquityValue)).append("\n");
    sb.append("    shortEquityValue: ").append(toIndentedString(shortEquityValue)).append("\n");
    sb.append("    longDerivativeValue: ").append(toIndentedString(longDerivativeValue)).append("\n");
    sb.append("    shortDerivativeValue: ").append(toIndentedString(shortDerivativeValue)).append("\n");
    sb.append("    longFuturesValue: ").append(toIndentedString(longFuturesValue)).append("\n");
    sb.append("    shortFuturesValue: ").append(toIndentedString(shortFuturesValue)).append("\n");
    sb.append("    longFuturesDerivativeValue: ").append(toIndentedString(longFuturesDerivativeValue)).append("\n");
    sb.append("    shortFuturesDerivativeValue: ").append(toIndentedString(shortFuturesDerivativeValue)).append("\n");
    sb.append("    longMargineableValue: ").append(toIndentedString(longMargineableValue)).append("\n");
    sb.append("    shortMargineableValue: ").append(toIndentedString(shortMargineableValue)).append("\n");
    sb.append("    marginEquity: ").append(toIndentedString(marginEquity)).append("\n");
    sb.append("    equityBuyingPower: ").append(toIndentedString(equityBuyingPower)).append("\n");
    sb.append("    derivativeBuyingPower: ").append(toIndentedString(derivativeBuyingPower)).append("\n");
    sb.append("    dayTradingBuyingPower: ").append(toIndentedString(dayTradingBuyingPower)).append("\n");
    sb.append("    futuresMarginRequirement: ").append(toIndentedString(futuresMarginRequirement)).append("\n");
    sb.append("    availableTradingFunds: ").append(toIndentedString(availableTradingFunds)).append("\n");
    sb.append("    maintenanceRequirement: ").append(toIndentedString(maintenanceRequirement)).append("\n");
    sb.append("    maintenanceCallValue: ").append(toIndentedString(maintenanceCallValue)).append("\n");
    sb.append("    regTCallValue: ").append(toIndentedString(regTCallValue)).append("\n");
    sb.append("    dayTradingCallValue: ").append(toIndentedString(dayTradingCallValue)).append("\n");
    sb.append("    dayEquityCallValue: ").append(toIndentedString(dayEquityCallValue)).append("\n");
    sb.append("    netLiquidatingValue: ").append(toIndentedString(netLiquidatingValue)).append("\n");
    sb.append("    cashAvailableToWithdraw: ").append(toIndentedString(cashAvailableToWithdraw)).append("\n");
    sb.append("    dayTradeExcess: ").append(toIndentedString(dayTradeExcess)).append("\n");
    sb.append("    pendingCash: ").append(toIndentedString(pendingCash)).append("\n");
    sb.append("    pendingCashEffect: ").append(toIndentedString(pendingCashEffect)).append("\n");
    sb.append("    longCryptocurrencyValue: ").append(toIndentedString(longCryptocurrencyValue)).append("\n");
    sb.append("    shortCryptocurrencyValue: ").append(toIndentedString(shortCryptocurrencyValue)).append("\n");
    sb.append("    cryptocurrencyMarginRequirement: ").append(toIndentedString(cryptocurrencyMarginRequirement)).append("\n");
    sb.append("    unsettledCryptocurrencyFiatAmount: ").append(toIndentedString(unsettledCryptocurrencyFiatAmount)).append("\n");
    sb.append("    unsettledCryptocurrencyFiatEffect: ").append(toIndentedString(unsettledCryptocurrencyFiatEffect)).append("\n");
    sb.append("    closedLoopAvailableBalance: ").append(toIndentedString(closedLoopAvailableBalance)).append("\n");
    sb.append("    equityOfferingMarginRequirement: ").append(toIndentedString(equityOfferingMarginRequirement)).append("\n");
    sb.append("    longBondValue: ").append(toIndentedString(longBondValue)).append("\n");
    sb.append("    bondMarginRequirement: ").append(toIndentedString(bondMarginRequirement)).append("\n");
    sb.append("    usedDerivativeBuyingPower: ").append(toIndentedString(usedDerivativeBuyingPower)).append("\n");
    sb.append("    specialMemorandumAccountValue: ").append(toIndentedString(specialMemorandumAccountValue)).append("\n");
    sb.append("    specialMemorandumAccountApexAdjustment: ").append(toIndentedString(specialMemorandumAccountApexAdjustment)).append("\n");
    sb.append("    totalSettleBalance: ").append(toIndentedString(totalSettleBalance)).append("\n");
    sb.append("    marginSettleBalance: ").append(toIndentedString(marginSettleBalance)).append("\n");
    sb.append("    cashSettleBalance: ").append(toIndentedString(cashSettleBalance)).append("\n");
    sb.append("    smaEquityOptionBuyingPower: ").append(toIndentedString(smaEquityOptionBuyingPower)).append("\n");
    sb.append("    snapshotDate: ").append(toIndentedString(snapshotDate)).append("\n");
    sb.append("    timeOfDay: ").append(toIndentedString(timeOfDay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

