/*
 * Transactions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.41.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.transactions;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  TransactionLots.JSON_PROPERTY_ID,
  TransactionLots.JSON_PROPERTY_TRANSACTION_ID,
  TransactionLots.JSON_PROPERTY_QUANTITY,
  TransactionLots.JSON_PROPERTY_PRICE,
  TransactionLots.JSON_PROPERTY_QUANTITY_DIRECTION,
  TransactionLots.JSON_PROPERTY_EXECUTED_AT,
  TransactionLots.JSON_PROPERTY_TRANSACTION_DATE
})
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeName("Transaction_lots")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-07T21:03:17.808404900+02:00[Europe/Berlin]")
public class TransactionLots {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transaction-id";
  private Integer transactionId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Double quantity;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_QUANTITY_DIRECTION = "quantity-direction";
  private String quantityDirection;

  public static final String JSON_PROPERTY_EXECUTED_AT = "executed-at";
  private OffsetDateTime executedAt;

  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transaction-date";
  private LocalDate transactionDate;

  public TransactionLots() {
  }

  public TransactionLots id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public TransactionLots transactionId(Integer transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * 
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTransactionId() {
    return transactionId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionId(Integer transactionId) {
    this.transactionId = transactionId;
  }


  public TransactionLots quantity(Double quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * 
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }


  public TransactionLots price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * 
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public TransactionLots quantityDirection(String quantityDirection) {
    
    this.quantityDirection = quantityDirection;
    return this;
  }

   /**
   * 
   * @return quantityDirection
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuantityDirection() {
    return quantityDirection;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantityDirection(String quantityDirection) {
    this.quantityDirection = quantityDirection;
  }


  public TransactionLots executedAt(OffsetDateTime executedAt) {
    
    this.executedAt = executedAt;
    return this;
  }

   /**
   * 
   * @return executedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExecutedAt() {
    return executedAt;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutedAt(OffsetDateTime executedAt) {
    this.executedAt = executedAt;
  }


  public TransactionLots transactionDate(LocalDate transactionDate) {
    
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * 
   * @return transactionDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getTransactionDate() {
    return transactionDate;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionDate(LocalDate transactionDate) {
    this.transactionDate = transactionDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionLots transactionLots = (TransactionLots) o;
    return Objects.equals(this.id, transactionLots.id) &&
        Objects.equals(this.transactionId, transactionLots.transactionId) &&
        Objects.equals(this.quantity, transactionLots.quantity) &&
        Objects.equals(this.price, transactionLots.price) &&
        Objects.equals(this.quantityDirection, transactionLots.quantityDirection) &&
        Objects.equals(this.executedAt, transactionLots.executedAt) &&
        Objects.equals(this.transactionDate, transactionLots.transactionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, transactionId, quantity, price, quantityDirection, executedAt, transactionDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionLots {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantityDirection: ").append(toIndentedString(quantityDirection)).append("\n");
    sb.append("    executedAt: ").append(toIndentedString(executedAt)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

