/*
 * Transactions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.41.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.transactions;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Transaction model
 */
@JsonPropertyOrder({
  Transaction.JSON_PROPERTY_ID,
  Transaction.JSON_PROPERTY_ACCOUNT_NUMBER,
  Transaction.JSON_PROPERTY_SYMBOL,
  Transaction.JSON_PROPERTY_INSTRUMENT_TYPE,
  Transaction.JSON_PROPERTY_UNDERLYING_SYMBOL,
  Transaction.JSON_PROPERTY_TRANSACTION_TYPE,
  Transaction.JSON_PROPERTY_TRANSACTION_SUB_TYPE,
  Transaction.JSON_PROPERTY_DESCRIPTION,
  Transaction.JSON_PROPERTY_ACTION,
  Transaction.JSON_PROPERTY_QUANTITY,
  Transaction.JSON_PROPERTY_PRICE,
  Transaction.JSON_PROPERTY_EXECUTED_AT,
  Transaction.JSON_PROPERTY_TRANSACTION_DATE,
  Transaction.JSON_PROPERTY_VALUE,
  Transaction.JSON_PROPERTY_VALUE_EFFECT,
  Transaction.JSON_PROPERTY_REGULATORY_FEES,
  Transaction.JSON_PROPERTY_REGULATORY_FEES_EFFECT,
  Transaction.JSON_PROPERTY_CLEARING_FEES,
  Transaction.JSON_PROPERTY_CLEARING_FEES_EFFECT,
  Transaction.JSON_PROPERTY_OTHER_CHARGE,
  Transaction.JSON_PROPERTY_OTHER_CHARGE_EFFECT,
  Transaction.JSON_PROPERTY_OTHER_CHARGE_DESCRIPTION,
  Transaction.JSON_PROPERTY_NET_VALUE,
  Transaction.JSON_PROPERTY_NET_VALUE_EFFECT,
  Transaction.JSON_PROPERTY_COMMISSION,
  Transaction.JSON_PROPERTY_COMMISSION_EFFECT,
  Transaction.JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES,
  Transaction.JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES_EFFECT,
  Transaction.JSON_PROPERTY_IS_ESTIMATED_FEE,
  Transaction.JSON_PROPERTY_EXT_EXCHANGE_ORDER_NUMBER,
  Transaction.JSON_PROPERTY_EXT_GLOBAL_ORDER_NUMBER,
  Transaction.JSON_PROPERTY_EXT_GROUP_ID,
  Transaction.JSON_PROPERTY_EXT_GROUP_FILL_ID,
  Transaction.JSON_PROPERTY_EXT_EXEC_ID,
  Transaction.JSON_PROPERTY_EXEC_ID,
  Transaction.JSON_PROPERTY_EXCHANGE,
  Transaction.JSON_PROPERTY_ORDER_ID,
  Transaction.JSON_PROPERTY_REVERSES_ID,
  Transaction.JSON_PROPERTY_EXCHANGE_AFFILIATION_IDENTIFIER,
  Transaction.JSON_PROPERTY_COST_BASIS_RECONCILIATION_DATE,
  Transaction.JSON_PROPERTY_LOTS,
  Transaction.JSON_PROPERTY_LEG_COUNT,
  Transaction.JSON_PROPERTY_DESTINATION_VENUE,
  Transaction.JSON_PROPERTY_AGENCY_PRICE,
  Transaction.JSON_PROPERTY_PRINCIPAL_PRICE
})
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-07T21:03:17.808404900+02:00[Europe/Berlin]")
public class Transaction {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private String instrumentType;

  public static final String JSON_PROPERTY_UNDERLYING_SYMBOL = "underlying-symbol";
  private String underlyingSymbol;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transaction-type";
  private String transactionType;

  public static final String JSON_PROPERTY_TRANSACTION_SUB_TYPE = "transaction-sub-type";
  private String transactionSubType;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Double quantity;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_EXECUTED_AT = "executed-at";
  private OffsetDateTime executedAt;

  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transaction-date";
  private LocalDate transactionDate;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private String valueEffect;

  public static final String JSON_PROPERTY_REGULATORY_FEES = "regulatory-fees";
  private Double regulatoryFees;

  public static final String JSON_PROPERTY_REGULATORY_FEES_EFFECT = "regulatory-fees-effect";
  private String regulatoryFeesEffect;

  public static final String JSON_PROPERTY_CLEARING_FEES = "clearing-fees";
  private Double clearingFees;

  public static final String JSON_PROPERTY_CLEARING_FEES_EFFECT = "clearing-fees-effect";
  private String clearingFeesEffect;

  public static final String JSON_PROPERTY_OTHER_CHARGE = "other-charge";
  private Double otherCharge;

  public static final String JSON_PROPERTY_OTHER_CHARGE_EFFECT = "other-charge-effect";
  private String otherChargeEffect;

  public static final String JSON_PROPERTY_OTHER_CHARGE_DESCRIPTION = "other-charge-description";
  private String otherChargeDescription;

  public static final String JSON_PROPERTY_NET_VALUE = "net-value";
  private Double netValue;

  public static final String JSON_PROPERTY_NET_VALUE_EFFECT = "net-value-effect";
  private String netValueEffect;

  public static final String JSON_PROPERTY_COMMISSION = "commission";
  private Double commission;

  public static final String JSON_PROPERTY_COMMISSION_EFFECT = "commission-effect";
  private String commissionEffect;

  public static final String JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES = "proprietary-index-option-fees";
  private Double proprietaryIndexOptionFees;

  public static final String JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES_EFFECT = "proprietary-index-option-fees-effect";
  private String proprietaryIndexOptionFeesEffect;

  public static final String JSON_PROPERTY_IS_ESTIMATED_FEE = "is-estimated-fee";
  private Boolean isEstimatedFee;

  public static final String JSON_PROPERTY_EXT_EXCHANGE_ORDER_NUMBER = "ext-exchange-order-number";
  private String extExchangeOrderNumber;

  public static final String JSON_PROPERTY_EXT_GLOBAL_ORDER_NUMBER = "ext-global-order-number";
  private Integer extGlobalOrderNumber;

  public static final String JSON_PROPERTY_EXT_GROUP_ID = "ext-group-id";
  private String extGroupId;

  public static final String JSON_PROPERTY_EXT_GROUP_FILL_ID = "ext-group-fill-id";
  private String extGroupFillId;

  public static final String JSON_PROPERTY_EXT_EXEC_ID = "ext-exec-id";
  private String extExecId;

  public static final String JSON_PROPERTY_EXEC_ID = "exec-id";
  private String execId;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  private String exchange;

  public static final String JSON_PROPERTY_ORDER_ID = "order-id";
  private Integer orderId;

  public static final String JSON_PROPERTY_REVERSES_ID = "reverses-id";
  private Integer reversesId;

  public static final String JSON_PROPERTY_EXCHANGE_AFFILIATION_IDENTIFIER = "exchange-affiliation-identifier";
  private String exchangeAffiliationIdentifier;

  public static final String JSON_PROPERTY_COST_BASIS_RECONCILIATION_DATE = "cost-basis-reconciliation-date";
  private LocalDate costBasisReconciliationDate;

  public static final String JSON_PROPERTY_LOTS = "lots";
  private TransactionLots lots;

  public static final String JSON_PROPERTY_LEG_COUNT = "leg-count";
  private Integer legCount;

  public static final String JSON_PROPERTY_DESTINATION_VENUE = "destination-venue";
  private String destinationVenue;

  public static final String JSON_PROPERTY_AGENCY_PRICE = "agency-price";
  private Double agencyPrice;

  public static final String JSON_PROPERTY_PRINCIPAL_PRICE = "principal-price";
  private Double principalPrice;

  public Transaction() {
  }

  public Transaction id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public Transaction accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public Transaction symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * 
   * @return symbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public Transaction instrumentType(String instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * 
   * @return instrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentType(String instrumentType) {
    this.instrumentType = instrumentType;
  }


  public Transaction underlyingSymbol(String underlyingSymbol) {
    
    this.underlyingSymbol = underlyingSymbol;
    return this;
  }

   /**
   * 
   * @return underlyingSymbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }


  public Transaction transactionType(String transactionType) {
    
    this.transactionType = transactionType;
    return this;
  }

   /**
   * 
   * @return transactionType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }


  public Transaction transactionSubType(String transactionSubType) {
    
    this.transactionSubType = transactionSubType;
    return this;
  }

   /**
   * 
   * @return transactionSubType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_SUB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionSubType() {
    return transactionSubType;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_SUB_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionSubType(String transactionSubType) {
    this.transactionSubType = transactionSubType;
  }


  public Transaction description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Transaction action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * 
   * @return action
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(String action) {
    this.action = action;
  }


  public Transaction quantity(Double quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * 
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }


  public Transaction price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * 
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public Transaction executedAt(OffsetDateTime executedAt) {
    
    this.executedAt = executedAt;
    return this;
  }

   /**
   * 
   * @return executedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExecutedAt() {
    return executedAt;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutedAt(OffsetDateTime executedAt) {
    this.executedAt = executedAt;
  }


  public Transaction transactionDate(LocalDate transactionDate) {
    
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * 
   * @return transactionDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getTransactionDate() {
    return transactionDate;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionDate(LocalDate transactionDate) {
    this.transactionDate = transactionDate;
  }


  public Transaction value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public Transaction valueEffect(String valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * 
   * @return valueEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueEffect(String valueEffect) {
    this.valueEffect = valueEffect;
  }


  public Transaction regulatoryFees(Double regulatoryFees) {
    
    this.regulatoryFees = regulatoryFees;
    return this;
  }

   /**
   * 
   * @return regulatoryFees
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGULATORY_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRegulatoryFees() {
    return regulatoryFees;
  }


  @JsonProperty(JSON_PROPERTY_REGULATORY_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegulatoryFees(Double regulatoryFees) {
    this.regulatoryFees = regulatoryFees;
  }


  public Transaction regulatoryFeesEffect(String regulatoryFeesEffect) {
    
    this.regulatoryFeesEffect = regulatoryFeesEffect;
    return this;
  }

   /**
   * 
   * @return regulatoryFeesEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGULATORY_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegulatoryFeesEffect() {
    return regulatoryFeesEffect;
  }


  @JsonProperty(JSON_PROPERTY_REGULATORY_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegulatoryFeesEffect(String regulatoryFeesEffect) {
    this.regulatoryFeesEffect = regulatoryFeesEffect;
  }


  public Transaction clearingFees(Double clearingFees) {
    
    this.clearingFees = clearingFees;
    return this;
  }

   /**
   * 
   * @return clearingFees
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLEARING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getClearingFees() {
    return clearingFees;
  }


  @JsonProperty(JSON_PROPERTY_CLEARING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClearingFees(Double clearingFees) {
    this.clearingFees = clearingFees;
  }


  public Transaction clearingFeesEffect(String clearingFeesEffect) {
    
    this.clearingFeesEffect = clearingFeesEffect;
    return this;
  }

   /**
   * 
   * @return clearingFeesEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLEARING_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClearingFeesEffect() {
    return clearingFeesEffect;
  }


  @JsonProperty(JSON_PROPERTY_CLEARING_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClearingFeesEffect(String clearingFeesEffect) {
    this.clearingFeesEffect = clearingFeesEffect;
  }


  public Transaction otherCharge(Double otherCharge) {
    
    this.otherCharge = otherCharge;
    return this;
  }

   /**
   * 
   * @return otherCharge
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getOtherCharge() {
    return otherCharge;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherCharge(Double otherCharge) {
    this.otherCharge = otherCharge;
  }


  public Transaction otherChargeEffect(String otherChargeEffect) {
    
    this.otherChargeEffect = otherChargeEffect;
    return this;
  }

   /**
   * 
   * @return otherChargeEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOtherChargeEffect() {
    return otherChargeEffect;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherChargeEffect(String otherChargeEffect) {
    this.otherChargeEffect = otherChargeEffect;
  }


  public Transaction otherChargeDescription(String otherChargeDescription) {
    
    this.otherChargeDescription = otherChargeDescription;
    return this;
  }

   /**
   * 
   * @return otherChargeDescription
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOtherChargeDescription() {
    return otherChargeDescription;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_CHARGE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherChargeDescription(String otherChargeDescription) {
    this.otherChargeDescription = otherChargeDescription;
  }


  public Transaction netValue(Double netValue) {
    
    this.netValue = netValue;
    return this;
  }

   /**
   * 
   * @return netValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NET_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getNetValue() {
    return netValue;
  }


  @JsonProperty(JSON_PROPERTY_NET_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetValue(Double netValue) {
    this.netValue = netValue;
  }


  public Transaction netValueEffect(String netValueEffect) {
    
    this.netValueEffect = netValueEffect;
    return this;
  }

   /**
   * 
   * @return netValueEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NET_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNetValueEffect() {
    return netValueEffect;
  }


  @JsonProperty(JSON_PROPERTY_NET_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetValueEffect(String netValueEffect) {
    this.netValueEffect = netValueEffect;
  }


  public Transaction commission(Double commission) {
    
    this.commission = commission;
    return this;
  }

   /**
   * 
   * @return commission
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCommission() {
    return commission;
  }


  @JsonProperty(JSON_PROPERTY_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommission(Double commission) {
    this.commission = commission;
  }


  public Transaction commissionEffect(String commissionEffect) {
    
    this.commissionEffect = commissionEffect;
    return this;
  }

   /**
   * 
   * @return commissionEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMISSION_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommissionEffect() {
    return commissionEffect;
  }


  @JsonProperty(JSON_PROPERTY_COMMISSION_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissionEffect(String commissionEffect) {
    this.commissionEffect = commissionEffect;
  }


  public Transaction proprietaryIndexOptionFees(Double proprietaryIndexOptionFees) {
    
    this.proprietaryIndexOptionFees = proprietaryIndexOptionFees;
    return this;
  }

   /**
   * 
   * @return proprietaryIndexOptionFees
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getProprietaryIndexOptionFees() {
    return proprietaryIndexOptionFees;
  }


  @JsonProperty(JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProprietaryIndexOptionFees(Double proprietaryIndexOptionFees) {
    this.proprietaryIndexOptionFees = proprietaryIndexOptionFees;
  }


  public Transaction proprietaryIndexOptionFeesEffect(String proprietaryIndexOptionFeesEffect) {
    
    this.proprietaryIndexOptionFeesEffect = proprietaryIndexOptionFeesEffect;
    return this;
  }

   /**
   * 
   * @return proprietaryIndexOptionFeesEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProprietaryIndexOptionFeesEffect() {
    return proprietaryIndexOptionFeesEffect;
  }


  @JsonProperty(JSON_PROPERTY_PROPRIETARY_INDEX_OPTION_FEES_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProprietaryIndexOptionFeesEffect(String proprietaryIndexOptionFeesEffect) {
    this.proprietaryIndexOptionFeesEffect = proprietaryIndexOptionFeesEffect;
  }


  public Transaction isEstimatedFee(Boolean isEstimatedFee) {
    
    this.isEstimatedFee = isEstimatedFee;
    return this;
  }

   /**
   * 
   * @return isEstimatedFee
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_ESTIMATED_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsEstimatedFee() {
    return isEstimatedFee;
  }


  @JsonProperty(JSON_PROPERTY_IS_ESTIMATED_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEstimatedFee(Boolean isEstimatedFee) {
    this.isEstimatedFee = isEstimatedFee;
  }


  public Transaction extExchangeOrderNumber(String extExchangeOrderNumber) {
    
    this.extExchangeOrderNumber = extExchangeOrderNumber;
    return this;
  }

   /**
   * 
   * @return extExchangeOrderNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_EXCHANGE_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtExchangeOrderNumber() {
    return extExchangeOrderNumber;
  }


  @JsonProperty(JSON_PROPERTY_EXT_EXCHANGE_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtExchangeOrderNumber(String extExchangeOrderNumber) {
    this.extExchangeOrderNumber = extExchangeOrderNumber;
  }


  public Transaction extGlobalOrderNumber(Integer extGlobalOrderNumber) {
    
    this.extGlobalOrderNumber = extGlobalOrderNumber;
    return this;
  }

   /**
   * 
   * @return extGlobalOrderNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_GLOBAL_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExtGlobalOrderNumber() {
    return extGlobalOrderNumber;
  }


  @JsonProperty(JSON_PROPERTY_EXT_GLOBAL_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtGlobalOrderNumber(Integer extGlobalOrderNumber) {
    this.extGlobalOrderNumber = extGlobalOrderNumber;
  }


  public Transaction extGroupId(String extGroupId) {
    
    this.extGroupId = extGroupId;
    return this;
  }

   /**
   * 
   * @return extGroupId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtGroupId() {
    return extGroupId;
  }


  @JsonProperty(JSON_PROPERTY_EXT_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtGroupId(String extGroupId) {
    this.extGroupId = extGroupId;
  }


  public Transaction extGroupFillId(String extGroupFillId) {
    
    this.extGroupFillId = extGroupFillId;
    return this;
  }

   /**
   * 
   * @return extGroupFillId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_GROUP_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtGroupFillId() {
    return extGroupFillId;
  }


  @JsonProperty(JSON_PROPERTY_EXT_GROUP_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtGroupFillId(String extGroupFillId) {
    this.extGroupFillId = extGroupFillId;
  }


  public Transaction extExecId(String extExecId) {
    
    this.extExecId = extExecId;
    return this;
  }

   /**
   * 
   * @return extExecId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtExecId() {
    return extExecId;
  }


  @JsonProperty(JSON_PROPERTY_EXT_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtExecId(String extExecId) {
    this.extExecId = extExecId;
  }


  public Transaction execId(String execId) {
    
    this.execId = execId;
    return this;
  }

   /**
   * 
   * @return execId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecId() {
    return execId;
  }


  @JsonProperty(JSON_PROPERTY_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecId(String execId) {
    this.execId = execId;
  }


  public Transaction exchange(String exchange) {
    
    this.exchange = exchange;
    return this;
  }

   /**
   * 
   * @return exchange
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchange() {
    return exchange;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(String exchange) {
    this.exchange = exchange;
  }


  public Transaction orderId(Integer orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * 
   * @return orderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrderId() {
    return orderId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }


  public Transaction reversesId(Integer reversesId) {
    
    this.reversesId = reversesId;
    return this;
  }

   /**
   * 
   * @return reversesId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVERSES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getReversesId() {
    return reversesId;
  }


  @JsonProperty(JSON_PROPERTY_REVERSES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReversesId(Integer reversesId) {
    this.reversesId = reversesId;
  }


  public Transaction exchangeAffiliationIdentifier(String exchangeAffiliationIdentifier) {
    
    this.exchangeAffiliationIdentifier = exchangeAffiliationIdentifier;
    return this;
  }

   /**
   * 
   * @return exchangeAffiliationIdentifier
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE_AFFILIATION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchangeAffiliationIdentifier() {
    return exchangeAffiliationIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_AFFILIATION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeAffiliationIdentifier(String exchangeAffiliationIdentifier) {
    this.exchangeAffiliationIdentifier = exchangeAffiliationIdentifier;
  }


  public Transaction costBasisReconciliationDate(LocalDate costBasisReconciliationDate) {
    
    this.costBasisReconciliationDate = costBasisReconciliationDate;
    return this;
  }

   /**
   * 
   * @return costBasisReconciliationDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COST_BASIS_RECONCILIATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getCostBasisReconciliationDate() {
    return costBasisReconciliationDate;
  }


  @JsonProperty(JSON_PROPERTY_COST_BASIS_RECONCILIATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCostBasisReconciliationDate(LocalDate costBasisReconciliationDate) {
    this.costBasisReconciliationDate = costBasisReconciliationDate;
  }


  public Transaction lots(TransactionLots lots) {
    
    this.lots = lots;
    return this;
  }

   /**
   * Get lots
   * @return lots
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TransactionLots getLots() {
    return lots;
  }


  @JsonProperty(JSON_PROPERTY_LOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLots(TransactionLots lots) {
    this.lots = lots;
  }


  public Transaction legCount(Integer legCount) {
    
    this.legCount = legCount;
    return this;
  }

   /**
   * 
   * @return legCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEG_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLegCount() {
    return legCount;
  }


  @JsonProperty(JSON_PROPERTY_LEG_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegCount(Integer legCount) {
    this.legCount = legCount;
  }


  public Transaction destinationVenue(String destinationVenue) {
    
    this.destinationVenue = destinationVenue;
    return this;
  }

   /**
   * 
   * @return destinationVenue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESTINATION_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationVenue() {
    return destinationVenue;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationVenue(String destinationVenue) {
    this.destinationVenue = destinationVenue;
  }


  public Transaction agencyPrice(Double agencyPrice) {
    
    this.agencyPrice = agencyPrice;
    return this;
  }

   /**
   * 
   * @return agencyPrice
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENCY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAgencyPrice() {
    return agencyPrice;
  }


  @JsonProperty(JSON_PROPERTY_AGENCY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgencyPrice(Double agencyPrice) {
    this.agencyPrice = agencyPrice;
  }


  public Transaction principalPrice(Double principalPrice) {
    
    this.principalPrice = principalPrice;
    return this;
  }

   /**
   * 
   * @return principalPrice
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRINCIPAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrincipalPrice() {
    return principalPrice;
  }


  @JsonProperty(JSON_PROPERTY_PRINCIPAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrincipalPrice(Double principalPrice) {
    this.principalPrice = principalPrice;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.id, transaction.id) &&
        Objects.equals(this.accountNumber, transaction.accountNumber) &&
        Objects.equals(this.symbol, transaction.symbol) &&
        Objects.equals(this.instrumentType, transaction.instrumentType) &&
        Objects.equals(this.underlyingSymbol, transaction.underlyingSymbol) &&
        Objects.equals(this.transactionType, transaction.transactionType) &&
        Objects.equals(this.transactionSubType, transaction.transactionSubType) &&
        Objects.equals(this.description, transaction.description) &&
        Objects.equals(this.action, transaction.action) &&
        Objects.equals(this.quantity, transaction.quantity) &&
        Objects.equals(this.price, transaction.price) &&
        Objects.equals(this.executedAt, transaction.executedAt) &&
        Objects.equals(this.transactionDate, transaction.transactionDate) &&
        Objects.equals(this.value, transaction.value) &&
        Objects.equals(this.valueEffect, transaction.valueEffect) &&
        Objects.equals(this.regulatoryFees, transaction.regulatoryFees) &&
        Objects.equals(this.regulatoryFeesEffect, transaction.regulatoryFeesEffect) &&
        Objects.equals(this.clearingFees, transaction.clearingFees) &&
        Objects.equals(this.clearingFeesEffect, transaction.clearingFeesEffect) &&
        Objects.equals(this.otherCharge, transaction.otherCharge) &&
        Objects.equals(this.otherChargeEffect, transaction.otherChargeEffect) &&
        Objects.equals(this.otherChargeDescription, transaction.otherChargeDescription) &&
        Objects.equals(this.netValue, transaction.netValue) &&
        Objects.equals(this.netValueEffect, transaction.netValueEffect) &&
        Objects.equals(this.commission, transaction.commission) &&
        Objects.equals(this.commissionEffect, transaction.commissionEffect) &&
        Objects.equals(this.proprietaryIndexOptionFees, transaction.proprietaryIndexOptionFees) &&
        Objects.equals(this.proprietaryIndexOptionFeesEffect, transaction.proprietaryIndexOptionFeesEffect) &&
        Objects.equals(this.isEstimatedFee, transaction.isEstimatedFee) &&
        Objects.equals(this.extExchangeOrderNumber, transaction.extExchangeOrderNumber) &&
        Objects.equals(this.extGlobalOrderNumber, transaction.extGlobalOrderNumber) &&
        Objects.equals(this.extGroupId, transaction.extGroupId) &&
        Objects.equals(this.extGroupFillId, transaction.extGroupFillId) &&
        Objects.equals(this.extExecId, transaction.extExecId) &&
        Objects.equals(this.execId, transaction.execId) &&
        Objects.equals(this.exchange, transaction.exchange) &&
        Objects.equals(this.orderId, transaction.orderId) &&
        Objects.equals(this.reversesId, transaction.reversesId) &&
        Objects.equals(this.exchangeAffiliationIdentifier, transaction.exchangeAffiliationIdentifier) &&
        Objects.equals(this.costBasisReconciliationDate, transaction.costBasisReconciliationDate) &&
        Objects.equals(this.lots, transaction.lots) &&
        Objects.equals(this.legCount, transaction.legCount) &&
        Objects.equals(this.destinationVenue, transaction.destinationVenue) &&
        Objects.equals(this.agencyPrice, transaction.agencyPrice) &&
        Objects.equals(this.principalPrice, transaction.principalPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, symbol, instrumentType, underlyingSymbol, transactionType, transactionSubType, description, action, quantity, price, executedAt, transactionDate, value, valueEffect, regulatoryFees, regulatoryFeesEffect, clearingFees, clearingFeesEffect, otherCharge, otherChargeEffect, otherChargeDescription, netValue, netValueEffect, commission, commissionEffect, proprietaryIndexOptionFees, proprietaryIndexOptionFeesEffect, isEstimatedFee, extExchangeOrderNumber, extGlobalOrderNumber, extGroupId, extGroupFillId, extExecId, execId, exchange, orderId, reversesId, exchangeAffiliationIdentifier, costBasisReconciliationDate, lots, legCount, destinationVenue, agencyPrice, principalPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    if (id != null)
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (accountNumber != null)
        sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    if (symbol != null)
        sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    if (instrumentType != null)
        sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    if (underlyingSymbol != null)
        sb.append("    underlyingSymbol: ").append(toIndentedString(underlyingSymbol)).append("\n");
    if (transactionType != null)
        sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    if (transactionSubType != null)
        sb.append("    transactionSubType: ").append(toIndentedString(transactionSubType)).append("\n");
    if (description != null)
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
    if (action != null)
        sb.append("    action: ").append(toIndentedString(action)).append("\n");
    if (quantity != null)
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    if (price != null)
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
    if (executedAt != null)
        sb.append("    executedAt: ").append(toIndentedString(executedAt)).append("\n");
    if (transactionDate != null)
        sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    if (value != null)
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
    if (valueEffect != null)
        sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    if (regulatoryFees != null)
        sb.append("    regulatoryFees: ").append(toIndentedString(regulatoryFees)).append("\n");
    if (regulatoryFeesEffect != null)
        sb.append("    regulatoryFeesEffect: ").append(toIndentedString(regulatoryFeesEffect)).append("\n");
    if (clearingFees != null)
        sb.append("    clearingFees: ").append(toIndentedString(clearingFees)).append("\n");
    if (clearingFeesEffect != null)
        sb.append("    clearingFeesEffect: ").append(toIndentedString(clearingFeesEffect)).append("\n");
    if (otherCharge != null)
        sb.append("    otherCharge: ").append(toIndentedString(otherCharge)).append("\n");
    if (otherChargeEffect != null)
        sb.append("    otherChargeEffect: ").append(toIndentedString(otherChargeEffect)).append("\n");
    if (otherChargeDescription != null)
        sb.append("    otherChargeDescription: ").append(toIndentedString(otherChargeDescription)).append("\n");
    if (netValue != null)
        sb.append("    netValue: ").append(toIndentedString(netValue)).append("\n");
    if (netValueEffect != null)
        sb.append("    netValueEffect: ").append(toIndentedString(netValueEffect)).append("\n");
    if (commission != null)
        sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    if (commissionEffect != null)
        sb.append("    commissionEffect: ").append(toIndentedString(commissionEffect)).append("\n");
    if (proprietaryIndexOptionFees != null)
        sb.append("    proprietaryIndexOptionFees: ").append(toIndentedString(proprietaryIndexOptionFees)).append("\n");
    if (proprietaryIndexOptionFeesEffect != null)
        sb.append("    proprietaryIndexOptionFeesEffect: ").append(toIndentedString(proprietaryIndexOptionFeesEffect)).append("\n");
    if (isEstimatedFee != null)
        sb.append("    isEstimatedFee: ").append(toIndentedString(isEstimatedFee)).append("\n");
    if (extExchangeOrderNumber != null)
        sb.append("    extExchangeOrderNumber: ").append(toIndentedString(extExchangeOrderNumber)).append("\n");
    if (extGlobalOrderNumber != null)
        sb.append("    extGlobalOrderNumber: ").append(toIndentedString(extGlobalOrderNumber)).append("\n");
    if (extGroupId != null)
        sb.append("    extGroupId: ").append(toIndentedString(extGroupId)).append("\n");
    if (extGroupFillId != null)
        sb.append("    extGroupFillId: ").append(toIndentedString(extGroupFillId)).append("\n");
    if (extExecId != null)
        sb.append("    extExecId: ").append(toIndentedString(extExecId)).append("\n");
    if (execId != null)
        sb.append("    execId: ").append(toIndentedString(execId)).append("\n");
    if (exchange != null)
        sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    if (orderId != null)
        sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    if (reversesId != null)
        sb.append("    reversesId: ").append(toIndentedString(reversesId)).append("\n");
    if (exchangeAffiliationIdentifier != null)
        sb.append("    exchangeAffiliationIdentifier: ").append(toIndentedString(exchangeAffiliationIdentifier)).append("\n");
    if (costBasisReconciliationDate != null)
        sb.append("    costBasisReconciliationDate: ").append(toIndentedString(costBasisReconciliationDate)).append("\n");
    if (lots != null)
        sb.append("    lots: ").append(toIndentedString(lots)).append("\n");
    if (legCount != null)
        sb.append("    legCount: ").append(toIndentedString(legCount)).append("\n");
    if (destinationVenue != null)
        sb.append("    destinationVenue: ").append(toIndentedString(destinationVenue)).append("\n");
    if (agencyPrice != null)
        sb.append("    agencyPrice: ").append(toIndentedString(agencyPrice)).append("\n");
    if (principalPrice != null)
        sb.append("    principalPrice: ").append(toIndentedString(principalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

