/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 11.49.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_ID,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_ACTION,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_COMPARATOR,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_INDICATOR,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_IS_THRESHOLD_BASED_ON_NOTIONAL,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_SYMBOL,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_THRESHOLD,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_TRIGGERED_AT,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_TRIGGERED_VALUE,
  ComplexOrderOrdersInnerOrderRuleOrderConditionsInner.JSON_PROPERTY_PRICE_COMPONENTS
})
@JsonTypeName("ComplexOrder_orders_inner_order_rule_order_conditions_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T20:26:17.174013300+02:00[Europe/Berlin]")
public class ComplexOrderOrdersInnerOrderRuleOrderConditionsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  public static final String JSON_PROPERTY_COMPARATOR = "comparator";
  private String comparator;

  public static final String JSON_PROPERTY_INDICATOR = "indicator";
  private String indicator;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private String instrumentType;

  public static final String JSON_PROPERTY_IS_THRESHOLD_BASED_ON_NOTIONAL = "is-threshold-based-on-notional";
  private Boolean isThresholdBasedOnNotional;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  private Double threshold;

  public static final String JSON_PROPERTY_TRIGGERED_AT = "triggered-at";
  private OffsetDateTime triggeredAt;

  public static final String JSON_PROPERTY_TRIGGERED_VALUE = "triggered-value";
  private Double triggeredValue;

  public static final String JSON_PROPERTY_PRICE_COMPONENTS = "price-components";
  private List<ComplexOrderOrdersInnerOrderRuleOrderConditionsInnerPriceComponentsInner> priceComponents;

  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner() {
  }

  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * 
   * @return action
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(String action) {
    this.action = action;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner comparator(String comparator) {
    
    this.comparator = comparator;
    return this;
  }

   /**
   * 
   * @return comparator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComparator() {
    return comparator;
  }


  @JsonProperty(JSON_PROPERTY_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComparator(String comparator) {
    this.comparator = comparator;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner indicator(String indicator) {
    
    this.indicator = indicator;
    return this;
  }

   /**
   * 
   * @return indicator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndicator() {
    return indicator;
  }


  @JsonProperty(JSON_PROPERTY_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndicator(String indicator) {
    this.indicator = indicator;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner instrumentType(String instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * 
   * @return instrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentType(String instrumentType) {
    this.instrumentType = instrumentType;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner isThresholdBasedOnNotional(Boolean isThresholdBasedOnNotional) {
    
    this.isThresholdBasedOnNotional = isThresholdBasedOnNotional;
    return this;
  }

   /**
   * 
   * @return isThresholdBasedOnNotional
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_THRESHOLD_BASED_ON_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsThresholdBasedOnNotional() {
    return isThresholdBasedOnNotional;
  }


  @JsonProperty(JSON_PROPERTY_IS_THRESHOLD_BASED_ON_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsThresholdBasedOnNotional(Boolean isThresholdBasedOnNotional) {
    this.isThresholdBasedOnNotional = isThresholdBasedOnNotional;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * 
   * @return symbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner threshold(Double threshold) {
    
    this.threshold = threshold;
    return this;
  }

   /**
   * 
   * @return threshold
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getThreshold() {
    return threshold;
  }


  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner triggeredAt(OffsetDateTime triggeredAt) {
    
    this.triggeredAt = triggeredAt;
    return this;
  }

   /**
   * 
   * @return triggeredAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRIGGERED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTriggeredAt() {
    return triggeredAt;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGERED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriggeredAt(OffsetDateTime triggeredAt) {
    this.triggeredAt = triggeredAt;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner triggeredValue(Double triggeredValue) {
    
    this.triggeredValue = triggeredValue;
    return this;
  }

   /**
   * 
   * @return triggeredValue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRIGGERED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTriggeredValue() {
    return triggeredValue;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGERED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriggeredValue(Double triggeredValue) {
    this.triggeredValue = triggeredValue;
  }


  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner priceComponents(List<ComplexOrderOrdersInnerOrderRuleOrderConditionsInnerPriceComponentsInner> priceComponents) {
    
    this.priceComponents = priceComponents;
    return this;
  }

  public ComplexOrderOrdersInnerOrderRuleOrderConditionsInner addPriceComponentsItem(ComplexOrderOrdersInnerOrderRuleOrderConditionsInnerPriceComponentsInner priceComponentsItem) {
    if (this.priceComponents == null) {
      this.priceComponents = new ArrayList<>();
    }
    this.priceComponents.add(priceComponentsItem);
    return this;
  }

   /**
   * Get priceComponents
   * @return priceComponents
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ComplexOrderOrdersInnerOrderRuleOrderConditionsInnerPriceComponentsInner> getPriceComponents() {
    return priceComponents;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceComponents(List<ComplexOrderOrdersInnerOrderRuleOrderConditionsInnerPriceComponentsInner> priceComponents) {
    this.priceComponents = priceComponents;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexOrderOrdersInnerOrderRuleOrderConditionsInner complexOrderOrdersInnerOrderRuleOrderConditionsInner = (ComplexOrderOrdersInnerOrderRuleOrderConditionsInner) o;
    return Objects.equals(this.id, complexOrderOrdersInnerOrderRuleOrderConditionsInner.id) &&
        Objects.equals(this.action, complexOrderOrdersInnerOrderRuleOrderConditionsInner.action) &&
        Objects.equals(this.comparator, complexOrderOrdersInnerOrderRuleOrderConditionsInner.comparator) &&
        Objects.equals(this.indicator, complexOrderOrdersInnerOrderRuleOrderConditionsInner.indicator) &&
        Objects.equals(this.instrumentType, complexOrderOrdersInnerOrderRuleOrderConditionsInner.instrumentType) &&
        Objects.equals(this.isThresholdBasedOnNotional, complexOrderOrdersInnerOrderRuleOrderConditionsInner.isThresholdBasedOnNotional) &&
        Objects.equals(this.symbol, complexOrderOrdersInnerOrderRuleOrderConditionsInner.symbol) &&
        Objects.equals(this.threshold, complexOrderOrdersInnerOrderRuleOrderConditionsInner.threshold) &&
        Objects.equals(this.triggeredAt, complexOrderOrdersInnerOrderRuleOrderConditionsInner.triggeredAt) &&
        Objects.equals(this.triggeredValue, complexOrderOrdersInnerOrderRuleOrderConditionsInner.triggeredValue) &&
        Objects.equals(this.priceComponents, complexOrderOrdersInnerOrderRuleOrderConditionsInner.priceComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, action, comparator, indicator, instrumentType, isThresholdBasedOnNotional, symbol, threshold, triggeredAt, triggeredValue, priceComponents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexOrderOrdersInnerOrderRuleOrderConditionsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    comparator: ").append(toIndentedString(comparator)).append("\n");
    sb.append("    indicator: ").append(toIndentedString(indicator)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    isThresholdBasedOnNotional: ").append(toIndentedString(isThresholdBasedOnNotional)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    triggeredAt: ").append(toIndentedString(triggeredAt)).append("\n");
    sb.append("    triggeredValue: ").append(toIndentedString(triggeredValue)).append("\n");
    sb.append("    priceComponents: ").append(toIndentedString(priceComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

