/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 11.49.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_DESTINATION_VENUE,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_EXT_EXEC_ID,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_EXT_GROUP_FILL_ID,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_FILL_ID,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_FILL_PRICE,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_FILLED_AT,
  ComplexOrderOrdersInnerLegsInnerFillsInner.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("ComplexOrder_orders_inner_legs_inner_fills_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T20:26:17.174013300+02:00[Europe/Berlin]")
public class ComplexOrderOrdersInnerLegsInnerFillsInner {
  public static final String JSON_PROPERTY_DESTINATION_VENUE = "destination-venue";
  private String destinationVenue;

  public static final String JSON_PROPERTY_EXT_EXEC_ID = "ext-exec-id";
  private String extExecId;

  public static final String JSON_PROPERTY_EXT_GROUP_FILL_ID = "ext-group-fill-id";
  private String extGroupFillId;

  public static final String JSON_PROPERTY_FILL_ID = "fill-id";
  private String fillId;

  public static final String JSON_PROPERTY_FILL_PRICE = "fill-price";
  private Double fillPrice;

  public static final String JSON_PROPERTY_FILLED_AT = "filled-at";
  private OffsetDateTime filledAt;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private String quantity;

  public ComplexOrderOrdersInnerLegsInnerFillsInner() {
  }

  public ComplexOrderOrdersInnerLegsInnerFillsInner destinationVenue(String destinationVenue) {
    
    this.destinationVenue = destinationVenue;
    return this;
  }

   /**
   * 
   * @return destinationVenue
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESTINATION_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestinationVenue() {
    return destinationVenue;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationVenue(String destinationVenue) {
    this.destinationVenue = destinationVenue;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner extExecId(String extExecId) {
    
    this.extExecId = extExecId;
    return this;
  }

   /**
   * 
   * @return extExecId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtExecId() {
    return extExecId;
  }


  @JsonProperty(JSON_PROPERTY_EXT_EXEC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtExecId(String extExecId) {
    this.extExecId = extExecId;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner extGroupFillId(String extGroupFillId) {
    
    this.extGroupFillId = extGroupFillId;
    return this;
  }

   /**
   * 
   * @return extGroupFillId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXT_GROUP_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtGroupFillId() {
    return extGroupFillId;
  }


  @JsonProperty(JSON_PROPERTY_EXT_GROUP_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtGroupFillId(String extGroupFillId) {
    this.extGroupFillId = extGroupFillId;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner fillId(String fillId) {
    
    this.fillId = fillId;
    return this;
  }

   /**
   * 
   * @return fillId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFillId() {
    return fillId;
  }


  @JsonProperty(JSON_PROPERTY_FILL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFillId(String fillId) {
    this.fillId = fillId;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner fillPrice(Double fillPrice) {
    
    this.fillPrice = fillPrice;
    return this;
  }

   /**
   * 
   * @return fillPrice
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILL_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFillPrice() {
    return fillPrice;
  }


  @JsonProperty(JSON_PROPERTY_FILL_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFillPrice(Double fillPrice) {
    this.fillPrice = fillPrice;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner filledAt(OffsetDateTime filledAt) {
    
    this.filledAt = filledAt;
    return this;
  }

   /**
   * 
   * @return filledAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFilledAt() {
    return filledAt;
  }


  @JsonProperty(JSON_PROPERTY_FILLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilledAt(OffsetDateTime filledAt) {
    this.filledAt = filledAt;
  }


  public ComplexOrderOrdersInnerLegsInnerFillsInner quantity(String quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * 
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexOrderOrdersInnerLegsInnerFillsInner complexOrderOrdersInnerLegsInnerFillsInner = (ComplexOrderOrdersInnerLegsInnerFillsInner) o;
    return Objects.equals(this.destinationVenue, complexOrderOrdersInnerLegsInnerFillsInner.destinationVenue) &&
        Objects.equals(this.extExecId, complexOrderOrdersInnerLegsInnerFillsInner.extExecId) &&
        Objects.equals(this.extGroupFillId, complexOrderOrdersInnerLegsInnerFillsInner.extGroupFillId) &&
        Objects.equals(this.fillId, complexOrderOrdersInnerLegsInnerFillsInner.fillId) &&
        Objects.equals(this.fillPrice, complexOrderOrdersInnerLegsInnerFillsInner.fillPrice) &&
        Objects.equals(this.filledAt, complexOrderOrdersInnerLegsInnerFillsInner.filledAt) &&
        Objects.equals(this.quantity, complexOrderOrdersInnerLegsInnerFillsInner.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationVenue, extExecId, extGroupFillId, fillId, fillPrice, filledAt, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexOrderOrdersInnerLegsInnerFillsInner {\n");
    sb.append("    destinationVenue: ").append(toIndentedString(destinationVenue)).append("\n");
    sb.append("    extExecId: ").append(toIndentedString(extExecId)).append("\n");
    sb.append("    extGroupFillId: ").append(toIndentedString(extGroupFillId)).append("\n");
    sb.append("    fillId: ").append(toIndentedString(fillId)).append("\n");
    sb.append("    fillPrice: ").append(toIndentedString(fillPrice)).append("\n");
    sb.append("    filledAt: ").append(toIndentedString(filledAt)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

