/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 11.49.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Non-current orders. This includes replaced orders, unfilled orders, and terminal orders.
 */
@JsonPropertyOrder({
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_ID,
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_COMPLEX_ORDER_ID,
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_COMPLEX_ORDER_TAG,
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_REPLACES_ORDER_ID,
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_REPLACING_ORDER_ID,
  ComplexOrderRelatedOrdersInner.JSON_PROPERTY_STATUS
})
@JsonTypeName("ComplexOrder_related_orders_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T20:26:17.174013300+02:00[Europe/Berlin]")
public class ComplexOrderRelatedOrdersInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_ID = "complex-order-id";
  private String complexOrderId;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_TAG = "complex-order-tag";
  private String complexOrderTag;

  public static final String JSON_PROPERTY_REPLACES_ORDER_ID = "replaces-order-id";
  private String replacesOrderId;

  public static final String JSON_PROPERTY_REPLACING_ORDER_ID = "replacing-order-id";
  private String replacingOrderId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public ComplexOrderRelatedOrdersInner() {
  }

  public ComplexOrderRelatedOrdersInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ComplexOrderRelatedOrdersInner complexOrderId(String complexOrderId) {
    
    this.complexOrderId = complexOrderId;
    return this;
  }

   /**
   * 
   * @return complexOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderId() {
    return complexOrderId;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderId(String complexOrderId) {
    this.complexOrderId = complexOrderId;
  }


  public ComplexOrderRelatedOrdersInner complexOrderTag(String complexOrderTag) {
    
    this.complexOrderTag = complexOrderTag;
    return this;
  }

   /**
   * 
   * @return complexOrderTag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderTag() {
    return complexOrderTag;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderTag(String complexOrderTag) {
    this.complexOrderTag = complexOrderTag;
  }


  public ComplexOrderRelatedOrdersInner replacesOrderId(String replacesOrderId) {
    
    this.replacesOrderId = replacesOrderId;
    return this;
  }

   /**
   * 
   * @return replacesOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacesOrderId() {
    return replacesOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacesOrderId(String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
  }


  public ComplexOrderRelatedOrdersInner replacingOrderId(String replacingOrderId) {
    
    this.replacingOrderId = replacingOrderId;
    return this;
  }

   /**
   * 
   * @return replacingOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacingOrderId() {
    return replacingOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacingOrderId(String replacingOrderId) {
    this.replacingOrderId = replacingOrderId;
  }


  public ComplexOrderRelatedOrdersInner status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplexOrderRelatedOrdersInner complexOrderRelatedOrdersInner = (ComplexOrderRelatedOrdersInner) o;
    return Objects.equals(this.id, complexOrderRelatedOrdersInner.id) &&
        Objects.equals(this.complexOrderId, complexOrderRelatedOrdersInner.complexOrderId) &&
        Objects.equals(this.complexOrderTag, complexOrderRelatedOrdersInner.complexOrderTag) &&
        Objects.equals(this.replacesOrderId, complexOrderRelatedOrdersInner.replacesOrderId) &&
        Objects.equals(this.replacingOrderId, complexOrderRelatedOrdersInner.replacingOrderId) &&
        Objects.equals(this.status, complexOrderRelatedOrdersInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, complexOrderId, complexOrderTag, replacesOrderId, replacingOrderId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplexOrderRelatedOrdersInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    complexOrderId: ").append(toIndentedString(complexOrderId)).append("\n");
    sb.append("    complexOrderTag: ").append(toIndentedString(complexOrderTag)).append("\n");
    sb.append("    replacesOrderId: ").append(toIndentedString(replacesOrderId)).append("\n");
    sb.append("    replacingOrderId: ").append(toIndentedString(replacingOrderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

