/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  OrderOrderRuleOrderConditionsInnerPriceComponentsInner.JSON_PROPERTY_SYMBOL,
  OrderOrderRuleOrderConditionsInnerPriceComponentsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  OrderOrderRuleOrderConditionsInnerPriceComponentsInner.JSON_PROPERTY_QUANTITY,
  OrderOrderRuleOrderConditionsInnerPriceComponentsInner.JSON_PROPERTY_QUANTITY_DIRECTION
})
@JsonTypeName("Order_order_rule_order_conditions_inner_price_components_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class OrderOrderRuleOrderConditionsInnerPriceComponentsInner {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private String instrumentType;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private String quantity;

  public static final String JSON_PROPERTY_QUANTITY_DIRECTION = "quantity-direction";
  private String quantityDirection;

  public OrderOrderRuleOrderConditionsInnerPriceComponentsInner() {
  }

  public OrderOrderRuleOrderConditionsInnerPriceComponentsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * 
   * @return symbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public OrderOrderRuleOrderConditionsInnerPriceComponentsInner instrumentType(String instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * 
   * @return instrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentType(String instrumentType) {
    this.instrumentType = instrumentType;
  }


  public OrderOrderRuleOrderConditionsInnerPriceComponentsInner quantity(String quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * 
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  public OrderOrderRuleOrderConditionsInnerPriceComponentsInner quantityDirection(String quantityDirection) {
    
    this.quantityDirection = quantityDirection;
    return this;
  }

   /**
   * 
   * @return quantityDirection
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuantityDirection() {
    return quantityDirection;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantityDirection(String quantityDirection) {
    this.quantityDirection = quantityDirection;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderOrderRuleOrderConditionsInnerPriceComponentsInner orderOrderRuleOrderConditionsInnerPriceComponentsInner = (OrderOrderRuleOrderConditionsInnerPriceComponentsInner) o;
    return Objects.equals(this.symbol, orderOrderRuleOrderConditionsInnerPriceComponentsInner.symbol) &&
        Objects.equals(this.instrumentType, orderOrderRuleOrderConditionsInnerPriceComponentsInner.instrumentType) &&
        Objects.equals(this.quantity, orderOrderRuleOrderConditionsInnerPriceComponentsInner.quantity) &&
        Objects.equals(this.quantityDirection, orderOrderRuleOrderConditionsInnerPriceComponentsInner.quantityDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, instrumentType, quantity, quantityDirection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderOrderRuleOrderConditionsInnerPriceComponentsInner {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    quantityDirection: ").append(toIndentedString(quantityDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

