/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Order model
 */
@JsonPropertyOrder({
  Order.JSON_PROPERTY_ID,
  Order.JSON_PROPERTY_ACCOUNT_NUMBER,
  Order.JSON_PROPERTY_TIME_IN_FORCE,
  Order.JSON_PROPERTY_GTC_DATE,
  Order.JSON_PROPERTY_ORDER_TYPE,
  Order.JSON_PROPERTY_SIZE,
  Order.JSON_PROPERTY_UNDERLYING_SYMBOL,
  Order.JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE,
  Order.JSON_PROPERTY_PRICE,
  Order.JSON_PROPERTY_PRICE_EFFECT,
  Order.JSON_PROPERTY_VALUE,
  Order.JSON_PROPERTY_VALUE_EFFECT,
  Order.JSON_PROPERTY_STOP_TRIGGER,
  Order.JSON_PROPERTY_STATUS,
  Order.JSON_PROPERTY_CONTINGENT_STATUS,
  Order.JSON_PROPERTY_CONFIRMATION_STATUS,
  Order.JSON_PROPERTY_CANCELLABLE,
  Order.JSON_PROPERTY_CANCELLED_AT,
  Order.JSON_PROPERTY_CANCEL_USER_ID,
  Order.JSON_PROPERTY_CANCEL_USERNAME,
  Order.JSON_PROPERTY_EDITABLE,
  Order.JSON_PROPERTY_EDITED,
  Order.JSON_PROPERTY_REPLACING_ORDER_ID,
  Order.JSON_PROPERTY_REPLACES_ORDER_ID,
  Order.JSON_PROPERTY_RECEIVED_AT,
  Order.JSON_PROPERTY_UPDATED_AT,
  Order.JSON_PROPERTY_IN_FLIGHT_AT,
  Order.JSON_PROPERTY_LIVE_AT,
  Order.JSON_PROPERTY_REJECT_REASON,
  Order.JSON_PROPERTY_USER_ID,
  Order.JSON_PROPERTY_USERNAME,
  Order.JSON_PROPERTY_TERMINAL_AT,
  Order.JSON_PROPERTY_COMPLEX_ORDER_ID,
  Order.JSON_PROPERTY_COMPLEX_ORDER_TAG,
  Order.JSON_PROPERTY_PREFLIGHT_ID,
  Order.JSON_PROPERTY_GLOBAL_REQUEST_ID,
  Order.JSON_PROPERTY_LEGS,
  Order.JSON_PROPERTY_ORDER_RULE
})
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class Order {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_TIME_IN_FORCE = "time-in-force";
  private String timeInForce;

  public static final String JSON_PROPERTY_GTC_DATE = "gtc-date";
  private LocalDate gtcDate;

  public static final String JSON_PROPERTY_ORDER_TYPE = "order-type";
  private String orderType;

  public static final String JSON_PROPERTY_SIZE = "size";
  private String size;

  public static final String JSON_PROPERTY_UNDERLYING_SYMBOL = "underlying-symbol";
  private String underlyingSymbol;

  public static final String JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE = "underlying-instrument-type";
  private String underlyingInstrumentType;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_PRICE_EFFECT = "price-effect";
  private String priceEffect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private String valueEffect;

  public static final String JSON_PROPERTY_STOP_TRIGGER = "stop-trigger";
  private String stopTrigger;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CONTINGENT_STATUS = "contingent-status";
  private String contingentStatus;

  public static final String JSON_PROPERTY_CONFIRMATION_STATUS = "confirmation-status";
  private String confirmationStatus;

  public static final String JSON_PROPERTY_CANCELLABLE = "cancellable";
  private Boolean cancellable;

  public static final String JSON_PROPERTY_CANCELLED_AT = "cancelled-at";
  private OffsetDateTime cancelledAt;

  public static final String JSON_PROPERTY_CANCEL_USER_ID = "cancel-user-id";
  private String cancelUserId;

  public static final String JSON_PROPERTY_CANCEL_USERNAME = "cancel-username";
  private String cancelUsername;

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  private Boolean editable;

  public static final String JSON_PROPERTY_EDITED = "edited";
  private Boolean edited;

  public static final String JSON_PROPERTY_REPLACING_ORDER_ID = "replacing-order-id";
  private String replacingOrderId;

  public static final String JSON_PROPERTY_REPLACES_ORDER_ID = "replaces-order-id";
  private String replacesOrderId;

  public static final String JSON_PROPERTY_RECEIVED_AT = "received-at";
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated-at";
  private String updatedAt;

  public static final String JSON_PROPERTY_IN_FLIGHT_AT = "in-flight-at";
  private OffsetDateTime inFlightAt;

  public static final String JSON_PROPERTY_LIVE_AT = "live-at";
  private OffsetDateTime liveAt;

  public static final String JSON_PROPERTY_REJECT_REASON = "reject-reason";
  private String rejectReason;

  public static final String JSON_PROPERTY_USER_ID = "user-id";
  private String userId;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_TERMINAL_AT = "terminal-at";
  private OffsetDateTime terminalAt;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_ID = "complex-order-id";
  private String complexOrderId;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_TAG = "complex-order-tag";
  private String complexOrderTag;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public static final String JSON_PROPERTY_GLOBAL_REQUEST_ID = "global-request-id";
  private String globalRequestId;

  public static final String JSON_PROPERTY_LEGS = "legs";
  private List<OrderLegsInner> legs;

  public static final String JSON_PROPERTY_ORDER_RULE = "order-rule";
  private OrderOrderRule orderRule;

  public Order() {
  }

  public Order id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public Order accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public Order timeInForce(String timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * 
   * @return timeInForce
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }


  public Order gtcDate(LocalDate gtcDate) {
    
    this.gtcDate = gtcDate;
    return this;
  }

   /**
   * 
   * @return gtcDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getGtcDate() {
    return gtcDate;
  }


  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGtcDate(LocalDate gtcDate) {
    this.gtcDate = gtcDate;
  }


  public Order orderType(String orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * 
   * @return orderType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }


  public Order size(String size) {
    
    this.size = size;
    return this;
  }

   /**
   * 
   * @return size
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(String size) {
    this.size = size;
  }


  public Order underlyingSymbol(String underlyingSymbol) {
    
    this.underlyingSymbol = underlyingSymbol;
    return this;
  }

   /**
   * 
   * @return underlyingSymbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }


  public Order underlyingInstrumentType(String underlyingInstrumentType) {
    
    this.underlyingInstrumentType = underlyingInstrumentType;
    return this;
  }

   /**
   * 
   * @return underlyingInstrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingInstrumentType() {
    return underlyingInstrumentType;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingInstrumentType(String underlyingInstrumentType) {
    this.underlyingInstrumentType = underlyingInstrumentType;
  }


  public Order price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * 
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public Order priceEffect(String priceEffect) {
    
    this.priceEffect = priceEffect;
    return this;
  }

   /**
   * 
   * @return priceEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPriceEffect() {
    return priceEffect;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceEffect(String priceEffect) {
    this.priceEffect = priceEffect;
  }


  public Order value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public Order valueEffect(String valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * 
   * @return valueEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueEffect(String valueEffect) {
    this.valueEffect = valueEffect;
  }


  public Order stopTrigger(String stopTrigger) {
    
    this.stopTrigger = stopTrigger;
    return this;
  }

   /**
   * 
   * @return stopTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStopTrigger() {
    return stopTrigger;
  }


  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopTrigger(String stopTrigger) {
    this.stopTrigger = stopTrigger;
  }


  public Order status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public Order contingentStatus(String contingentStatus) {
    
    this.contingentStatus = contingentStatus;
    return this;
  }

   /**
   * 
   * @return contingentStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingentStatus() {
    return contingentStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingentStatus(String contingentStatus) {
    this.contingentStatus = contingentStatus;
  }


  public Order confirmationStatus(String confirmationStatus) {
    
    this.confirmationStatus = confirmationStatus;
    return this;
  }

   /**
   * 
   * @return confirmationStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmationStatus() {
    return confirmationStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfirmationStatus(String confirmationStatus) {
    this.confirmationStatus = confirmationStatus;
  }


  public Order cancellable(Boolean cancellable) {
    
    this.cancellable = cancellable;
    return this;
  }

   /**
   * 
   * @return cancellable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancellable() {
    return cancellable;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancellable(Boolean cancellable) {
    this.cancellable = cancellable;
  }


  public Order cancelledAt(OffsetDateTime cancelledAt) {
    
    this.cancelledAt = cancelledAt;
    return this;
  }

   /**
   * 
   * @return cancelledAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public Order cancelUserId(String cancelUserId) {
    
    this.cancelUserId = cancelUserId;
    return this;
  }

   /**
   * 
   * @return cancelUserId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUserId() {
    return cancelUserId;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUserId(String cancelUserId) {
    this.cancelUserId = cancelUserId;
  }


  public Order cancelUsername(String cancelUsername) {
    
    this.cancelUsername = cancelUsername;
    return this;
  }

   /**
   * 
   * @return cancelUsername
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUsername() {
    return cancelUsername;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUsername(String cancelUsername) {
    this.cancelUsername = cancelUsername;
  }


  public Order editable(Boolean editable) {
    
    this.editable = editable;
    return this;
  }

   /**
   * 
   * @return editable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditable(Boolean editable) {
    this.editable = editable;
  }


  public Order edited(Boolean edited) {
    
    this.edited = edited;
    return this;
  }

   /**
   * 
   * @return edited
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEdited() {
    return edited;
  }


  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEdited(Boolean edited) {
    this.edited = edited;
  }


  public Order replacingOrderId(String replacingOrderId) {
    
    this.replacingOrderId = replacingOrderId;
    return this;
  }

   /**
   * 
   * @return replacingOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacingOrderId() {
    return replacingOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacingOrderId(String replacingOrderId) {
    this.replacingOrderId = replacingOrderId;
  }


  public Order replacesOrderId(String replacesOrderId) {
    
    this.replacesOrderId = replacesOrderId;
    return this;
  }

   /**
   * 
   * @return replacesOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacesOrderId() {
    return replacesOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacesOrderId(String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
  }


  public Order receivedAt(OffsetDateTime receivedAt) {
    
    this.receivedAt = receivedAt;
    return this;
  }

   /**
   * 
   * @return receivedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedAt(OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public Order updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Order inFlightAt(OffsetDateTime inFlightAt) {
    
    this.inFlightAt = inFlightAt;
    return this;
  }

   /**
   * 
   * @return inFlightAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getInFlightAt() {
    return inFlightAt;
  }


  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInFlightAt(OffsetDateTime inFlightAt) {
    this.inFlightAt = inFlightAt;
  }


  public Order liveAt(OffsetDateTime liveAt) {
    
    this.liveAt = liveAt;
    return this;
  }

   /**
   * 
   * @return liveAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLiveAt() {
    return liveAt;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveAt(OffsetDateTime liveAt) {
    this.liveAt = liveAt;
  }


  public Order rejectReason(String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

   /**
   * 
   * @return rejectReason
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
  }


  public Order userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 
   * @return userId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  public Order username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * 
   * @return username
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public Order terminalAt(OffsetDateTime terminalAt) {
    
    this.terminalAt = terminalAt;
    return this;
  }

   /**
   * 
   * @return terminalAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTerminalAt() {
    return terminalAt;
  }


  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerminalAt(OffsetDateTime terminalAt) {
    this.terminalAt = terminalAt;
  }


  public Order complexOrderId(String complexOrderId) {
    
    this.complexOrderId = complexOrderId;
    return this;
  }

   /**
   * 
   * @return complexOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderId() {
    return complexOrderId;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderId(String complexOrderId) {
    this.complexOrderId = complexOrderId;
  }


  public Order complexOrderTag(String complexOrderTag) {
    
    this.complexOrderTag = complexOrderTag;
    return this;
  }

   /**
   * 
   * @return complexOrderTag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderTag() {
    return complexOrderTag;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderTag(String complexOrderTag) {
    this.complexOrderTag = complexOrderTag;
  }


  public Order preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * 
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }


  public Order globalRequestId(String globalRequestId) {
    
    this.globalRequestId = globalRequestId;
    return this;
  }

   /**
   * 
   * @return globalRequestId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGlobalRequestId() {
    return globalRequestId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobalRequestId(String globalRequestId) {
    this.globalRequestId = globalRequestId;
  }


  public Order legs(List<OrderLegsInner> legs) {
    
    this.legs = legs;
    return this;
  }

  public Order addLegsItem(OrderLegsInner legsItem) {
    if (this.legs == null) {
      this.legs = new ArrayList<>();
    }
    this.legs.add(legsItem);
    return this;
  }

   /**
   * Get legs
   * @return legs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderLegsInner> getLegs() {
    return legs;
  }


  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegs(List<OrderLegsInner> legs) {
    this.legs = legs;
  }


  public Order orderRule(OrderOrderRule orderRule) {
    
    this.orderRule = orderRule;
    return this;
  }

   /**
   * Get orderRule
   * @return orderRule
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderOrderRule getOrderRule() {
    return orderRule;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderRule(OrderOrderRule orderRule) {
    this.orderRule = orderRule;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.id, order.id) &&
        Objects.equals(this.accountNumber, order.accountNumber) &&
        Objects.equals(this.timeInForce, order.timeInForce) &&
        Objects.equals(this.gtcDate, order.gtcDate) &&
        Objects.equals(this.orderType, order.orderType) &&
        Objects.equals(this.size, order.size) &&
        Objects.equals(this.underlyingSymbol, order.underlyingSymbol) &&
        Objects.equals(this.underlyingInstrumentType, order.underlyingInstrumentType) &&
        Objects.equals(this.price, order.price) &&
        Objects.equals(this.priceEffect, order.priceEffect) &&
        Objects.equals(this.value, order.value) &&
        Objects.equals(this.valueEffect, order.valueEffect) &&
        Objects.equals(this.stopTrigger, order.stopTrigger) &&
        Objects.equals(this.status, order.status) &&
        Objects.equals(this.contingentStatus, order.contingentStatus) &&
        Objects.equals(this.confirmationStatus, order.confirmationStatus) &&
        Objects.equals(this.cancellable, order.cancellable) &&
        Objects.equals(this.cancelledAt, order.cancelledAt) &&
        Objects.equals(this.cancelUserId, order.cancelUserId) &&
        Objects.equals(this.cancelUsername, order.cancelUsername) &&
        Objects.equals(this.editable, order.editable) &&
        Objects.equals(this.edited, order.edited) &&
        Objects.equals(this.replacingOrderId, order.replacingOrderId) &&
        Objects.equals(this.replacesOrderId, order.replacesOrderId) &&
        Objects.equals(this.receivedAt, order.receivedAt) &&
        Objects.equals(this.updatedAt, order.updatedAt) &&
        Objects.equals(this.inFlightAt, order.inFlightAt) &&
        Objects.equals(this.liveAt, order.liveAt) &&
        Objects.equals(this.rejectReason, order.rejectReason) &&
        Objects.equals(this.userId, order.userId) &&
        Objects.equals(this.username, order.username) &&
        Objects.equals(this.terminalAt, order.terminalAt) &&
        Objects.equals(this.complexOrderId, order.complexOrderId) &&
        Objects.equals(this.complexOrderTag, order.complexOrderTag) &&
        Objects.equals(this.preflightId, order.preflightId) &&
        Objects.equals(this.globalRequestId, order.globalRequestId) &&
        Objects.equals(this.legs, order.legs) &&
        Objects.equals(this.orderRule, order.orderRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, timeInForce, gtcDate, orderType, size, underlyingSymbol, underlyingInstrumentType, price, priceEffect, value, valueEffect, stopTrigger, status, contingentStatus, confirmationStatus, cancellable, cancelledAt, cancelUserId, cancelUsername, editable, edited, replacingOrderId, replacesOrderId, receivedAt, updatedAt, inFlightAt, liveAt, rejectReason, userId, username, terminalAt, complexOrderId, complexOrderTag, preflightId, globalRequestId, legs, orderRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    gtcDate: ").append(toIndentedString(gtcDate)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    underlyingSymbol: ").append(toIndentedString(underlyingSymbol)).append("\n");
    sb.append("    underlyingInstrumentType: ").append(toIndentedString(underlyingInstrumentType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceEffect: ").append(toIndentedString(priceEffect)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    sb.append("    stopTrigger: ").append(toIndentedString(stopTrigger)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    contingentStatus: ").append(toIndentedString(contingentStatus)).append("\n");
    sb.append("    confirmationStatus: ").append(toIndentedString(confirmationStatus)).append("\n");
    sb.append("    cancellable: ").append(toIndentedString(cancellable)).append("\n");
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    cancelUserId: ").append(toIndentedString(cancelUserId)).append("\n");
    sb.append("    cancelUsername: ").append(toIndentedString(cancelUsername)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    replacingOrderId: ").append(toIndentedString(replacingOrderId)).append("\n");
    sb.append("    replacesOrderId: ").append(toIndentedString(replacesOrderId)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    inFlightAt: ").append(toIndentedString(inFlightAt)).append("\n");
    sb.append("    liveAt: ").append(toIndentedString(liveAt)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    terminalAt: ").append(toIndentedString(terminalAt)).append("\n");
    sb.append("    complexOrderId: ").append(toIndentedString(complexOrderId)).append("\n");
    sb.append("    complexOrderTag: ").append(toIndentedString(complexOrderTag)).append("\n");
    sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    sb.append("    globalRequestId: ").append(toIndentedString(globalRequestId)).append("\n");
    sb.append("    legs: ").append(toIndentedString(legs)).append("\n");
    sb.append("    orderRule: ").append(toIndentedString(orderRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

