/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  OrderOrderRule.JSON_PROPERTY_ROUTE_AFTER,
  OrderOrderRule.JSON_PROPERTY_ROUTED_AT,
  OrderOrderRule.JSON_PROPERTY_CANCEL_AT,
  OrderOrderRule.JSON_PROPERTY_CANCELLED_AT,
  OrderOrderRule.JSON_PROPERTY_ORDER_CONDITIONS
})
@JsonTypeName("Order_order_rule")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class OrderOrderRule {
  public static final String JSON_PROPERTY_ROUTE_AFTER = "route-after";
  private OffsetDateTime routeAfter;

  public static final String JSON_PROPERTY_ROUTED_AT = "routed-at";
  private OffsetDateTime routedAt;

  public static final String JSON_PROPERTY_CANCEL_AT = "cancel-at";
  private OffsetDateTime cancelAt;

  public static final String JSON_PROPERTY_CANCELLED_AT = "cancelled-at";
  private OffsetDateTime cancelledAt;

  public static final String JSON_PROPERTY_ORDER_CONDITIONS = "order-conditions";
  private List<OrderOrderRuleOrderConditionsInner> orderConditions;

  public OrderOrderRule() {
  }

  public OrderOrderRule routeAfter(OffsetDateTime routeAfter) {
    
    this.routeAfter = routeAfter;
    return this;
  }

   /**
   * 
   * @return routeAfter
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTE_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRouteAfter() {
    return routeAfter;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteAfter(OffsetDateTime routeAfter) {
    this.routeAfter = routeAfter;
  }


  public OrderOrderRule routedAt(OffsetDateTime routedAt) {
    
    this.routedAt = routedAt;
    return this;
  }

   /**
   * 
   * @return routedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRoutedAt() {
    return routedAt;
  }


  @JsonProperty(JSON_PROPERTY_ROUTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutedAt(OffsetDateTime routedAt) {
    this.routedAt = routedAt;
  }


  public OrderOrderRule cancelAt(OffsetDateTime cancelAt) {
    
    this.cancelAt = cancelAt;
    return this;
  }

   /**
   * 
   * @return cancelAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCancelAt() {
    return cancelAt;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelAt(OffsetDateTime cancelAt) {
    this.cancelAt = cancelAt;
  }


  public OrderOrderRule cancelledAt(OffsetDateTime cancelledAt) {
    
    this.cancelledAt = cancelledAt;
    return this;
  }

   /**
   * 
   * @return cancelledAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public OrderOrderRule orderConditions(List<OrderOrderRuleOrderConditionsInner> orderConditions) {
    
    this.orderConditions = orderConditions;
    return this;
  }

  public OrderOrderRule addOrderConditionsItem(OrderOrderRuleOrderConditionsInner orderConditionsItem) {
    if (this.orderConditions == null) {
      this.orderConditions = new ArrayList<>();
    }
    this.orderConditions.add(orderConditionsItem);
    return this;
  }

   /**
   * Get orderConditions
   * @return orderConditions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderOrderRuleOrderConditionsInner> getOrderConditions() {
    return orderConditions;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderConditions(List<OrderOrderRuleOrderConditionsInner> orderConditions) {
    this.orderConditions = orderConditions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderOrderRule orderOrderRule = (OrderOrderRule) o;
    return Objects.equals(this.routeAfter, orderOrderRule.routeAfter) &&
        Objects.equals(this.routedAt, orderOrderRule.routedAt) &&
        Objects.equals(this.cancelAt, orderOrderRule.cancelAt) &&
        Objects.equals(this.cancelledAt, orderOrderRule.cancelledAt) &&
        Objects.equals(this.orderConditions, orderOrderRule.orderConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeAfter, routedAt, cancelAt, cancelledAt, orderConditions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderOrderRule {\n");
    sb.append("    routeAfter: ").append(toIndentedString(routeAfter)).append("\n");
    sb.append("    routedAt: ").append(toIndentedString(routedAt)).append("\n");
    sb.append("    cancelAt: ").append(toIndentedString(cancelAt)).append("\n");
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    orderConditions: ").append(toIndentedString(orderConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

