/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_ID,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_ACCOUNT_NUMBER,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_TYPE,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_TERMINAL_AT,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_RATIO_PRICE_THRESHOLD,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_RATIO_PRICE_COMPARATOR,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_RATIO_PRICE_IS_THRESHOLD_BASED_ON_NOTIONAL,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_RELATED_ORDERS,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_ORDERS,
  PlacedOrderResponseComplexOrder.JSON_PROPERTY_TRIGGER_ORDER
})
@JsonTypeName("PlacedOrderResponse_complex_order")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:32:41.545126+01:00[Europe/Berlin]")
public class PlacedOrderResponseComplexOrder {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_TERMINAL_AT = "terminal-at";
  private String terminalAt;

  public static final String JSON_PROPERTY_RATIO_PRICE_THRESHOLD = "ratio-price-threshold";
  private Double ratioPriceThreshold;

  public static final String JSON_PROPERTY_RATIO_PRICE_COMPARATOR = "ratio-price-comparator";
  private String ratioPriceComparator;

  public static final String JSON_PROPERTY_RATIO_PRICE_IS_THRESHOLD_BASED_ON_NOTIONAL = "ratio-price-is-threshold-based-on-notional";
  private Boolean ratioPriceIsThresholdBasedOnNotional;

  public static final String JSON_PROPERTY_RELATED_ORDERS = "related-orders";
  private List<PlacedOrderResponseComplexOrderRelatedOrdersInner> relatedOrders;

  public static final String JSON_PROPERTY_ORDERS = "orders";
  private List<PlacedOrderResponseComplexOrderOrdersInner> orders;

  public static final String JSON_PROPERTY_TRIGGER_ORDER = "trigger-order";
  private PlacedOrderResponseComplexOrderTriggerOrder triggerOrder;

  public PlacedOrderResponseComplexOrder() {
  }

  public PlacedOrderResponseComplexOrder id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public PlacedOrderResponseComplexOrder accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public PlacedOrderResponseComplexOrder type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * 
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public PlacedOrderResponseComplexOrder terminalAt(String terminalAt) {
    
    this.terminalAt = terminalAt;
    return this;
  }

   /**
   * 
   * @return terminalAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTerminalAt() {
    return terminalAt;
  }


  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerminalAt(String terminalAt) {
    this.terminalAt = terminalAt;
  }


  public PlacedOrderResponseComplexOrder ratioPriceThreshold(Double ratioPriceThreshold) {
    
    this.ratioPriceThreshold = ratioPriceThreshold;
    return this;
  }

   /**
   * 
   * @return ratioPriceThreshold
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRatioPriceThreshold() {
    return ratioPriceThreshold;
  }


  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRatioPriceThreshold(Double ratioPriceThreshold) {
    this.ratioPriceThreshold = ratioPriceThreshold;
  }


  public PlacedOrderResponseComplexOrder ratioPriceComparator(String ratioPriceComparator) {
    
    this.ratioPriceComparator = ratioPriceComparator;
    return this;
  }

   /**
   * 
   * @return ratioPriceComparator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRatioPriceComparator() {
    return ratioPriceComparator;
  }


  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRatioPriceComparator(String ratioPriceComparator) {
    this.ratioPriceComparator = ratioPriceComparator;
  }


  public PlacedOrderResponseComplexOrder ratioPriceIsThresholdBasedOnNotional(Boolean ratioPriceIsThresholdBasedOnNotional) {
    
    this.ratioPriceIsThresholdBasedOnNotional = ratioPriceIsThresholdBasedOnNotional;
    return this;
  }

   /**
   * 
   * @return ratioPriceIsThresholdBasedOnNotional
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_IS_THRESHOLD_BASED_ON_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRatioPriceIsThresholdBasedOnNotional() {
    return ratioPriceIsThresholdBasedOnNotional;
  }


  @JsonProperty(JSON_PROPERTY_RATIO_PRICE_IS_THRESHOLD_BASED_ON_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRatioPriceIsThresholdBasedOnNotional(Boolean ratioPriceIsThresholdBasedOnNotional) {
    this.ratioPriceIsThresholdBasedOnNotional = ratioPriceIsThresholdBasedOnNotional;
  }


  public PlacedOrderResponseComplexOrder relatedOrders(List<PlacedOrderResponseComplexOrderRelatedOrdersInner> relatedOrders) {
    
    this.relatedOrders = relatedOrders;
    return this;
  }

  public PlacedOrderResponseComplexOrder addRelatedOrdersItem(PlacedOrderResponseComplexOrderRelatedOrdersInner relatedOrdersItem) {
    if (this.relatedOrders == null) {
      this.relatedOrders = new ArrayList<>();
    }
    this.relatedOrders.add(relatedOrdersItem);
    return this;
  }

   /**
   * Get relatedOrders
   * @return relatedOrders
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED_ORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlacedOrderResponseComplexOrderRelatedOrdersInner> getRelatedOrders() {
    return relatedOrders;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_ORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedOrders(List<PlacedOrderResponseComplexOrderRelatedOrdersInner> relatedOrders) {
    this.relatedOrders = relatedOrders;
  }


  public PlacedOrderResponseComplexOrder orders(List<PlacedOrderResponseComplexOrderOrdersInner> orders) {
    
    this.orders = orders;
    return this;
  }

  public PlacedOrderResponseComplexOrder addOrdersItem(PlacedOrderResponseComplexOrderOrdersInner ordersItem) {
    if (this.orders == null) {
      this.orders = new ArrayList<>();
    }
    this.orders.add(ordersItem);
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlacedOrderResponseComplexOrderOrdersInner> getOrders() {
    return orders;
  }


  @JsonProperty(JSON_PROPERTY_ORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrders(List<PlacedOrderResponseComplexOrderOrdersInner> orders) {
    this.orders = orders;
  }


  public PlacedOrderResponseComplexOrder triggerOrder(PlacedOrderResponseComplexOrderTriggerOrder triggerOrder) {
    
    this.triggerOrder = triggerOrder;
    return this;
  }

   /**
   * Get triggerOrder
   * @return triggerOrder
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRIGGER_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlacedOrderResponseComplexOrderTriggerOrder getTriggerOrder() {
    return triggerOrder;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGER_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriggerOrder(PlacedOrderResponseComplexOrderTriggerOrder triggerOrder) {
    this.triggerOrder = triggerOrder;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacedOrderResponseComplexOrder placedOrderResponseComplexOrder = (PlacedOrderResponseComplexOrder) o;
    return Objects.equals(this.id, placedOrderResponseComplexOrder.id) &&
        Objects.equals(this.accountNumber, placedOrderResponseComplexOrder.accountNumber) &&
        Objects.equals(this.type, placedOrderResponseComplexOrder.type) &&
        Objects.equals(this.terminalAt, placedOrderResponseComplexOrder.terminalAt) &&
        Objects.equals(this.ratioPriceThreshold, placedOrderResponseComplexOrder.ratioPriceThreshold) &&
        Objects.equals(this.ratioPriceComparator, placedOrderResponseComplexOrder.ratioPriceComparator) &&
        Objects.equals(this.ratioPriceIsThresholdBasedOnNotional, placedOrderResponseComplexOrder.ratioPriceIsThresholdBasedOnNotional) &&
        Objects.equals(this.relatedOrders, placedOrderResponseComplexOrder.relatedOrders) &&
        Objects.equals(this.orders, placedOrderResponseComplexOrder.orders) &&
        Objects.equals(this.triggerOrder, placedOrderResponseComplexOrder.triggerOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, type, terminalAt, ratioPriceThreshold, ratioPriceComparator, ratioPriceIsThresholdBasedOnNotional, relatedOrders, orders, triggerOrder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacedOrderResponseComplexOrder {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    terminalAt: ").append(toIndentedString(terminalAt)).append("\n");
    sb.append("    ratioPriceThreshold: ").append(toIndentedString(ratioPriceThreshold)).append("\n");
    sb.append("    ratioPriceComparator: ").append(toIndentedString(ratioPriceComparator)).append("\n");
    sb.append("    ratioPriceIsThresholdBasedOnNotional: ").append(toIndentedString(ratioPriceIsThresholdBasedOnNotional)).append("\n");
    sb.append("    relatedOrders: ").append(toIndentedString(relatedOrders)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    triggerOrder: ").append(toIndentedString(triggerOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

