/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PlacedOrderResponse model
 */
@JsonPropertyOrder({
  PlacedOrderResponse.JSON_PROPERTY_ORDER,
  PlacedOrderResponse.JSON_PROPERTY_COMPLEX_ORDER,
  PlacedOrderResponse.JSON_PROPERTY_WARNINGS,
  PlacedOrderResponse.JSON_PROPERTY_ERRORS,
  PlacedOrderResponse.JSON_PROPERTY_BUYING_POWER_EFFECT,
  PlacedOrderResponse.JSON_PROPERTY_FEE_CALCULATION
})
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PlacedOrderResponse {
  public static final String JSON_PROPERTY_ORDER = "order";
  private PlacedOrderResponseOrder order;

  public static final String JSON_PROPERTY_COMPLEX_ORDER = "complex-order";
  private PlacedOrderResponseComplexOrder complexOrder;

  public static final String JSON_PROPERTY_WARNINGS = "warnings";
  private List<PlacedOrderResponseWarningsInner> warnings;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  private List<PlacedOrderResponseWarningsInner> errors;

  public static final String JSON_PROPERTY_BUYING_POWER_EFFECT = "buying-power-effect";
  private BuyingPowerEffect buyingPowerEffect;

  public static final String JSON_PROPERTY_FEE_CALCULATION = "fee-calculation";
  private FeeCalculation feeCalculation;

  public PlacedOrderResponse() {
  }

  public PlacedOrderResponse order(PlacedOrderResponseOrder order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlacedOrderResponseOrder getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(PlacedOrderResponseOrder order) {
    this.order = order;
  }


  public PlacedOrderResponse complexOrder(PlacedOrderResponseComplexOrder complexOrder) {
    
    this.complexOrder = complexOrder;
    return this;
  }

   /**
   * Get complexOrder
   * @return complexOrder
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlacedOrderResponseComplexOrder getComplexOrder() {
    return complexOrder;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrder(PlacedOrderResponseComplexOrder complexOrder) {
    this.complexOrder = complexOrder;
  }


  public PlacedOrderResponse warnings(List<PlacedOrderResponseWarningsInner> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public PlacedOrderResponse addWarningsItem(PlacedOrderResponseWarningsInner warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * Get warnings
   * @return warnings
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlacedOrderResponseWarningsInner> getWarnings() {
    return warnings;
  }


  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnings(List<PlacedOrderResponseWarningsInner> warnings) {
    this.warnings = warnings;
  }


  public PlacedOrderResponse errors(List<PlacedOrderResponseWarningsInner> errors) {
    
    this.errors = errors;
    return this;
  }

  public PlacedOrderResponse addErrorsItem(PlacedOrderResponseWarningsInner errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PlacedOrderResponseWarningsInner> getErrors() {
    return errors;
  }


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(List<PlacedOrderResponseWarningsInner> errors) {
    this.errors = errors;
  }


  public PlacedOrderResponse buyingPowerEffect(BuyingPowerEffect buyingPowerEffect) {
    
    this.buyingPowerEffect = buyingPowerEffect;
    return this;
  }

   /**
   * 
   * @return buyingPowerEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUYING_POWER_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BuyingPowerEffect getBuyingPowerEffect() {
    return buyingPowerEffect;
  }


  @JsonProperty(JSON_PROPERTY_BUYING_POWER_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyingPowerEffect(BuyingPowerEffect buyingPowerEffect) {
    this.buyingPowerEffect = buyingPowerEffect;
  }


  public PlacedOrderResponse feeCalculation(FeeCalculation feeCalculation) {
    
    this.feeCalculation = feeCalculation;
    return this;
  }

   /**
   * 
   * @return feeCalculation
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEE_CALCULATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FeeCalculation getFeeCalculation() {
    return feeCalculation;
  }


  @JsonProperty(JSON_PROPERTY_FEE_CALCULATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeeCalculation(FeeCalculation feeCalculation) {
    this.feeCalculation = feeCalculation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacedOrderResponse placedOrderResponse = (PlacedOrderResponse) o;
    return Objects.equals(this.order, placedOrderResponse.order) &&
        Objects.equals(this.complexOrder, placedOrderResponse.complexOrder) &&
        Objects.equals(this.warnings, placedOrderResponse.warnings) &&
        Objects.equals(this.errors, placedOrderResponse.errors) &&
        Objects.equals(this.buyingPowerEffect, placedOrderResponse.buyingPowerEffect) &&
        Objects.equals(this.feeCalculation, placedOrderResponse.feeCalculation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, complexOrder, warnings, errors, buyingPowerEffect, feeCalculation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacedOrderResponse {\n");
    if (order != null)
        sb.append("    order: ").append(toIndentedString(order)).append("\n");
    if (complexOrder != null)
        sb.append("    complexOrder: ").append(toIndentedString(complexOrder)).append("\n");
    if (warnings != null)
        sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    if (errors != null)
        sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    if (buyingPowerEffect != null)
        sb.append("    buyingPowerEffect: ").append(toIndentedString(buyingPowerEffect)).append("\n");
    if (feeCalculation != null)
        sb.append("    feeCalculation: ").append(toIndentedString(feeCalculation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

