/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  PlacedOrderResponseWarningsInner.JSON_PROPERTY_CODE,
  PlacedOrderResponseWarningsInner.JSON_PROPERTY_MESSAGE,
  PlacedOrderResponseWarningsInner.JSON_PROPERTY_PREFLIGHT_ID
})
@JsonTypeName("PlacedOrderResponse_warnings_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PlacedOrderResponseWarningsInner {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public PlacedOrderResponseWarningsInner() {
  }

  public PlacedOrderResponseWarningsInner code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 
   * @return code
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public PlacedOrderResponseWarningsInner message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * 
   * @return message
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public PlacedOrderResponseWarningsInner preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * 
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacedOrderResponseWarningsInner placedOrderResponseWarningsInner = (PlacedOrderResponseWarningsInner) o;
    return Objects.equals(this.code, placedOrderResponseWarningsInner.code) &&
        Objects.equals(this.message, placedOrderResponseWarningsInner.message) &&
        Objects.equals(this.preflightId, placedOrderResponseWarningsInner.preflightId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, preflightId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacedOrderResponseWarningsInner {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

