/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * 
 */
@JsonPropertyOrder({
  PlacedOrderResponseOrder.JSON_PROPERTY_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_ACCOUNT_NUMBER,
  PlacedOrderResponseOrder.JSON_PROPERTY_TIME_IN_FORCE,
  PlacedOrderResponseOrder.JSON_PROPERTY_GTC_DATE,
  PlacedOrderResponseOrder.JSON_PROPERTY_ORDER_TYPE,
  PlacedOrderResponseOrder.JSON_PROPERTY_SIZE,
  PlacedOrderResponseOrder.JSON_PROPERTY_UNDERLYING_SYMBOL,
  PlacedOrderResponseOrder.JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE,
  PlacedOrderResponseOrder.JSON_PROPERTY_PRICE,
  PlacedOrderResponseOrder.JSON_PROPERTY_PRICE_EFFECT,
  PlacedOrderResponseOrder.JSON_PROPERTY_VALUE,
  PlacedOrderResponseOrder.JSON_PROPERTY_VALUE_EFFECT,
  PlacedOrderResponseOrder.JSON_PROPERTY_STOP_TRIGGER,
  PlacedOrderResponseOrder.JSON_PROPERTY_STATUS,
  PlacedOrderResponseOrder.JSON_PROPERTY_CONTINGENT_STATUS,
  PlacedOrderResponseOrder.JSON_PROPERTY_CONFIRMATION_STATUS,
  PlacedOrderResponseOrder.JSON_PROPERTY_CANCELLABLE,
  PlacedOrderResponseOrder.JSON_PROPERTY_CANCELLED_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_CANCEL_USER_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_CANCEL_USERNAME,
  PlacedOrderResponseOrder.JSON_PROPERTY_EDITABLE,
  PlacedOrderResponseOrder.JSON_PROPERTY_EDITED,
  PlacedOrderResponseOrder.JSON_PROPERTY_REPLACING_ORDER_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_REPLACES_ORDER_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_RECEIVED_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_UPDATED_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_IN_FLIGHT_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_LIVE_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_REJECT_REASON,
  PlacedOrderResponseOrder.JSON_PROPERTY_USER_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_USERNAME,
  PlacedOrderResponseOrder.JSON_PROPERTY_TERMINAL_AT,
  PlacedOrderResponseOrder.JSON_PROPERTY_COMPLEX_ORDER_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_COMPLEX_ORDER_TAG,
  PlacedOrderResponseOrder.JSON_PROPERTY_PREFLIGHT_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_GLOBAL_REQUEST_ID,
  PlacedOrderResponseOrder.JSON_PROPERTY_LEGS,
  PlacedOrderResponseOrder.JSON_PROPERTY_ORDER_RULE
})
@JsonTypeName("PlacedOrderResponse_order")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PlacedOrderResponseOrder {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_TIME_IN_FORCE = "time-in-force";
  private String timeInForce;

  public static final String JSON_PROPERTY_GTC_DATE = "gtc-date";
  private LocalDate gtcDate;

  public static final String JSON_PROPERTY_ORDER_TYPE = "order-type";
  private String orderType;

  public static final String JSON_PROPERTY_SIZE = "size";
  private String size;

  public static final String JSON_PROPERTY_UNDERLYING_SYMBOL = "underlying-symbol";
  private String underlyingSymbol;

  public static final String JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE = "underlying-instrument-type";
  private String underlyingInstrumentType;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_PRICE_EFFECT = "price-effect";
  private String priceEffect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private String valueEffect;

  public static final String JSON_PROPERTY_STOP_TRIGGER = "stop-trigger";
  private String stopTrigger;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CONTINGENT_STATUS = "contingent-status";
  private String contingentStatus;

  public static final String JSON_PROPERTY_CONFIRMATION_STATUS = "confirmation-status";
  private String confirmationStatus;

  public static final String JSON_PROPERTY_CANCELLABLE = "cancellable";
  private Boolean cancellable;

  public static final String JSON_PROPERTY_CANCELLED_AT = "cancelled-at";
  private OffsetDateTime cancelledAt;

  public static final String JSON_PROPERTY_CANCEL_USER_ID = "cancel-user-id";
  private String cancelUserId;

  public static final String JSON_PROPERTY_CANCEL_USERNAME = "cancel-username";
  private String cancelUsername;

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  private Boolean editable;

  public static final String JSON_PROPERTY_EDITED = "edited";
  private Boolean edited;

  public static final String JSON_PROPERTY_REPLACING_ORDER_ID = "replacing-order-id";
  private String replacingOrderId;

  public static final String JSON_PROPERTY_REPLACES_ORDER_ID = "replaces-order-id";
  private String replacesOrderId;

  public static final String JSON_PROPERTY_RECEIVED_AT = "received-at";
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated-at";
  private String updatedAt;

  public static final String JSON_PROPERTY_IN_FLIGHT_AT = "in-flight-at";
  private OffsetDateTime inFlightAt;

  public static final String JSON_PROPERTY_LIVE_AT = "live-at";
  private OffsetDateTime liveAt;

  public static final String JSON_PROPERTY_REJECT_REASON = "reject-reason";
  private String rejectReason;

  public static final String JSON_PROPERTY_USER_ID = "user-id";
  private String userId;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_TERMINAL_AT = "terminal-at";
  private OffsetDateTime terminalAt;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_ID = "complex-order-id";
  private String complexOrderId;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_TAG = "complex-order-tag";
  private String complexOrderTag;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public static final String JSON_PROPERTY_GLOBAL_REQUEST_ID = "global-request-id";
  private String globalRequestId;

  public static final String JSON_PROPERTY_LEGS = "legs";
  private List<OrderLegsInner> legs;

  public static final String JSON_PROPERTY_ORDER_RULE = "order-rule";
  private OrderOrderRule orderRule;

  public PlacedOrderResponseOrder() {
  }

  public PlacedOrderResponseOrder id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public PlacedOrderResponseOrder accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public PlacedOrderResponseOrder timeInForce(String timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * 
   * @return timeInForce
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }


  public PlacedOrderResponseOrder gtcDate(LocalDate gtcDate) {
    
    this.gtcDate = gtcDate;
    return this;
  }

   /**
   * 
   * @return gtcDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getGtcDate() {
    return gtcDate;
  }


  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGtcDate(LocalDate gtcDate) {
    this.gtcDate = gtcDate;
  }


  public PlacedOrderResponseOrder orderType(String orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * 
   * @return orderType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }


  public PlacedOrderResponseOrder size(String size) {
    
    this.size = size;
    return this;
  }

   /**
   * 
   * @return size
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(String size) {
    this.size = size;
  }


  public PlacedOrderResponseOrder underlyingSymbol(String underlyingSymbol) {
    
    this.underlyingSymbol = underlyingSymbol;
    return this;
  }

   /**
   * 
   * @return underlyingSymbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }


  public PlacedOrderResponseOrder underlyingInstrumentType(String underlyingInstrumentType) {
    
    this.underlyingInstrumentType = underlyingInstrumentType;
    return this;
  }

   /**
   * 
   * @return underlyingInstrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingInstrumentType() {
    return underlyingInstrumentType;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingInstrumentType(String underlyingInstrumentType) {
    this.underlyingInstrumentType = underlyingInstrumentType;
  }


  public PlacedOrderResponseOrder price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * 
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public PlacedOrderResponseOrder priceEffect(String priceEffect) {
    
    this.priceEffect = priceEffect;
    return this;
  }

   /**
   * 
   * @return priceEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPriceEffect() {
    return priceEffect;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceEffect(String priceEffect) {
    this.priceEffect = priceEffect;
  }


  public PlacedOrderResponseOrder value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public PlacedOrderResponseOrder valueEffect(String valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * 
   * @return valueEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueEffect(String valueEffect) {
    this.valueEffect = valueEffect;
  }


  public PlacedOrderResponseOrder stopTrigger(String stopTrigger) {
    
    this.stopTrigger = stopTrigger;
    return this;
  }

   /**
   * 
   * @return stopTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStopTrigger() {
    return stopTrigger;
  }


  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopTrigger(String stopTrigger) {
    this.stopTrigger = stopTrigger;
  }


  public PlacedOrderResponseOrder status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public PlacedOrderResponseOrder contingentStatus(String contingentStatus) {
    
    this.contingentStatus = contingentStatus;
    return this;
  }

   /**
   * 
   * @return contingentStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingentStatus() {
    return contingentStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingentStatus(String contingentStatus) {
    this.contingentStatus = contingentStatus;
  }


  public PlacedOrderResponseOrder confirmationStatus(String confirmationStatus) {
    
    this.confirmationStatus = confirmationStatus;
    return this;
  }

   /**
   * 
   * @return confirmationStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmationStatus() {
    return confirmationStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfirmationStatus(String confirmationStatus) {
    this.confirmationStatus = confirmationStatus;
  }


  public PlacedOrderResponseOrder cancellable(Boolean cancellable) {
    
    this.cancellable = cancellable;
    return this;
  }

   /**
   * 
   * @return cancellable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancellable() {
    return cancellable;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancellable(Boolean cancellable) {
    this.cancellable = cancellable;
  }


  public PlacedOrderResponseOrder cancelledAt(OffsetDateTime cancelledAt) {
    
    this.cancelledAt = cancelledAt;
    return this;
  }

   /**
   * 
   * @return cancelledAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public PlacedOrderResponseOrder cancelUserId(String cancelUserId) {
    
    this.cancelUserId = cancelUserId;
    return this;
  }

   /**
   * 
   * @return cancelUserId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUserId() {
    return cancelUserId;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUserId(String cancelUserId) {
    this.cancelUserId = cancelUserId;
  }


  public PlacedOrderResponseOrder cancelUsername(String cancelUsername) {
    
    this.cancelUsername = cancelUsername;
    return this;
  }

   /**
   * 
   * @return cancelUsername
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUsername() {
    return cancelUsername;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUsername(String cancelUsername) {
    this.cancelUsername = cancelUsername;
  }


  public PlacedOrderResponseOrder editable(Boolean editable) {
    
    this.editable = editable;
    return this;
  }

   /**
   * 
   * @return editable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditable(Boolean editable) {
    this.editable = editable;
  }


  public PlacedOrderResponseOrder edited(Boolean edited) {
    
    this.edited = edited;
    return this;
  }

   /**
   * 
   * @return edited
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEdited() {
    return edited;
  }


  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEdited(Boolean edited) {
    this.edited = edited;
  }


  public PlacedOrderResponseOrder replacingOrderId(String replacingOrderId) {
    
    this.replacingOrderId = replacingOrderId;
    return this;
  }

   /**
   * 
   * @return replacingOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacingOrderId() {
    return replacingOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacingOrderId(String replacingOrderId) {
    this.replacingOrderId = replacingOrderId;
  }


  public PlacedOrderResponseOrder replacesOrderId(String replacesOrderId) {
    
    this.replacesOrderId = replacesOrderId;
    return this;
  }

   /**
   * 
   * @return replacesOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacesOrderId() {
    return replacesOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacesOrderId(String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
  }


  public PlacedOrderResponseOrder receivedAt(OffsetDateTime receivedAt) {
    
    this.receivedAt = receivedAt;
    return this;
  }

   /**
   * 
   * @return receivedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedAt(OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public PlacedOrderResponseOrder updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PlacedOrderResponseOrder inFlightAt(OffsetDateTime inFlightAt) {
    
    this.inFlightAt = inFlightAt;
    return this;
  }

   /**
   * 
   * @return inFlightAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getInFlightAt() {
    return inFlightAt;
  }


  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInFlightAt(OffsetDateTime inFlightAt) {
    this.inFlightAt = inFlightAt;
  }


  public PlacedOrderResponseOrder liveAt(OffsetDateTime liveAt) {
    
    this.liveAt = liveAt;
    return this;
  }

   /**
   * 
   * @return liveAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLiveAt() {
    return liveAt;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveAt(OffsetDateTime liveAt) {
    this.liveAt = liveAt;
  }


  public PlacedOrderResponseOrder rejectReason(String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

   /**
   * 
   * @return rejectReason
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
  }


  public PlacedOrderResponseOrder userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 
   * @return userId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  public PlacedOrderResponseOrder username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * 
   * @return username
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public PlacedOrderResponseOrder terminalAt(OffsetDateTime terminalAt) {
    
    this.terminalAt = terminalAt;
    return this;
  }

   /**
   * 
   * @return terminalAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTerminalAt() {
    return terminalAt;
  }


  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerminalAt(OffsetDateTime terminalAt) {
    this.terminalAt = terminalAt;
  }


  public PlacedOrderResponseOrder complexOrderId(String complexOrderId) {
    
    this.complexOrderId = complexOrderId;
    return this;
  }

   /**
   * 
   * @return complexOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderId() {
    return complexOrderId;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderId(String complexOrderId) {
    this.complexOrderId = complexOrderId;
  }


  public PlacedOrderResponseOrder complexOrderTag(String complexOrderTag) {
    
    this.complexOrderTag = complexOrderTag;
    return this;
  }

   /**
   * 
   * @return complexOrderTag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderTag() {
    return complexOrderTag;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderTag(String complexOrderTag) {
    this.complexOrderTag = complexOrderTag;
  }


  public PlacedOrderResponseOrder preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * 
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }


  public PlacedOrderResponseOrder globalRequestId(String globalRequestId) {
    
    this.globalRequestId = globalRequestId;
    return this;
  }

   /**
   * 
   * @return globalRequestId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGlobalRequestId() {
    return globalRequestId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobalRequestId(String globalRequestId) {
    this.globalRequestId = globalRequestId;
  }


  public PlacedOrderResponseOrder legs(List<OrderLegsInner> legs) {
    
    this.legs = legs;
    return this;
  }

  public PlacedOrderResponseOrder addLegsItem(OrderLegsInner legsItem) {
    if (this.legs == null) {
      this.legs = new ArrayList<>();
    }
    this.legs.add(legsItem);
    return this;
  }

   /**
   * Get legs
   * @return legs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderLegsInner> getLegs() {
    return legs;
  }


  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegs(List<OrderLegsInner> legs) {
    this.legs = legs;
  }


  public PlacedOrderResponseOrder orderRule(OrderOrderRule orderRule) {
    
    this.orderRule = orderRule;
    return this;
  }

   /**
   * Get orderRule
   * @return orderRule
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderOrderRule getOrderRule() {
    return orderRule;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderRule(OrderOrderRule orderRule) {
    this.orderRule = orderRule;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacedOrderResponseOrder placedOrderResponseOrder = (PlacedOrderResponseOrder) o;
    return Objects.equals(this.id, placedOrderResponseOrder.id) &&
        Objects.equals(this.accountNumber, placedOrderResponseOrder.accountNumber) &&
        Objects.equals(this.timeInForce, placedOrderResponseOrder.timeInForce) &&
        Objects.equals(this.gtcDate, placedOrderResponseOrder.gtcDate) &&
        Objects.equals(this.orderType, placedOrderResponseOrder.orderType) &&
        Objects.equals(this.size, placedOrderResponseOrder.size) &&
        Objects.equals(this.underlyingSymbol, placedOrderResponseOrder.underlyingSymbol) &&
        Objects.equals(this.underlyingInstrumentType, placedOrderResponseOrder.underlyingInstrumentType) &&
        Objects.equals(this.price, placedOrderResponseOrder.price) &&
        Objects.equals(this.priceEffect, placedOrderResponseOrder.priceEffect) &&
        Objects.equals(this.value, placedOrderResponseOrder.value) &&
        Objects.equals(this.valueEffect, placedOrderResponseOrder.valueEffect) &&
        Objects.equals(this.stopTrigger, placedOrderResponseOrder.stopTrigger) &&
        Objects.equals(this.status, placedOrderResponseOrder.status) &&
        Objects.equals(this.contingentStatus, placedOrderResponseOrder.contingentStatus) &&
        Objects.equals(this.confirmationStatus, placedOrderResponseOrder.confirmationStatus) &&
        Objects.equals(this.cancellable, placedOrderResponseOrder.cancellable) &&
        Objects.equals(this.cancelledAt, placedOrderResponseOrder.cancelledAt) &&
        Objects.equals(this.cancelUserId, placedOrderResponseOrder.cancelUserId) &&
        Objects.equals(this.cancelUsername, placedOrderResponseOrder.cancelUsername) &&
        Objects.equals(this.editable, placedOrderResponseOrder.editable) &&
        Objects.equals(this.edited, placedOrderResponseOrder.edited) &&
        Objects.equals(this.replacingOrderId, placedOrderResponseOrder.replacingOrderId) &&
        Objects.equals(this.replacesOrderId, placedOrderResponseOrder.replacesOrderId) &&
        Objects.equals(this.receivedAt, placedOrderResponseOrder.receivedAt) &&
        Objects.equals(this.updatedAt, placedOrderResponseOrder.updatedAt) &&
        Objects.equals(this.inFlightAt, placedOrderResponseOrder.inFlightAt) &&
        Objects.equals(this.liveAt, placedOrderResponseOrder.liveAt) &&
        Objects.equals(this.rejectReason, placedOrderResponseOrder.rejectReason) &&
        Objects.equals(this.userId, placedOrderResponseOrder.userId) &&
        Objects.equals(this.username, placedOrderResponseOrder.username) &&
        Objects.equals(this.terminalAt, placedOrderResponseOrder.terminalAt) &&
        Objects.equals(this.complexOrderId, placedOrderResponseOrder.complexOrderId) &&
        Objects.equals(this.complexOrderTag, placedOrderResponseOrder.complexOrderTag) &&
        Objects.equals(this.preflightId, placedOrderResponseOrder.preflightId) &&
        Objects.equals(this.globalRequestId, placedOrderResponseOrder.globalRequestId) &&
        Objects.equals(this.legs, placedOrderResponseOrder.legs) &&
        Objects.equals(this.orderRule, placedOrderResponseOrder.orderRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, timeInForce, gtcDate, orderType, size, underlyingSymbol, underlyingInstrumentType, price, priceEffect, value, valueEffect, stopTrigger, status, contingentStatus, confirmationStatus, cancellable, cancelledAt, cancelUserId, cancelUsername, editable, edited, replacingOrderId, replacesOrderId, receivedAt, updatedAt, inFlightAt, liveAt, rejectReason, userId, username, terminalAt, complexOrderId, complexOrderTag, preflightId, globalRequestId, legs, orderRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacedOrderResponseOrder {\n");
    if (id != null)
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (accountNumber != null)
        sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    if (timeInForce != null)
        sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    if (gtcDate != null)
        sb.append("    gtcDate: ").append(toIndentedString(gtcDate)).append("\n");
    if (orderType != null)
        sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    if (size != null)
        sb.append("    size: ").append(toIndentedString(size)).append("\n");
    if (underlyingSymbol != null)
        sb.append("    underlyingSymbol: ").append(toIndentedString(underlyingSymbol)).append("\n");
    if (underlyingInstrumentType != null)
        sb.append("    underlyingInstrumentType: ").append(toIndentedString(underlyingInstrumentType)).append("\n");
    if (price != null)
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
    if (priceEffect != null)
        sb.append("    priceEffect: ").append(toIndentedString(priceEffect)).append("\n");
    if (value != null)
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
    if (valueEffect != null)
        sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    if (stopTrigger != null)
        sb.append("    stopTrigger: ").append(toIndentedString(stopTrigger)).append("\n");
    if (status != null)
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
    if (contingentStatus != null)
        sb.append("    contingentStatus: ").append(toIndentedString(contingentStatus)).append("\n");
    if (confirmationStatus != null)
        sb.append("    confirmationStatus: ").append(toIndentedString(confirmationStatus)).append("\n");
    if (cancellable != null)
        sb.append("    cancellable: ").append(toIndentedString(cancellable)).append("\n");
    if (cancelledAt != null)
        sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    if (cancelUserId != null)
        sb.append("    cancelUserId: ").append(toIndentedString(cancelUserId)).append("\n");
    if (cancelUsername != null)
        sb.append("    cancelUsername: ").append(toIndentedString(cancelUsername)).append("\n");
    if (editable != null)
        sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    if (edited != null)
        sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    if (replacingOrderId != null)
        sb.append("    replacingOrderId: ").append(toIndentedString(replacingOrderId)).append("\n");
    if (replacesOrderId != null)
        sb.append("    replacesOrderId: ").append(toIndentedString(replacesOrderId)).append("\n");
    if (receivedAt != null)
        sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    if (updatedAt != null)
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    if (inFlightAt != null)
        sb.append("    inFlightAt: ").append(toIndentedString(inFlightAt)).append("\n");
    if (liveAt != null)
        sb.append("    liveAt: ").append(toIndentedString(liveAt)).append("\n");
    if (rejectReason != null)
        sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    if (userId != null)
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    if (username != null)
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
    if (terminalAt != null)
        sb.append("    terminalAt: ").append(toIndentedString(terminalAt)).append("\n");
    if (complexOrderId != null)
        sb.append("    complexOrderId: ").append(toIndentedString(complexOrderId)).append("\n");
    if (complexOrderTag != null)
        sb.append("    complexOrderTag: ").append(toIndentedString(complexOrderTag)).append("\n");
    if (preflightId != null)
        sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    if (globalRequestId != null)
        sb.append("    globalRequestId: ").append(toIndentedString(globalRequestId)).append("\n");
    if (legs != null)
        sb.append("    legs: ").append(toIndentedString(legs)).append("\n");
    if (orderRule != null)
        sb.append("    orderRule: ").append(toIndentedString(orderRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

