/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Order with complex-order-tag: &#39;&lt;type&gt;::trigger-order&#39;. For example, &#39;OTO::trigger-order for OTO complex orders.
 */
@JsonPropertyOrder({
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_ACCOUNT_NUMBER,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_TIME_IN_FORCE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_GTC_DATE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_ORDER_TYPE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_SIZE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_UNDERLYING_SYMBOL,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_PRICE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_PRICE_EFFECT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_VALUE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_VALUE_EFFECT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_STOP_TRIGGER,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_STATUS,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CONTINGENT_STATUS,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CONFIRMATION_STATUS,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CANCELLABLE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CANCELLED_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CANCEL_USER_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_CANCEL_USERNAME,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_EDITABLE,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_EDITED,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_REPLACING_ORDER_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_REPLACES_ORDER_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_RECEIVED_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_UPDATED_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_IN_FLIGHT_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_LIVE_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_REJECT_REASON,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_USER_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_USERNAME,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_TERMINAL_AT,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_COMPLEX_ORDER_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_COMPLEX_ORDER_TAG,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_PREFLIGHT_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_GLOBAL_REQUEST_ID,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_LEGS,
  PlacedOrderResponseComplexOrderTriggerOrder.JSON_PROPERTY_ORDER_RULE
})
@JsonTypeName("PlacedOrderResponse_complex_order_trigger_order")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:32:41.545126+01:00[Europe/Berlin]")
public class PlacedOrderResponseComplexOrderTriggerOrder {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account-number";
  private String accountNumber;

  public static final String JSON_PROPERTY_TIME_IN_FORCE = "time-in-force";
  private String timeInForce;

  public static final String JSON_PROPERTY_GTC_DATE = "gtc-date";
  private LocalDate gtcDate;

  public static final String JSON_PROPERTY_ORDER_TYPE = "order-type";
  private String orderType;

  public static final String JSON_PROPERTY_SIZE = "size";
  private String size;

  public static final String JSON_PROPERTY_UNDERLYING_SYMBOL = "underlying-symbol";
  private String underlyingSymbol;

  public static final String JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE = "underlying-instrument-type";
  private String underlyingInstrumentType;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_PRICE_EFFECT = "price-effect";
  private String priceEffect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private String valueEffect;

  public static final String JSON_PROPERTY_STOP_TRIGGER = "stop-trigger";
  private String stopTrigger;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CONTINGENT_STATUS = "contingent-status";
  private String contingentStatus;

  public static final String JSON_PROPERTY_CONFIRMATION_STATUS = "confirmation-status";
  private String confirmationStatus;

  public static final String JSON_PROPERTY_CANCELLABLE = "cancellable";
  private Boolean cancellable;

  public static final String JSON_PROPERTY_CANCELLED_AT = "cancelled-at";
  private OffsetDateTime cancelledAt;

  public static final String JSON_PROPERTY_CANCEL_USER_ID = "cancel-user-id";
  private String cancelUserId;

  public static final String JSON_PROPERTY_CANCEL_USERNAME = "cancel-username";
  private String cancelUsername;

  public static final String JSON_PROPERTY_EDITABLE = "editable";
  private Boolean editable;

  public static final String JSON_PROPERTY_EDITED = "edited";
  private Boolean edited;

  public static final String JSON_PROPERTY_REPLACING_ORDER_ID = "replacing-order-id";
  private String replacingOrderId;

  public static final String JSON_PROPERTY_REPLACES_ORDER_ID = "replaces-order-id";
  private String replacesOrderId;

  public static final String JSON_PROPERTY_RECEIVED_AT = "received-at";
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated-at";
  private String updatedAt;

  public static final String JSON_PROPERTY_IN_FLIGHT_AT = "in-flight-at";
  private OffsetDateTime inFlightAt;

  public static final String JSON_PROPERTY_LIVE_AT = "live-at";
  private OffsetDateTime liveAt;

  public static final String JSON_PROPERTY_REJECT_REASON = "reject-reason";
  private String rejectReason;

  public static final String JSON_PROPERTY_USER_ID = "user-id";
  private String userId;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_TERMINAL_AT = "terminal-at";
  private OffsetDateTime terminalAt;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_ID = "complex-order-id";
  private String complexOrderId;

  public static final String JSON_PROPERTY_COMPLEX_ORDER_TAG = "complex-order-tag";
  private String complexOrderTag;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public static final String JSON_PROPERTY_GLOBAL_REQUEST_ID = "global-request-id";
  private String globalRequestId;

  public static final String JSON_PROPERTY_LEGS = "legs";
  private List<OrderLegsInner> legs;

  public static final String JSON_PROPERTY_ORDER_RULE = "order-rule";
  private OrderOrderRule orderRule;

  public PlacedOrderResponseComplexOrderTriggerOrder() {
  }

  public PlacedOrderResponseComplexOrderTriggerOrder id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder accountNumber(String accountNumber) {
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder timeInForce(String timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * 
   * @return timeInForce
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder gtcDate(LocalDate gtcDate) {
    
    this.gtcDate = gtcDate;
    return this;
  }

   /**
   * 
   * @return gtcDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getGtcDate() {
    return gtcDate;
  }


  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGtcDate(LocalDate gtcDate) {
    this.gtcDate = gtcDate;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder orderType(String orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * 
   * @return orderType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder size(String size) {
    
    this.size = size;
    return this;
  }

   /**
   * 
   * @return size
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(String size) {
    this.size = size;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder underlyingSymbol(String underlyingSymbol) {
    
    this.underlyingSymbol = underlyingSymbol;
    return this;
  }

   /**
   * 
   * @return underlyingSymbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder underlyingInstrumentType(String underlyingInstrumentType) {
    
    this.underlyingInstrumentType = underlyingInstrumentType;
    return this;
  }

   /**
   * 
   * @return underlyingInstrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnderlyingInstrumentType() {
    return underlyingInstrumentType;
  }


  @JsonProperty(JSON_PROPERTY_UNDERLYING_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnderlyingInstrumentType(String underlyingInstrumentType) {
    this.underlyingInstrumentType = underlyingInstrumentType;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * 
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder priceEffect(String priceEffect) {
    
    this.priceEffect = priceEffect;
    return this;
  }

   /**
   * 
   * @return priceEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPriceEffect() {
    return priceEffect;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceEffect(String priceEffect) {
    this.priceEffect = priceEffect;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder valueEffect(String valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * 
   * @return valueEffect
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueEffect(String valueEffect) {
    this.valueEffect = valueEffect;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder stopTrigger(String stopTrigger) {
    
    this.stopTrigger = stopTrigger;
    return this;
  }

   /**
   * 
   * @return stopTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStopTrigger() {
    return stopTrigger;
  }


  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopTrigger(String stopTrigger) {
    this.stopTrigger = stopTrigger;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder contingentStatus(String contingentStatus) {
    
    this.contingentStatus = contingentStatus;
    return this;
  }

   /**
   * 
   * @return contingentStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingentStatus() {
    return contingentStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingentStatus(String contingentStatus) {
    this.contingentStatus = contingentStatus;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder confirmationStatus(String confirmationStatus) {
    
    this.confirmationStatus = confirmationStatus;
    return this;
  }

   /**
   * 
   * @return confirmationStatus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmationStatus() {
    return confirmationStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONFIRMATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfirmationStatus(String confirmationStatus) {
    this.confirmationStatus = confirmationStatus;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder cancellable(Boolean cancellable) {
    
    this.cancellable = cancellable;
    return this;
  }

   /**
   * 
   * @return cancellable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCancellable() {
    return cancellable;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancellable(Boolean cancellable) {
    this.cancellable = cancellable;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder cancelledAt(OffsetDateTime cancelledAt) {
    
    this.cancelledAt = cancelledAt;
    return this;
  }

   /**
   * 
   * @return cancelledAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder cancelUserId(String cancelUserId) {
    
    this.cancelUserId = cancelUserId;
    return this;
  }

   /**
   * 
   * @return cancelUserId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUserId() {
    return cancelUserId;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUserId(String cancelUserId) {
    this.cancelUserId = cancelUserId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder cancelUsername(String cancelUsername) {
    
    this.cancelUsername = cancelUsername;
    return this;
  }

   /**
   * 
   * @return cancelUsername
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCancelUsername() {
    return cancelUsername;
  }


  @JsonProperty(JSON_PROPERTY_CANCEL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelUsername(String cancelUsername) {
    this.cancelUsername = cancelUsername;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder editable(Boolean editable) {
    
    this.editable = editable;
    return this;
  }

   /**
   * 
   * @return editable
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditable() {
    return editable;
  }


  @JsonProperty(JSON_PROPERTY_EDITABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditable(Boolean editable) {
    this.editable = editable;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder edited(Boolean edited) {
    
    this.edited = edited;
    return this;
  }

   /**
   * 
   * @return edited
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEdited() {
    return edited;
  }


  @JsonProperty(JSON_PROPERTY_EDITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEdited(Boolean edited) {
    this.edited = edited;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder replacingOrderId(String replacingOrderId) {
    
    this.replacingOrderId = replacingOrderId;
    return this;
  }

   /**
   * 
   * @return replacingOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacingOrderId() {
    return replacingOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACING_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacingOrderId(String replacingOrderId) {
    this.replacingOrderId = replacingOrderId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder replacesOrderId(String replacesOrderId) {
    
    this.replacesOrderId = replacesOrderId;
    return this;
  }

   /**
   * 
   * @return replacesOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReplacesOrderId() {
    return replacesOrderId;
  }


  @JsonProperty(JSON_PROPERTY_REPLACES_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplacesOrderId(String replacesOrderId) {
    this.replacesOrderId = replacesOrderId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder receivedAt(OffsetDateTime receivedAt) {
    
    this.receivedAt = receivedAt;
    return this;
  }

   /**
   * 
   * @return receivedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedAt(OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * 
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder inFlightAt(OffsetDateTime inFlightAt) {
    
    this.inFlightAt = inFlightAt;
    return this;
  }

   /**
   * 
   * @return inFlightAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getInFlightAt() {
    return inFlightAt;
  }


  @JsonProperty(JSON_PROPERTY_IN_FLIGHT_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInFlightAt(OffsetDateTime inFlightAt) {
    this.inFlightAt = inFlightAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder liveAt(OffsetDateTime liveAt) {
    
    this.liveAt = liveAt;
    return this;
  }

   /**
   * 
   * @return liveAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLiveAt() {
    return liveAt;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveAt(OffsetDateTime liveAt) {
    this.liveAt = liveAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder rejectReason(String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

   /**
   * 
   * @return rejectReason
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 
   * @return userId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * 
   * @return username
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder terminalAt(OffsetDateTime terminalAt) {
    
    this.terminalAt = terminalAt;
    return this;
  }

   /**
   * 
   * @return terminalAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTerminalAt() {
    return terminalAt;
  }


  @JsonProperty(JSON_PROPERTY_TERMINAL_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerminalAt(OffsetDateTime terminalAt) {
    this.terminalAt = terminalAt;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder complexOrderId(String complexOrderId) {
    
    this.complexOrderId = complexOrderId;
    return this;
  }

   /**
   * 
   * @return complexOrderId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderId() {
    return complexOrderId;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderId(String complexOrderId) {
    this.complexOrderId = complexOrderId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder complexOrderTag(String complexOrderTag) {
    
    this.complexOrderTag = complexOrderTag;
    return this;
  }

   /**
   * 
   * @return complexOrderTag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComplexOrderTag() {
    return complexOrderTag;
  }


  @JsonProperty(JSON_PROPERTY_COMPLEX_ORDER_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComplexOrderTag(String complexOrderTag) {
    this.complexOrderTag = complexOrderTag;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * 
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder globalRequestId(String globalRequestId) {
    
    this.globalRequestId = globalRequestId;
    return this;
  }

   /**
   * 
   * @return globalRequestId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGlobalRequestId() {
    return globalRequestId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobalRequestId(String globalRequestId) {
    this.globalRequestId = globalRequestId;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder legs(List<OrderLegsInner> legs) {
    
    this.legs = legs;
    return this;
  }

  public PlacedOrderResponseComplexOrderTriggerOrder addLegsItem(OrderLegsInner legsItem) {
    if (this.legs == null) {
      this.legs = new ArrayList<>();
    }
    this.legs.add(legsItem);
    return this;
  }

   /**
   * Get legs
   * @return legs
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OrderLegsInner> getLegs() {
    return legs;
  }


  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegs(List<OrderLegsInner> legs) {
    this.legs = legs;
  }


  public PlacedOrderResponseComplexOrderTriggerOrder orderRule(OrderOrderRule orderRule) {
    
    this.orderRule = orderRule;
    return this;
  }

   /**
   * Get orderRule
   * @return orderRule
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrderOrderRule getOrderRule() {
    return orderRule;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderRule(OrderOrderRule orderRule) {
    this.orderRule = orderRule;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacedOrderResponseComplexOrderTriggerOrder placedOrderResponseComplexOrderTriggerOrder = (PlacedOrderResponseComplexOrderTriggerOrder) o;
    return Objects.equals(this.id, placedOrderResponseComplexOrderTriggerOrder.id) &&
        Objects.equals(this.accountNumber, placedOrderResponseComplexOrderTriggerOrder.accountNumber) &&
        Objects.equals(this.timeInForce, placedOrderResponseComplexOrderTriggerOrder.timeInForce) &&
        Objects.equals(this.gtcDate, placedOrderResponseComplexOrderTriggerOrder.gtcDate) &&
        Objects.equals(this.orderType, placedOrderResponseComplexOrderTriggerOrder.orderType) &&
        Objects.equals(this.size, placedOrderResponseComplexOrderTriggerOrder.size) &&
        Objects.equals(this.underlyingSymbol, placedOrderResponseComplexOrderTriggerOrder.underlyingSymbol) &&
        Objects.equals(this.underlyingInstrumentType, placedOrderResponseComplexOrderTriggerOrder.underlyingInstrumentType) &&
        Objects.equals(this.price, placedOrderResponseComplexOrderTriggerOrder.price) &&
        Objects.equals(this.priceEffect, placedOrderResponseComplexOrderTriggerOrder.priceEffect) &&
        Objects.equals(this.value, placedOrderResponseComplexOrderTriggerOrder.value) &&
        Objects.equals(this.valueEffect, placedOrderResponseComplexOrderTriggerOrder.valueEffect) &&
        Objects.equals(this.stopTrigger, placedOrderResponseComplexOrderTriggerOrder.stopTrigger) &&
        Objects.equals(this.status, placedOrderResponseComplexOrderTriggerOrder.status) &&
        Objects.equals(this.contingentStatus, placedOrderResponseComplexOrderTriggerOrder.contingentStatus) &&
        Objects.equals(this.confirmationStatus, placedOrderResponseComplexOrderTriggerOrder.confirmationStatus) &&
        Objects.equals(this.cancellable, placedOrderResponseComplexOrderTriggerOrder.cancellable) &&
        Objects.equals(this.cancelledAt, placedOrderResponseComplexOrderTriggerOrder.cancelledAt) &&
        Objects.equals(this.cancelUserId, placedOrderResponseComplexOrderTriggerOrder.cancelUserId) &&
        Objects.equals(this.cancelUsername, placedOrderResponseComplexOrderTriggerOrder.cancelUsername) &&
        Objects.equals(this.editable, placedOrderResponseComplexOrderTriggerOrder.editable) &&
        Objects.equals(this.edited, placedOrderResponseComplexOrderTriggerOrder.edited) &&
        Objects.equals(this.replacingOrderId, placedOrderResponseComplexOrderTriggerOrder.replacingOrderId) &&
        Objects.equals(this.replacesOrderId, placedOrderResponseComplexOrderTriggerOrder.replacesOrderId) &&
        Objects.equals(this.receivedAt, placedOrderResponseComplexOrderTriggerOrder.receivedAt) &&
        Objects.equals(this.updatedAt, placedOrderResponseComplexOrderTriggerOrder.updatedAt) &&
        Objects.equals(this.inFlightAt, placedOrderResponseComplexOrderTriggerOrder.inFlightAt) &&
        Objects.equals(this.liveAt, placedOrderResponseComplexOrderTriggerOrder.liveAt) &&
        Objects.equals(this.rejectReason, placedOrderResponseComplexOrderTriggerOrder.rejectReason) &&
        Objects.equals(this.userId, placedOrderResponseComplexOrderTriggerOrder.userId) &&
        Objects.equals(this.username, placedOrderResponseComplexOrderTriggerOrder.username) &&
        Objects.equals(this.terminalAt, placedOrderResponseComplexOrderTriggerOrder.terminalAt) &&
        Objects.equals(this.complexOrderId, placedOrderResponseComplexOrderTriggerOrder.complexOrderId) &&
        Objects.equals(this.complexOrderTag, placedOrderResponseComplexOrderTriggerOrder.complexOrderTag) &&
        Objects.equals(this.preflightId, placedOrderResponseComplexOrderTriggerOrder.preflightId) &&
        Objects.equals(this.globalRequestId, placedOrderResponseComplexOrderTriggerOrder.globalRequestId) &&
        Objects.equals(this.legs, placedOrderResponseComplexOrderTriggerOrder.legs) &&
        Objects.equals(this.orderRule, placedOrderResponseComplexOrderTriggerOrder.orderRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, timeInForce, gtcDate, orderType, size, underlyingSymbol, underlyingInstrumentType, price, priceEffect, value, valueEffect, stopTrigger, status, contingentStatus, confirmationStatus, cancellable, cancelledAt, cancelUserId, cancelUsername, editable, edited, replacingOrderId, replacesOrderId, receivedAt, updatedAt, inFlightAt, liveAt, rejectReason, userId, username, terminalAt, complexOrderId, complexOrderTag, preflightId, globalRequestId, legs, orderRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacedOrderResponseComplexOrderTriggerOrder {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    gtcDate: ").append(toIndentedString(gtcDate)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    underlyingSymbol: ").append(toIndentedString(underlyingSymbol)).append("\n");
    sb.append("    underlyingInstrumentType: ").append(toIndentedString(underlyingInstrumentType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceEffect: ").append(toIndentedString(priceEffect)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    sb.append("    stopTrigger: ").append(toIndentedString(stopTrigger)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    contingentStatus: ").append(toIndentedString(contingentStatus)).append("\n");
    sb.append("    confirmationStatus: ").append(toIndentedString(confirmationStatus)).append("\n");
    sb.append("    cancellable: ").append(toIndentedString(cancellable)).append("\n");
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    cancelUserId: ").append(toIndentedString(cancelUserId)).append("\n");
    sb.append("    cancelUsername: ").append(toIndentedString(cancelUsername)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    replacingOrderId: ").append(toIndentedString(replacingOrderId)).append("\n");
    sb.append("    replacesOrderId: ").append(toIndentedString(replacesOrderId)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    inFlightAt: ").append(toIndentedString(inFlightAt)).append("\n");
    sb.append("    liveAt: ").append(toIndentedString(liveAt)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    terminalAt: ").append(toIndentedString(terminalAt)).append("\n");
    sb.append("    complexOrderId: ").append(toIndentedString(complexOrderId)).append("\n");
    sb.append("    complexOrderTag: ").append(toIndentedString(complexOrderTag)).append("\n");
    sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    sb.append("    globalRequestId: ").append(toIndentedString(globalRequestId)).append("\n");
    sb.append("    legs: ").append(toIndentedString(legs)).append("\n");
    sb.append("    orderRule: ").append(toIndentedString(orderRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

