/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostAccountsAccountNumberOrdersIdDryRunLegsInner
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersIdDryRunLegsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  PostAccountsAccountNumberOrdersIdDryRunLegsInner.JSON_PROPERTY_SYMBOL,
  PostAccountsAccountNumberOrdersIdDryRunLegsInner.JSON_PROPERTY_QUANTITY,
  PostAccountsAccountNumberOrdersIdDryRunLegsInner.JSON_PROPERTY_ACTION
})
@JsonTypeName("postAccountsAccountNumberOrdersIdDryRun_legs_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersIdDryRunLegsInner {
  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private InstrumentTypeEnum instrumentType;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Double quantity;

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public PostAccountsAccountNumberOrdersIdDryRunLegsInner() {
  }

  public PostAccountsAccountNumberOrdersIdDryRunLegsInner instrumentType(InstrumentTypeEnum instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * The type of Instrument.
   * @return instrumentType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  public PostAccountsAccountNumberOrdersIdDryRunLegsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol for stock, specific option symbol in the           OCC symbology or specific future symbol. e.g. \&quot;AAPL\&quot;, \&quot;AAPL  150515C00120000\&quot;, \&quot;/ESM5\&quot;
   * @return symbol
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public PostAccountsAccountNumberOrdersIdDryRunLegsInner quantity(Double quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * TODO
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }


  public PostAccountsAccountNumberOrdersIdDryRunLegsInner action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * TODO
   * @return action
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(ActionEnum action) {
    this.action = action;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersIdDryRunLegsInner postAccountsAccountNumberOrdersIdDryRunLegsInner = (PostAccountsAccountNumberOrdersIdDryRunLegsInner) o;
    return Objects.equals(this.instrumentType, postAccountsAccountNumberOrdersIdDryRunLegsInner.instrumentType) &&
        Objects.equals(this.symbol, postAccountsAccountNumberOrdersIdDryRunLegsInner.symbol) &&
        Objects.equals(this.quantity, postAccountsAccountNumberOrdersIdDryRunLegsInner.quantity) &&
        Objects.equals(this.action, postAccountsAccountNumberOrdersIdDryRunLegsInner.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentType, symbol, quantity, action);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersIdDryRunLegsInner {\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

