/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostAccountsAccountNumberOrdersDryRunLegsInner
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersDryRunLegsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  PostAccountsAccountNumberOrdersDryRunLegsInner.JSON_PROPERTY_SYMBOL,
  PostAccountsAccountNumberOrdersDryRunLegsInner.JSON_PROPERTY_QUANTITY,
  PostAccountsAccountNumberOrdersDryRunLegsInner.JSON_PROPERTY_ACTION
})
@JsonTypeName("postAccountsAccountNumberOrdersDryRun_legs_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersDryRunLegsInner {
  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private InstrumentTypeEnum instrumentType;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Double quantity;

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public PostAccountsAccountNumberOrdersDryRunLegsInner() {
  }

  public PostAccountsAccountNumberOrdersDryRunLegsInner instrumentType(InstrumentTypeEnum instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * The type of Instrument. i.e.                                            &#x60;Cryptocurrency&#x60;, &#x60;Equity&#x60;, &#x60;Equity Offering&#x60;, &#x60;Equity Option&#x60;, &#x60;Future&#x60; or &#x60;Future Option&#x60;
   * @return instrumentType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  public PostAccountsAccountNumberOrdersDryRunLegsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * The Stock Ticker Symbol &#x60;AAPL&#x60;, OCC Option Symbol &#x60;AAPL  191004P00275000&#x60;, \\                                     TW Future Symbol &#x60;/ESZ9&#x60;, or TW Future Option Symbol &#x60;./ESZ9 EW4U9 190927P2975&#x60;
   * @return symbol
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public PostAccountsAccountNumberOrdersDryRunLegsInner quantity(Double quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * The size of the contract. Required for all orders but notional market.
   * @return quantity
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }


  public PostAccountsAccountNumberOrdersDryRunLegsInner action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * The directional action of the leg. i.e.                                   &#x60;Sell to Open&#x60;, &#x60;Sell to Close&#x60;, &#x60;Buy to Open&#x60;, &#x60;Buy to Close&#x60;, &#x60;Sell&#x60; or &#x60;Buy&#x60;.                                   Note: &#x60;Buy&#x60; and &#x60;Sell&#x60; are only applicable to Futures orders.
   * @return action
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(ActionEnum action) {
    this.action = action;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersDryRunLegsInner postAccountsAccountNumberOrdersDryRunLegsInner = (PostAccountsAccountNumberOrdersDryRunLegsInner) o;
    return Objects.equals(this.instrumentType, postAccountsAccountNumberOrdersDryRunLegsInner.instrumentType) &&
        Objects.equals(this.symbol, postAccountsAccountNumberOrdersDryRunLegsInner.symbol) &&
        Objects.equals(this.quantity, postAccountsAccountNumberOrdersDryRunLegsInner.quantity) &&
        Objects.equals(this.action, postAccountsAccountNumberOrdersDryRunLegsInner.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instrumentType, symbol, quantity, action);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersDryRunLegsInner {\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

