/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostAccountsAccountNumberOrdersDryRunRulesConditionsInner
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_ACTION,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_SYMBOL,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_INDICATOR,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_COMPARATOR,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_THRESHOLD,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInner.JSON_PROPERTY_PRICE_COMPONENTS
})
@JsonTypeName("postAccountsAccountNumberOrdersDryRun_rules_conditions_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersDryRunRulesConditionsInner {
  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private InstrumentTypeEnum instrumentType;

  /**
   * The indicator for the trigger, currently only supports &#x60;last&#x60;
   */
  public enum IndicatorEnum {
    LAST("last"),
    
    NAT("nat");

    private String value;

    IndicatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IndicatorEnum fromValue(String value) {
      for (IndicatorEnum b : IndicatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INDICATOR = "indicator";
  private IndicatorEnum indicator;

  /**
   * How to compare against the threshold. \\                                         Currently Supports &#x60;gte&#x60; (Greater than or Equal To) or &#x60;lte&#x60; (Less than or Equal to)
   */
  public enum ComparatorEnum {
    GTE("gte"),
    
    LTE("lte");

    private String value;

    ComparatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ComparatorEnum fromValue(String value) {
      for (ComparatorEnum b : ComparatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COMPARATOR = "comparator";
  private ComparatorEnum comparator;

  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  private Double threshold;

  public static final String JSON_PROPERTY_PRICE_COMPONENTS = "price-components";
  private List<PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner> priceComponents;

  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner() {
  }

  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * The action in which the trigger is enacted. i.e.                                     &#x60;route&#x60; and &#x60;cancel&#x60;
   * @return action
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * The symbol to apply the condition to. \\                                       i.e. Stock Ticker Symbol &#x60;AAPL&#x60; or the TW Future Symbol &#x60;/ESZ9&#x60;
   * @return symbol
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner instrumentType(InstrumentTypeEnum instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * The instrument&#39;s type in relation to the condition. i.e. \\                                               &#x60;Equity&#x60; or &#x60;Future&#x60;
   * @return instrumentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner indicator(IndicatorEnum indicator) {
    
    this.indicator = indicator;
    return this;
  }

   /**
   * The indicator for the trigger, currently only supports &#x60;last&#x60;
   * @return indicator
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public IndicatorEnum getIndicator() {
    return indicator;
  }


  @JsonProperty(JSON_PROPERTY_INDICATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndicator(IndicatorEnum indicator) {
    this.indicator = indicator;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner comparator(ComparatorEnum comparator) {
    
    this.comparator = comparator;
    return this;
  }

   /**
   * How to compare against the threshold. \\                                         Currently Supports &#x60;gte&#x60; (Greater than or Equal To) or &#x60;lte&#x60; (Less than or Equal to)
   * @return comparator
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ComparatorEnum getComparator() {
    return comparator;
  }


  @JsonProperty(JSON_PROPERTY_COMPARATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComparator(ComparatorEnum comparator) {
    this.comparator = comparator;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner threshold(Double threshold) {
    
    this.threshold = threshold;
    return this;
  }

   /**
   * The price at which the condition triggers.
   * @return threshold
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getThreshold() {
    return threshold;
  }


  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner priceComponents(List<PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner> priceComponents) {
    
    this.priceComponents = priceComponents;
    return this;
  }

  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInner addPriceComponentsItem(PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner priceComponentsItem) {
    if (this.priceComponents == null) {
      this.priceComponents = new ArrayList<>();
    }
    this.priceComponents.add(priceComponentsItem);
    return this;
  }

   /**
   * Get priceComponents
   * @return priceComponents
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner> getPriceComponents() {
    return priceComponents;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceComponents(List<PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner> priceComponents) {
    this.priceComponents = priceComponents;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersDryRunRulesConditionsInner postAccountsAccountNumberOrdersDryRunRulesConditionsInner = (PostAccountsAccountNumberOrdersDryRunRulesConditionsInner) o;
    return Objects.equals(this.action, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.action) &&
        Objects.equals(this.symbol, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.symbol) &&
        Objects.equals(this.instrumentType, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.instrumentType) &&
        Objects.equals(this.indicator, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.indicator) &&
        Objects.equals(this.comparator, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.comparator) &&
        Objects.equals(this.threshold, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.threshold) &&
        Objects.equals(this.priceComponents, postAccountsAccountNumberOrdersDryRunRulesConditionsInner.priceComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, symbol, instrumentType, indicator, comparator, threshold, priceComponents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersDryRunRulesConditionsInner {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    indicator: ").append(toIndentedString(indicator)).append("\n");
    sb.append("    comparator: ").append(toIndentedString(comparator)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    priceComponents: ").append(toIndentedString(priceComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

