/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Accepts a json document containing parameters to create an order and \\           then runs the prefights without placing the order.
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_TIME_IN_FORCE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_GTC_DATE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_ORDER_TYPE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_STOP_TRIGGER,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_PRICE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_PRICE_EFFECT,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_VALUE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_VALUE_EFFECT,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_SOURCE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_PARTITION_KEY,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_PREFLIGHT_ID,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_AUTOMATED_SOURCE,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_LEGS,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_RULES,
  PostAccountsAccountNumberOrdersDryRun.JSON_PROPERTY_ADVANCED_INSTRUCTIONS
})
@JsonTypeName("postAccountsAccountNumberOrdersDryRun")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersDryRun {
  public static final String JSON_PROPERTY_TIME_IN_FORCE = "time-in-force";
  private TimeInForceEnum timeInForce;

  public static final String JSON_PROPERTY_GTC_DATE = "gtc-date";
  private LocalDate gtcDate;

  public static final String JSON_PROPERTY_ORDER_TYPE = "order-type";
  private OrderTypeEnum orderType;

  public static final String JSON_PROPERTY_STOP_TRIGGER = "stop-trigger";
  private Double stopTrigger;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_PRICE_EFFECT = "price-effect";
  private PriceEffectEnum priceEffect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private ValueEffectEnum valueEffect;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_PARTITION_KEY = "partition-key";
  private String partitionKey;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public static final String JSON_PROPERTY_AUTOMATED_SOURCE = "automated-source";
  private Boolean automatedSource = false;

  public static final String JSON_PROPERTY_LEGS = "legs";
  private List<PostAccountsAccountNumberOrdersDryRunLegsInner> legs = new ArrayList<>();

  public static final String JSON_PROPERTY_RULES = "rules";
  private PostAccountsAccountNumberOrdersDryRunRules rules;

  public static final String JSON_PROPERTY_ADVANCED_INSTRUCTIONS = "advanced-instructions";
  private PostAccountsAccountNumberOrdersDryRunAdvancedInstructions advancedInstructions;

  public PostAccountsAccountNumberOrdersDryRun() {
  }

  public PostAccountsAccountNumberOrdersDryRun timeInForce(TimeInForceEnum timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * The length in time before the order expires. i.e.                                        &#x60;Day&#x60;, &#x60;GTC&#x60;, &#x60;GTD&#x60;, &#x60;Ext&#x60;, &#x60;GTC Ext&#x60; or &#x60;IOC&#x60;
   * @return timeInForce
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TimeInForceEnum getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeInForce(TimeInForceEnum timeInForce) {
    this.timeInForce = timeInForce;
  }


  public PostAccountsAccountNumberOrdersDryRun gtcDate(LocalDate gtcDate) {
    
    this.gtcDate = gtcDate;
    return this;
  }

   /**
   * The date in which a GTD order will expire
   * @return gtcDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getGtcDate() {
    return gtcDate;
  }


  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGtcDate(LocalDate gtcDate) {
    this.gtcDate = gtcDate;
  }


  public PostAccountsAccountNumberOrdersDryRun orderType(OrderTypeEnum orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * The type of order in regards to the price. i.e.                                     &#x60;Limit&#x60;, &#x60;Market&#x60;, &#x60;Marketable Limit&#x60;, &#x60;Stop&#x60;, &#x60;Stop Limit&#x60; or &#x60;Notional Market&#x60;
   * @return orderType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OrderTypeEnum getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
  }


  public PostAccountsAccountNumberOrdersDryRun stopTrigger(Double stopTrigger) {
    
    this.stopTrigger = stopTrigger;
    return this;
  }

   /**
   * The price trigger at which a stop or stop-limit order becomes valid.
   * @return stopTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getStopTrigger() {
    return stopTrigger;
  }


  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopTrigger(Double stopTrigger) {
    this.stopTrigger = stopTrigger;
  }


  public PostAccountsAccountNumberOrdersDryRun price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * The price of the Order. Required for limit and stop-limit orders.
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public PostAccountsAccountNumberOrdersDryRun priceEffect(PriceEffectEnum priceEffect) {
    
    this.priceEffect = priceEffect;
    return this;
  }

   /**
   * If pay or receive payment for placing the order. i.e. &#x60;Credit&#x60; or &#x60;Debit&#x60;
   * @return priceEffect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PriceEffectEnum getPriceEffect() {
    return priceEffect;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPriceEffect(PriceEffectEnum priceEffect) {
    this.priceEffect = priceEffect;
  }


  public PostAccountsAccountNumberOrdersDryRun value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * The notional value of the Order, required for notional market orders.
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public PostAccountsAccountNumberOrdersDryRun valueEffect(ValueEffectEnum valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * If pay or receive payment for placing the notional market order. i.e. &#x60;Credit&#x60; or &#x60;Debit&#x60;
   * @return valueEffect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ValueEffectEnum getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValueEffect(ValueEffectEnum valueEffect) {
    this.valueEffect = valueEffect;
  }


  public PostAccountsAccountNumberOrdersDryRun source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * The source the order is coming from
   * @return source
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(String source) {
    this.source = source;
  }


  public PostAccountsAccountNumberOrdersDryRun partitionKey(String partitionKey) {
    
    this.partitionKey = partitionKey;
    return this;
  }

   /**
   * Account partition key
   * @return partitionKey
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTITION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartitionKey() {
    return partitionKey;
  }


  @JsonProperty(JSON_PROPERTY_PARTITION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartitionKey(String partitionKey) {
    this.partitionKey = partitionKey;
  }


  public PostAccountsAccountNumberOrdersDryRun preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * Transient order identifier used for matching preflight errors to an individual order
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }


  public PostAccountsAccountNumberOrdersDryRun automatedSource(Boolean automatedSource) {
    
    this.automatedSource = automatedSource;
    return this;
  }

   /**
   * If the order was placed from an automated source
   * @return automatedSource
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTOMATED_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutomatedSource() {
    return automatedSource;
  }


  @JsonProperty(JSON_PROPERTY_AUTOMATED_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutomatedSource(Boolean automatedSource) {
    this.automatedSource = automatedSource;
  }


  public PostAccountsAccountNumberOrdersDryRun legs(List<PostAccountsAccountNumberOrdersDryRunLegsInner> legs) {
    
    this.legs = legs;
    return this;
  }

  public PostAccountsAccountNumberOrdersDryRun addLegsItem(PostAccountsAccountNumberOrdersDryRunLegsInner legsItem) {
    if (this.legs == null) {
      this.legs = new ArrayList<>();
    }
    this.legs.add(legsItem);
    return this;
  }

   /**
   * Get legs
   * @return legs
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PostAccountsAccountNumberOrdersDryRunLegsInner> getLegs() {
    return legs;
  }


  @JsonProperty(JSON_PROPERTY_LEGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegs(List<PostAccountsAccountNumberOrdersDryRunLegsInner> legs) {
    this.legs = legs;
  }


  public PostAccountsAccountNumberOrdersDryRun rules(PostAccountsAccountNumberOrdersDryRunRules rules) {
    
    this.rules = rules;
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostAccountsAccountNumberOrdersDryRunRules getRules() {
    return rules;
  }


  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRules(PostAccountsAccountNumberOrdersDryRunRules rules) {
    this.rules = rules;
  }


  public PostAccountsAccountNumberOrdersDryRun advancedInstructions(PostAccountsAccountNumberOrdersDryRunAdvancedInstructions advancedInstructions) {
    
    this.advancedInstructions = advancedInstructions;
    return this;
  }

   /**
   * Get advancedInstructions
   * @return advancedInstructions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADVANCED_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostAccountsAccountNumberOrdersDryRunAdvancedInstructions getAdvancedInstructions() {
    return advancedInstructions;
  }


  @JsonProperty(JSON_PROPERTY_ADVANCED_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvancedInstructions(PostAccountsAccountNumberOrdersDryRunAdvancedInstructions advancedInstructions) {
    this.advancedInstructions = advancedInstructions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersDryRun postAccountsAccountNumberOrdersDryRun = (PostAccountsAccountNumberOrdersDryRun) o;
    return Objects.equals(this.timeInForce, postAccountsAccountNumberOrdersDryRun.timeInForce) &&
        Objects.equals(this.gtcDate, postAccountsAccountNumberOrdersDryRun.gtcDate) &&
        Objects.equals(this.orderType, postAccountsAccountNumberOrdersDryRun.orderType) &&
        Objects.equals(this.stopTrigger, postAccountsAccountNumberOrdersDryRun.stopTrigger) &&
        Objects.equals(this.price, postAccountsAccountNumberOrdersDryRun.price) &&
        Objects.equals(this.priceEffect, postAccountsAccountNumberOrdersDryRun.priceEffect) &&
        Objects.equals(this.value, postAccountsAccountNumberOrdersDryRun.value) &&
        Objects.equals(this.valueEffect, postAccountsAccountNumberOrdersDryRun.valueEffect) &&
        Objects.equals(this.source, postAccountsAccountNumberOrdersDryRun.source) &&
        Objects.equals(this.partitionKey, postAccountsAccountNumberOrdersDryRun.partitionKey) &&
        Objects.equals(this.preflightId, postAccountsAccountNumberOrdersDryRun.preflightId) &&
        Objects.equals(this.automatedSource, postAccountsAccountNumberOrdersDryRun.automatedSource) &&
        Objects.equals(this.legs, postAccountsAccountNumberOrdersDryRun.legs) &&
        Objects.equals(this.rules, postAccountsAccountNumberOrdersDryRun.rules) &&
        Objects.equals(this.advancedInstructions, postAccountsAccountNumberOrdersDryRun.advancedInstructions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeInForce, gtcDate, orderType, stopTrigger, price, priceEffect, value, valueEffect, source, partitionKey, preflightId, automatedSource, legs, rules, advancedInstructions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersDryRun {\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    gtcDate: ").append(toIndentedString(gtcDate)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    stopTrigger: ").append(toIndentedString(stopTrigger)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceEffect: ").append(toIndentedString(priceEffect)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    partitionKey: ").append(toIndentedString(partitionKey)).append("\n");
    sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    sb.append("    automatedSource: ").append(toIndentedString(automatedSource)).append("\n");
    sb.append("    legs: ").append(toIndentedString(legs)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    advancedInstructions: ").append(toIndentedString(advancedInstructions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

