/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.JSON_PROPERTY_SYMBOL,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.JSON_PROPERTY_INSTRUMENT_TYPE,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.JSON_PROPERTY_QUANTITY,
  PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.JSON_PROPERTY_QUANTITY_DIRECTION
})
@JsonTypeName("postAccountsAccountNumberOrdersDryRun_rules_conditions_inner_price_components_inner")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_INSTRUMENT_TYPE = "instrument-type";
  private InstrumentTypeEnum instrumentType;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Double quantity;

  /**
   * The quantity direction(ie Long or Short) in relation to the symbol
   */
  public enum QuantityDirectionEnum {
    LONG("Long"),
    
    SHORT("Short");

    private String value;

    QuantityDirectionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static QuantityDirectionEnum fromValue(String value) {
      for (QuantityDirectionEnum b : QuantityDirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_QUANTITY_DIRECTION = "quantity-direction";
  private QuantityDirectionEnum quantityDirection;

  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner() {
  }

  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * The symbol to apply the condition to. \\                                       i.e. Stock Ticker Symbol &#x60;AAPL&#x60; or the TW Future Symbol &#x60;/ESZ9&#x60;
   * @return symbol
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner instrumentType(InstrumentTypeEnum instrumentType) {
    
    this.instrumentType = instrumentType;
    return this;
  }

   /**
   * The instrument&#39;s type in relation to the symbol.
   * @return instrumentType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InstrumentTypeEnum getInstrumentType() {
    return instrumentType;
  }


  @JsonProperty(JSON_PROPERTY_INSTRUMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInstrumentType(InstrumentTypeEnum instrumentType) {
    this.instrumentType = instrumentType;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner quantity(Double quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * The Ratio quantity in relation to the symbol
   * @return quantity
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }


  public PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner quantityDirection(QuantityDirectionEnum quantityDirection) {
    
    this.quantityDirection = quantityDirection;
    return this;
  }

   /**
   * The quantity direction(ie Long or Short) in relation to the symbol
   * @return quantityDirection
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public QuantityDirectionEnum getQuantityDirection() {
    return quantityDirection;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantityDirection(QuantityDirectionEnum quantityDirection) {
    this.quantityDirection = quantityDirection;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner postAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner = (PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner) o;
    return Objects.equals(this.symbol, postAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.symbol) &&
        Objects.equals(this.instrumentType, postAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.instrumentType) &&
        Objects.equals(this.quantity, postAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.quantity) &&
        Objects.equals(this.quantityDirection, postAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner.quantityDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, instrumentType, quantity, quantityDirection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersDryRunRulesConditionsInnerPriceComponentsInner {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    instrumentType: ").append(toIndentedString(instrumentType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    quantityDirection: ").append(toIndentedString(quantityDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

