/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostAccountsAccountNumberOrdersDryRunAdvancedInstructions
 */
@JsonPropertyOrder({
  PostAccountsAccountNumberOrdersDryRunAdvancedInstructions.JSON_PROPERTY_STRICT_POSITION_EFFECT_VALIDATION
})
@JsonTypeName("postAccountsAccountNumberOrdersDryRun_advanced_instructions")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PostAccountsAccountNumberOrdersDryRunAdvancedInstructions {
  public static final String JSON_PROPERTY_STRICT_POSITION_EFFECT_VALIDATION = "strict-position-effect-validation";
  private Boolean strictPositionEffectValidation = false;

  public PostAccountsAccountNumberOrdersDryRunAdvancedInstructions() {
  }

  public PostAccountsAccountNumberOrdersDryRunAdvancedInstructions strictPositionEffectValidation(Boolean strictPositionEffectValidation) {
    
    this.strictPositionEffectValidation = strictPositionEffectValidation;
    return this;
  }

   /**
   * If the order should be rejected the open/close position effect is not valid
   * @return strictPositionEffectValidation
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STRICT_POSITION_EFFECT_VALIDATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStrictPositionEffectValidation() {
    return strictPositionEffectValidation;
  }


  @JsonProperty(JSON_PROPERTY_STRICT_POSITION_EFFECT_VALIDATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrictPositionEffectValidation(Boolean strictPositionEffectValidation) {
    this.strictPositionEffectValidation = strictPositionEffectValidation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountsAccountNumberOrdersDryRunAdvancedInstructions postAccountsAccountNumberOrdersDryRunAdvancedInstructions = (PostAccountsAccountNumberOrdersDryRunAdvancedInstructions) o;
    return Objects.equals(this.strictPositionEffectValidation, postAccountsAccountNumberOrdersDryRunAdvancedInstructions.strictPositionEffectValidation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(strictPositionEffectValidation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountsAccountNumberOrdersDryRunAdvancedInstructions {\n");
    sb.append("    strictPositionEffectValidation: ").append(toIndentedString(strictPositionEffectValidation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

