/*
 * Orders
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.195.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.orders;

import java.time.LocalDate;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Replaces a live order with a new one. Subsequent fills of the original order will abort the replacement.
 */
@JsonPropertyOrder({
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_TIME_IN_FORCE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_GTC_DATE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_ORDER_TYPE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_STOP_TRIGGER,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_PRICE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_PRICE_EFFECT,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_VALUE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_VALUE_EFFECT,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_SOURCE,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_PARTITION_KEY,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_PREFLIGHT_ID,
  PutAccountsAccountNumberOrdersId.JSON_PROPERTY_AUTOMATED_SOURCE
})
@JsonTypeName("putAccountsAccountNumberOrdersId")
@JsonIgnoreProperties(ignoreUnknown = true)
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:39:11.883498700+01:00[Europe/Berlin]")
public class PutAccountsAccountNumberOrdersId {
  public static final String JSON_PROPERTY_TIME_IN_FORCE = "time-in-force";
  private TimeInForceEnum timeInForce;

  public static final String JSON_PROPERTY_GTC_DATE = "gtc-date";
  private LocalDate gtcDate;

  public static final String JSON_PROPERTY_ORDER_TYPE = "order-type";
  private OrderTypeEnum orderType;

  public static final String JSON_PROPERTY_STOP_TRIGGER = "stop-trigger";
  private Double stopTrigger;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_PRICE_EFFECT = "price-effect";
  private PriceEffectEnum priceEffect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Double value;

  public static final String JSON_PROPERTY_VALUE_EFFECT = "value-effect";
  private ValueEffectEnum valueEffect;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_PARTITION_KEY = "partition-key";
  private String partitionKey;

  public static final String JSON_PROPERTY_PREFLIGHT_ID = "preflight-id";
  private String preflightId;

  public static final String JSON_PROPERTY_AUTOMATED_SOURCE = "automated-source";
  private Boolean automatedSource = false;

  public PutAccountsAccountNumberOrdersId() {
  }

  public PutAccountsAccountNumberOrdersId timeInForce(TimeInForceEnum timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * The length in time before the order expires. i.e.                                        &#x60;Day&#x60;, &#x60;GTC&#x60;, &#x60;GTD&#x60;, &#x60;Ext&#x60;, &#x60;GTC Ext&#x60; or &#x60;IOC&#x60;
   * @return timeInForce
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TimeInForceEnum getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeInForce(TimeInForceEnum timeInForce) {
    this.timeInForce = timeInForce;
  }


  public PutAccountsAccountNumberOrdersId gtcDate(LocalDate gtcDate) {
    
    this.gtcDate = gtcDate;
    return this;
  }

   /**
   * The date in which a GTD order will expire
   * @return gtcDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getGtcDate() {
    return gtcDate;
  }


  @JsonProperty(JSON_PROPERTY_GTC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGtcDate(LocalDate gtcDate) {
    this.gtcDate = gtcDate;
  }


  public PutAccountsAccountNumberOrdersId orderType(OrderTypeEnum orderType) {
    
    this.orderType = orderType;
    return this;
  }

   /**
   * The type of order in regards to the price. i.e.                                     &#x60;Limit&#x60;, &#x60;Market&#x60;, &#x60;Marketable Limit&#x60;, &#x60;Stop&#x60;, &#x60;Stop Limit&#x60; or &#x60;Notional Market&#x60;
   * @return orderType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OrderTypeEnum getOrderType() {
    return orderType;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
  }


  public PutAccountsAccountNumberOrdersId stopTrigger(Double stopTrigger) {
    
    this.stopTrigger = stopTrigger;
    return this;
  }

   /**
   * The price trigger at which a stop or stop-limit order becomes valid.
   * @return stopTrigger
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getStopTrigger() {
    return stopTrigger;
  }


  @JsonProperty(JSON_PROPERTY_STOP_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopTrigger(Double stopTrigger) {
    this.stopTrigger = stopTrigger;
  }


  public PutAccountsAccountNumberOrdersId price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * The price of the Order. Required for limit and stop-limit orders.
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(Double price) {
    this.price = price;
  }


  public PutAccountsAccountNumberOrdersId priceEffect(PriceEffectEnum priceEffect) {
    
    this.priceEffect = priceEffect;
    return this;
  }

   /**
   * If pay or receive payment for placing the order. i.e. &#x60;Credit&#x60; or &#x60;Debit&#x60;
   * @return priceEffect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PriceEffectEnum getPriceEffect() {
    return priceEffect;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPriceEffect(PriceEffectEnum priceEffect) {
    this.priceEffect = priceEffect;
  }


  public PutAccountsAccountNumberOrdersId value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * The notional value of the Order, required for notional market orders.
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(Double value) {
    this.value = value;
  }


  public PutAccountsAccountNumberOrdersId valueEffect(ValueEffectEnum valueEffect) {
    
    this.valueEffect = valueEffect;
    return this;
  }

   /**
   * If pay or receive payment for placing the notional market order. i.e. &#x60;Credit&#x60; or &#x60;Debit&#x60;
   * @return valueEffect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ValueEffectEnum getValueEffect() {
    return valueEffect;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValueEffect(ValueEffectEnum valueEffect) {
    this.valueEffect = valueEffect;
  }


  public PutAccountsAccountNumberOrdersId source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * The source the order is coming from
   * @return source
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(String source) {
    this.source = source;
  }


  public PutAccountsAccountNumberOrdersId partitionKey(String partitionKey) {
    
    this.partitionKey = partitionKey;
    return this;
  }

   /**
   * Account partition key
   * @return partitionKey
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTITION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartitionKey() {
    return partitionKey;
  }


  @JsonProperty(JSON_PROPERTY_PARTITION_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartitionKey(String partitionKey) {
    this.partitionKey = partitionKey;
  }


  public PutAccountsAccountNumberOrdersId preflightId(String preflightId) {
    
    this.preflightId = preflightId;
    return this;
  }

   /**
   * Transient order identifier used for matching preflight errors to an individual order
   * @return preflightId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreflightId() {
    return preflightId;
  }


  @JsonProperty(JSON_PROPERTY_PREFLIGHT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreflightId(String preflightId) {
    this.preflightId = preflightId;
  }


  public PutAccountsAccountNumberOrdersId automatedSource(Boolean automatedSource) {
    
    this.automatedSource = automatedSource;
    return this;
  }

   /**
   * If the order was placed from an automated source
   * @return automatedSource
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTOMATED_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutomatedSource() {
    return automatedSource;
  }


  @JsonProperty(JSON_PROPERTY_AUTOMATED_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutomatedSource(Boolean automatedSource) {
    this.automatedSource = automatedSource;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutAccountsAccountNumberOrdersId putAccountsAccountNumberOrdersId = (PutAccountsAccountNumberOrdersId) o;
    return Objects.equals(this.timeInForce, putAccountsAccountNumberOrdersId.timeInForce) &&
        Objects.equals(this.gtcDate, putAccountsAccountNumberOrdersId.gtcDate) &&
        Objects.equals(this.orderType, putAccountsAccountNumberOrdersId.orderType) &&
        Objects.equals(this.stopTrigger, putAccountsAccountNumberOrdersId.stopTrigger) &&
        Objects.equals(this.price, putAccountsAccountNumberOrdersId.price) &&
        Objects.equals(this.priceEffect, putAccountsAccountNumberOrdersId.priceEffect) &&
        Objects.equals(this.value, putAccountsAccountNumberOrdersId.value) &&
        Objects.equals(this.valueEffect, putAccountsAccountNumberOrdersId.valueEffect) &&
        Objects.equals(this.source, putAccountsAccountNumberOrdersId.source) &&
        Objects.equals(this.partitionKey, putAccountsAccountNumberOrdersId.partitionKey) &&
        Objects.equals(this.preflightId, putAccountsAccountNumberOrdersId.preflightId) &&
        Objects.equals(this.automatedSource, putAccountsAccountNumberOrdersId.automatedSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeInForce, gtcDate, orderType, stopTrigger, price, priceEffect, value, valueEffect, source, partitionKey, preflightId, automatedSource);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutAccountsAccountNumberOrdersId {\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    gtcDate: ").append(toIndentedString(gtcDate)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    stopTrigger: ").append(toIndentedString(stopTrigger)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceEffect: ").append(toIndentedString(priceEffect)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueEffect: ").append(toIndentedString(valueEffect)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    partitionKey: ").append(toIndentedString(partitionKey)).append("\n");
    sb.append("    preflightId: ").append(toIndentedString(preflightId)).append("\n");
    sb.append("    automatedSource: ").append(toIndentedString(automatedSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

