/*
 * Net Liquidating Value History
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.22.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stockmarketpotato.integration.tastytrade.model.netliq;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents the open, high, low, close values for a time interval. The &#x60;close&#x60; value is the value at &#x60;time&#x60;. Also includes pending cash values and a sum of the two for convenience.
 */
@JsonPropertyOrder({
  NetLiqOhlc.JSON_PROPERTY_OPEN,
  NetLiqOhlc.JSON_PROPERTY_HIGH,
  NetLiqOhlc.JSON_PROPERTY_LOW,
  NetLiqOhlc.JSON_PROPERTY_CLOSE,
  NetLiqOhlc.JSON_PROPERTY_PENDING_CASH_OPEN,
  NetLiqOhlc.JSON_PROPERTY_PENDING_CASH_HIGH,
  NetLiqOhlc.JSON_PROPERTY_PENDING_CASH_LOW,
  NetLiqOhlc.JSON_PROPERTY_PENDING_CASH_CLOSE,
  NetLiqOhlc.JSON_PROPERTY_TOTAL_OPEN,
  NetLiqOhlc.JSON_PROPERTY_TOTAL_HIGH,
  NetLiqOhlc.JSON_PROPERTY_TOTAL_LOW,
  NetLiqOhlc.JSON_PROPERTY_TOTAL_CLOSE,
  NetLiqOhlc.JSON_PROPERTY_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-18T13:42:14.901615900+02:00[Europe/Berlin]")
public class NetLiqOhlc {
  public static final String JSON_PROPERTY_OPEN = "open";
  private Double open;

  public static final String JSON_PROPERTY_HIGH = "high";
  private Double high;

  public static final String JSON_PROPERTY_LOW = "low";
  private Double low;

  public static final String JSON_PROPERTY_CLOSE = "close";
  private Double close;

  public static final String JSON_PROPERTY_PENDING_CASH_OPEN = "pending-cash-open";
  private Double pendingCashOpen;

  public static final String JSON_PROPERTY_PENDING_CASH_HIGH = "pending-cash-high";
  private Double pendingCashHigh;

  public static final String JSON_PROPERTY_PENDING_CASH_LOW = "pending-cash-low";
  private Double pendingCashLow;

  public static final String JSON_PROPERTY_PENDING_CASH_CLOSE = "pending-cash-close";
  private Double pendingCashClose;

  public static final String JSON_PROPERTY_TOTAL_OPEN = "total-open";
  private Double totalOpen;

  public static final String JSON_PROPERTY_TOTAL_HIGH = "total-high";
  private Double totalHigh;

  public static final String JSON_PROPERTY_TOTAL_LOW = "total-low";
  private Double totalLow;

  public static final String JSON_PROPERTY_TOTAL_CLOSE = "total-close";
  private Double totalClose;

  public static final String JSON_PROPERTY_TIME = "time";
  @JsonFormat(shape=JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ssx")
  private OffsetDateTime time;
  
  /**
   * The type of order in regards to the price. i.e.                                     &#x60;Limit&#x60;, &#x60;Market&#x60;, &#x60;Marketable Limit&#x60;, &#x60;Stop&#x60;, &#x60;Stop Limit&#x60; or &#x60;Notional Market&#x60;
   */
	public enum TimeBackEnum {
		WEEK("1w"), // 1 week of data in 15 minute intervals
		MONTH("1m"), // 1 month of data in 1 hour intervals
		QUARTER("3m"), // 3 months of data in 1 day intervals
		HALF_YEAR("6m"), // 6 months of data in 1 day intervals
		YEAR("1y"), // 1 year of data in 1 day intervals
		ALL("all"); // All historical data in 1 day intervals

		private String value;

		TimeBackEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TimeBackEnum fromValue(String value) {
			for (TimeBackEnum b : TimeBackEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}
	}
  
  public NetLiqOhlc() {
  }

  public NetLiqOhlc open(Double open) {
    
    this.open = open;
    return this;
  }

   /**
   * Net liq at start of time interval
   * @return open
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getOpen() {
    return open;
  }


  @JsonProperty(JSON_PROPERTY_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpen(Double open) {
    this.open = open;
  }


  public NetLiqOhlc high(Double high) {
    
    this.high = high;
    return this;
  }

   /**
   * Max Net liq during time interval
   * @return high
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getHigh() {
    return high;
  }


  @JsonProperty(JSON_PROPERTY_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHigh(Double high) {
    this.high = high;
  }


  public NetLiqOhlc low(Double low) {
    
    this.low = low;
    return this;
  }

   /**
   * Min Net liq during time interval
   * @return low
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLow() {
    return low;
  }


  @JsonProperty(JSON_PROPERTY_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLow(Double low) {
    this.low = low;
  }


  public NetLiqOhlc close(Double close) {
    
    this.close = close;
    return this;
  }

   /**
   * Net liq at &#x60;time&#x60;
   * @return close
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getClose() {
    return close;
  }


  @JsonProperty(JSON_PROPERTY_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClose(Double close) {
    this.close = close;
  }


  public NetLiqOhlc pendingCashOpen(Double pendingCashOpen) {
    
    this.pendingCashOpen = pendingCashOpen;
    return this;
  }

   /**
   * Pending cash at start of time interval
   * @return pendingCashOpen
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPendingCashOpen() {
    return pendingCashOpen;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCashOpen(Double pendingCashOpen) {
    this.pendingCashOpen = pendingCashOpen;
  }


  public NetLiqOhlc pendingCashHigh(Double pendingCashHigh) {
    
    this.pendingCashHigh = pendingCashHigh;
    return this;
  }

   /**
   * Max pending cash during time interval
   * @return pendingCashHigh
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPendingCashHigh() {
    return pendingCashHigh;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCashHigh(Double pendingCashHigh) {
    this.pendingCashHigh = pendingCashHigh;
  }


  public NetLiqOhlc pendingCashLow(Double pendingCashLow) {
    
    this.pendingCashLow = pendingCashLow;
    return this;
  }

   /**
   * Min pending cash during time interval
   * @return pendingCashLow
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPendingCashLow() {
    return pendingCashLow;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCashLow(Double pendingCashLow) {
    this.pendingCashLow = pendingCashLow;
  }


  public NetLiqOhlc pendingCashClose(Double pendingCashClose) {
    
    this.pendingCashClose = pendingCashClose;
    return this;
  }

   /**
   * Pending cash at &#x60;time&#x60;
   * @return pendingCashClose
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_CASH_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPendingCashClose() {
    return pendingCashClose;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_CASH_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingCashClose(Double pendingCashClose) {
    this.pendingCashClose = pendingCashClose;
  }


  public NetLiqOhlc totalOpen(Double totalOpen) {
    
    this.totalOpen = totalOpen;
    return this;
  }

   /**
   * open + pending-cash-open
   * @return totalOpen
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalOpen() {
    return totalOpen;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_OPEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalOpen(Double totalOpen) {
    this.totalOpen = totalOpen;
  }


  public NetLiqOhlc totalHigh(Double totalHigh) {
    
    this.totalHigh = totalHigh;
    return this;
  }

   /**
   * high + pending-cash-high
   * @return totalHigh
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalHigh() {
    return totalHigh;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_HIGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalHigh(Double totalHigh) {
    this.totalHigh = totalHigh;
  }


  public NetLiqOhlc totalLow(Double totalLow) {
    
    this.totalLow = totalLow;
    return this;
  }

   /**
   * low + pending-cash-low
   * @return totalLow
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalLow() {
    return totalLow;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_LOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalLow(Double totalLow) {
    this.totalLow = totalLow;
  }


  public NetLiqOhlc totalClose(Double totalClose) {
    
    this.totalClose = totalClose;
    return this;
  }

   /**
   * close + pending-cash-close
   * @return totalClose
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalClose() {
    return totalClose;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_CLOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalClose(Double totalClose) {
    this.totalClose = totalClose;
  }


  public NetLiqOhlc time(OffsetDateTime time) {
    
    this.time = time;
    return this;
  }

   /**
   * Timestamp
   * @return time
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetLiqOhlc netLiqOhlc = (NetLiqOhlc) o;
    return Objects.equals(this.open, netLiqOhlc.open) &&
        Objects.equals(this.high, netLiqOhlc.high) &&
        Objects.equals(this.low, netLiqOhlc.low) &&
        Objects.equals(this.close, netLiqOhlc.close) &&
        Objects.equals(this.pendingCashOpen, netLiqOhlc.pendingCashOpen) &&
        Objects.equals(this.pendingCashHigh, netLiqOhlc.pendingCashHigh) &&
        Objects.equals(this.pendingCashLow, netLiqOhlc.pendingCashLow) &&
        Objects.equals(this.pendingCashClose, netLiqOhlc.pendingCashClose) &&
        Objects.equals(this.totalOpen, netLiqOhlc.totalOpen) &&
        Objects.equals(this.totalHigh, netLiqOhlc.totalHigh) &&
        Objects.equals(this.totalLow, netLiqOhlc.totalLow) &&
        Objects.equals(this.totalClose, netLiqOhlc.totalClose) &&
        Objects.equals(this.time, netLiqOhlc.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(open, high, low, close, pendingCashOpen, pendingCashHigh, pendingCashLow, pendingCashClose, totalOpen, totalHigh, totalLow, totalClose, time);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetLiqOhlc {\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    pendingCashOpen: ").append(toIndentedString(pendingCashOpen)).append("\n");
    sb.append("    pendingCashHigh: ").append(toIndentedString(pendingCashHigh)).append("\n");
    sb.append("    pendingCashLow: ").append(toIndentedString(pendingCashLow)).append("\n");
    sb.append("    pendingCashClose: ").append(toIndentedString(pendingCashClose)).append("\n");
    sb.append("    totalOpen: ").append(toIndentedString(totalOpen)).append("\n");
    sb.append("    totalHigh: ").append(toIndentedString(totalHigh)).append("\n");
    sb.append("    totalLow: ").append(toIndentedString(totalLow)).append("\n");
    sb.append("    totalClose: ").append(toIndentedString(totalClose)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

